# Generated by Django 3.2.25 on 2026-01-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_follower', models.BooleanField(default=True)),
                ('notify_follow_request', models.BooleanField(default=True)),
                ('notify_recipe_comment', models.BooleanField(default=True)),
                ('notify_recipe_rating', models.BooleanField(default=True)),
                ('notify_comment_reply', models.BooleanField(default=True)),
                ('notify_following_new_recipe', models.BooleanField(default=True)),
                ('email_digest', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
