# Generated by Django 3.2.25 on 2026-01-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0007_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_recipes', models.BooleanField(default=True)),
                ('show_ratings', models.BooleanField(default=True)),
                ('show_comments', models.BooleanField(default=False)),
                ('show_favorites', models.BooleanField(default=False)),
                ('feed_order', models.CharField(choices=[('chronological', 'Chronological'), ('algorithmic', 'Algorithmic')], default='chronological', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
