# Generated by Django 3.2.25 on 2026-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_feedpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=50)),
                ('badge_type', models.CharField(choices=[('verified', 'Verified'), ('achievement', 'Achievement')], max_length=15)),
                ('criteria', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
