INDIAN_RECIPES = [
    {
        "title": "Dal Tadka",
        "description": "Yellow lentils tempered with cumin, garlic, and dried red chilies. A staple comfort food across India.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein"],
        "instructions": "1. Wash and soak toor dal for 15 minutes, then drain.\n2. Pressure cook dal with turmeric and salt with 3 cups water for 3 whistles.\n3. Mash the cooked dal and set aside.\n4. Heat oil in a small pan and add cumin seeds, letting them splutter.\n5. Add chopped garlic, dried red chilies, and sliced onion. Saute until golden.\n6. Add chopped tomatoes and cook until soft.\n7. Pour the tempering over the dal and stir well.\n8. Garnish with fresh cilantro and serve hot with rice.",
        "ingredients": [
            ("Toor dal", 1.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Dried red chilies", 2.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Salt", 1.0, "to taste"),
            ("Oil", 2.0, "tbsp"),
            ("Fresh cilantro", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Chana Masala",
        "description": "Spiced chickpea curry cooked with tomatoes and a blend of aromatic spices. Hearty and protein-rich.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Heat oil in a deep pan and add cumin seeds until they splutter.\n2. Add finely chopped onions and saute until deep golden brown.\n3. Add ginger-garlic paste and cook for one minute.\n4. Add chopped tomatoes, turmeric, coriander powder, and chili powder. Cook until oil separates.\n5. Add drained chickpeas and one cup of water. Stir well.\n6. Add chana masala powder and salt. Cover and simmer for 20 minutes.\n7. Mash a few chickpeas against the side of the pan to thicken the gravy.\n8. Garnish with cilantro and a squeeze of lemon juice before serving.",
        "ingredients": [
            ("Chickpeas", 2.0, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 3.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Chana masala powder", 1.0, "tbsp"),
            ("Oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Aloo Gobi",
        "description": "Dry-style potato and cauliflower curry seasoned with turmeric and cumin. A classic North Indian side dish.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Cut potatoes into cubes and cauliflower into small florets.\n2. Heat oil in a pan and add cumin seeds until they crackle.\n3. Add diced onion and saute until translucent.\n4. Add turmeric, coriander powder, and red chili powder. Stir for 30 seconds.\n5. Add potatoes and cauliflower. Toss to coat with spices.\n6. Cover and cook on low heat for 20 minutes, stirring occasionally.\n7. Add salt and garam masala. Cook uncovered for 5 more minutes until vegetables are tender.\n8. Garnish with fresh cilantro and serve with roti.",
        "ingredients": [
            ("Potato", 3.0, "pieces"),
            ("Cauliflower", 1.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Garam masala", 0.5, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Rajma",
        "description": "Kidney bean curry in a thick tomato-onion gravy. A beloved Punjabi comfort dish served with rice.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 45,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Soak rajma overnight, then pressure cook with salt until soft, about 5 whistles.\n2. Heat oil and add bay leaf and cumin seeds.\n3. Add finely chopped onions and cook until golden brown.\n4. Add ginger-garlic paste and saute for a minute.\n5. Add pureed tomatoes, turmeric, coriander powder, and chili powder. Cook until oil separates.\n6. Add cooked rajma along with its cooking liquid. Mix well.\n7. Simmer on low heat for 20 minutes until the gravy thickens. Add garam masala.\n8. Serve hot over steamed basmati rice with a squeeze of lemon.",
        "ingredients": [
            ("Kidney beans", 1.5, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 3.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Bay leaf", 1.0, "pieces"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Garam masala", 1.0, "tsp"),
            ("Oil", 3.0, "tbsp"),
        ],
    },
    {
        "title": "Sambar",
        "description": "South Indian lentil and vegetable stew flavored with tamarind and sambar powder. Pairs perfectly with rice or idli.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "one-pot", "budget"],
        "instructions": "1. Cook toor dal with turmeric in a pressure cooker for 3 whistles.\n2. Chop drumstick, carrots, and potatoes into pieces. Boil until tender.\n3. Mix tamarind paste with half a cup of warm water and extract the juice.\n4. Combine cooked dal, vegetables, and tamarind water in a pot. Add sambar powder and salt.\n5. Bring to a boil and simmer for 10 minutes.\n6. Heat oil in a small pan, add mustard seeds, curry leaves, and dried red chilies.\n7. Pour the tempering into the sambar and stir well.\n8. Serve hot with steamed rice, idli, or dosa.",
        "ingredients": [
            ("Toor dal", 1.0, "cups"),
            ("Drumstick", 1.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Potato", 1.0, "pieces"),
            ("Tamarind paste", 1.0, "tbsp"),
            ("Sambar powder", 2.0, "tbsp"),
            ("Mustard seeds", 1.0, "tsp"),
            ("Curry leaves", 8.0, "pieces"),
            ("Dried red chilies", 2.0, "pieces"),
            ("Oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Palak Dal",
        "description": "Spinach and lentil curry with a light tempering. Nutritious, iron-rich, and deeply flavorful.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Wash moong dal and pressure cook with turmeric for 3 whistles.\n2. Blanch spinach in boiling water for 2 minutes, then puree coarsely.\n3. Mix the dal and spinach puree together in a pot. Add salt and simmer.\n4. Heat ghee in a small pan and add cumin seeds and asafoetida.\n5. Add chopped garlic and dried red chilies. Fry until garlic is golden.\n6. Pour the tempering over the dal-spinach mixture and stir.\n7. Serve hot with steamed rice or roti.",
        "ingredients": [
            ("Moong dal", 1.0, "cups"),
            ("Spinach", 4.0, "cups"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Dried red chilies", 2.0, "pieces"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Asafoetida", 0.25, "tsp"),
            ("Ghee", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Egg Curry",
        "description": "Hard-boiled eggs simmered in a spiced onion-tomato gravy. A quick, protein-packed meal.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget", "quick"],
        "instructions": "1. Hard boil eggs, peel, and make small slits on the surface.\n2. Heat oil and saute sliced onions until golden brown.\n3. Add ginger-garlic paste and cook for a minute.\n4. Add chopped tomatoes, turmeric, chili powder, and coriander powder. Cook until soft.\n5. Add half a cup of water and bring to a simmer.\n6. Gently add the boiled eggs and coat them in the gravy.\n7. Simmer for 10 minutes, then add garam masala.\n8. Garnish with cilantro and serve with rice or paratha.",
        "ingredients": [
            ("Eggs", 6.0, "pieces"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Garam masala", 0.5, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Fresh cilantro", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Aloo Matar",
        "description": "Potato and green pea curry in a light tomato gravy. Simple, homestyle, and universally loved.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Heat oil in a pan and add cumin seeds until they splutter.\n2. Add finely chopped onions and saute until light brown.\n3. Add ginger-garlic paste and cook for 30 seconds.\n4. Add chopped tomatoes, turmeric, and chili powder. Cook until tomatoes break down.\n5. Add cubed potatoes and green peas with half a cup of water.\n6. Cover and cook for 15 minutes until potatoes are tender.\n7. Add garam masala and salt. Stir and cook for 2 more minutes.\n8. Garnish with cilantro and serve with puri or chapati.",
        "ingredients": [
            ("Potato", 3.0, "pieces"),
            ("Green peas", 1.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Garam masala", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Chicken Curry",
        "description": "Classic Indian chicken curry with a rich onion-tomato base and warm spices. A weeknight staple.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget"],
        "instructions": "1. Marinate chicken thighs with turmeric, chili powder, and salt for 15 minutes.\n2. Heat oil and add whole spices: bay leaf, cardamom, and cloves.\n3. Add sliced onions and cook until deep golden brown.\n4. Add ginger-garlic paste and saute for a minute.\n5. Add chopped tomatoes and cook until they turn to a paste.\n6. Add coriander powder and the marinated chicken. Sear for 5 minutes.\n7. Add one cup of water, cover, and simmer for 25 minutes until chicken is cooked through.\n8. Finish with garam masala and fresh cilantro. Serve with rice or naan.",
        "ingredients": [
            ("Chicken thighs", 500.0, "g"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 3.0, "pieces"),
            ("Ginger-garlic paste", 1.5, "tbsp"),
            ("Bay leaf", 1.0, "pieces"),
            ("Green cardamom", 3.0, "pieces"),
            ("Coriander powder", 1.0, "tsp"),
            ("Garam masala", 1.0, "tsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Oil", 3.0, "tbsp"),
        ],
    },
    {
        "title": "Baingan Bharta",
        "description": "Smoky roasted eggplant mashed and cooked with onions, tomatoes, and spices. A rustic Punjabi favorite.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Roast the whole eggplant directly over a flame, turning frequently, until the skin is charred and flesh is soft.\n2. Let it cool, then peel off the skin and mash the flesh.\n3. Heat oil in a pan and add cumin seeds.\n4. Add chopped onions and saute until golden.\n5. Add green chilies, ginger, and chopped tomatoes. Cook until tomatoes are soft.\n6. Add the mashed eggplant, turmeric, coriander powder, and salt.\n7. Cook on medium heat for 10 minutes, stirring occasionally.\n8. Garnish with cilantro and serve with roti.",
        "ingredients": [
            ("Eggplant", 2.0, "pieces"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Ginger", 1.0, "tbsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Jeera Rice",
        "description": "Fragrant basmati rice tempered with cumin seeds and ghee. The perfect accompaniment to any dal or curry.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick"],
        "instructions": "1. Wash and soak basmati rice for 20 minutes, then drain.\n2. Heat ghee in a heavy-bottomed pot.\n3. Add cumin seeds, bay leaf, and whole black pepper. Let them splutter.\n4. Add the drained rice and saute gently for 2 minutes.\n5. Add 2 cups of water and salt. Bring to a boil.\n6. Reduce heat to the lowest setting, cover tightly, and cook for 15 minutes.\n7. Turn off heat and let it rest covered for 5 minutes. Fluff with a fork before serving.",
        "ingredients": [
            ("Basmati rice", 1.5, "cups"),
            ("Cumin seeds", 1.5, "tsp"),
            ("Ghee", 2.0, "tbsp"),
            ("Bay leaf", 1.0, "pieces"),
            ("Black pepper", 5.0, "pieces"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Masoor Dal",
        "description": "Simple red lentil dal cooked to a creamy consistency with a garlic tempering. Ready in under 30 minutes.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-protein", "budget", "quick"],
        "instructions": "1. Wash masoor dal thoroughly and drain.\n2. Add dal to a pot with 3 cups water, turmeric, and salt. Bring to a boil.\n3. Reduce heat and simmer for 20 minutes, skimming off any foam.\n4. Heat oil in a small pan and add mustard seeds and cumin seeds.\n5. Add sliced garlic, dried red chilies, and curry leaves. Fry until garlic is golden.\n6. Pour the tempering into the cooked dal and stir.\n7. Serve hot with steamed rice.",
        "ingredients": [
            ("Masoor dal", 1.0, "cups"),
            ("Garlic cloves", 5.0, "pieces"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Cumin seeds", 0.5, "tsp"),
            ("Dried red chilies", 2.0, "pieces"),
            ("Curry leaves", 8.0, "pieces"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Chole Bhature",
        "description": "Spiced chickpea curry served with deep-fried puffed bread. A beloved North Indian street food classic.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 45,
        "servings": 4,
        "tags": ["vegetarian", "high-protein", "budget"],
        "instructions": "1. Soak chickpeas overnight and pressure cook until soft.\n2. Make the bhatura dough: mix flour, yogurt, oil, baking soda, and salt. Knead into a soft dough and rest for 2 hours.\n3. Heat oil and saute onions until brown. Add ginger-garlic paste.\n4. Add tomato puree, chole masala, coriander powder, and chili powder. Cook until oil separates.\n5. Add cooked chickpeas with some cooking liquid. Simmer for 15 minutes.\n6. Roll out bhatura dough into ovals and deep fry until puffed and golden.\n7. Serve the chole hot with bhatura and pickled onions.",
        "ingredients": [
            ("Chickpeas", 2.0, "cups"),
            ("All-purpose flour", 2.0, "cups"),
            ("Yogurt", 3.0, "tbsp"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 3.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Chole masala", 2.0, "tbsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Baking soda", 0.25, "tsp"),
            ("Oil", 3.0, "cups"),
        ],
    },
    {
        "title": "Vegetable Pulao",
        "description": "Lightly spiced rice cooked with mixed vegetables and whole spices. A quick one-pot meal.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "one-pot", "budget", "quick"],
        "instructions": "1. Wash and soak basmati rice for 20 minutes.\n2. Heat ghee in a pot and add bay leaf, cinnamon, cardamom, and cloves.\n3. Add sliced onion and saute until light golden.\n4. Add diced carrots, peas, beans, and potatoes. Saute for 3 minutes.\n5. Add drained rice and stir gently for 2 minutes.\n6. Add 2.5 cups water and salt. Bring to a boil.\n7. Cover tightly, reduce heat to lowest, and cook for 15 minutes.\n8. Let it rest for 5 minutes, then fluff and serve with raita.",
        "ingredients": [
            ("Basmati rice", 1.5, "cups"),
            ("Mixed vegetables", 1.5, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Bay leaf", 1.0, "pieces"),
            ("Cinnamon stick", 1.0, "pieces"),
            ("Green cardamom", 3.0, "pieces"),
            ("Cloves", 3.0, "pieces"),
            ("Ghee", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Kadhi Pakora",
        "description": "Tangy yogurt-based curry with crispy gram flour fritters. A North Indian homestyle dish.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Mix gram flour, sliced onion, green chili, and salt. Add water to make a thick batter.\n2. Deep fry spoonfuls of batter until golden to make pakoras. Set aside.\n3. Whisk yogurt with gram flour, turmeric, and chili powder until smooth.\n4. Add 3 cups water to the yogurt mixture and bring to a boil, stirring constantly.\n5. Reduce heat and simmer for 20 minutes until the kadhi thickens.\n6. Add the fried pakoras to the kadhi and simmer for 5 more minutes.\n7. Heat ghee, add mustard seeds, cumin seeds, dried red chilies, and curry leaves. Pour over kadhi.\n8. Serve hot with steamed rice.",
        "ingredients": [
            ("Yogurt", 2.0, "cups"),
            ("Gram flour", 0.75, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Cumin seeds", 0.5, "tsp"),
            ("Ghee", 1.0, "tbsp"),
            ("Oil", 1.0, "cups"),
        ],
    },
    {
        "title": "Aloo Paratha",
        "description": "Whole wheat flatbread stuffed with spiced mashed potato filling. A hearty Indian breakfast.",
        "difficulty": "medium",
        "prep_time": 25,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Knead whole wheat flour with water and salt into a soft dough. Rest for 15 minutes.\n2. Boil, peel, and mash potatoes. Add green chili, cumin, coriander, and salt.\n3. Divide the dough and filling into equal portions.\n4. Roll a dough ball into a small circle, place filling in the center, and seal the edges.\n5. Gently roll out the stuffed ball into a flat paratha.\n6. Cook on a hot tawa with ghee on both sides until golden brown spots appear.\n7. Serve hot with yogurt and pickle.",
        "ingredients": [
            ("Whole wheat flour", 2.0, "cups"),
            ("Potato", 4.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Cumin powder", 1.0, "tsp"),
            ("Coriander leaves", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
            ("Ghee", 4.0, "tbsp"),
        ],
    },
    {
        "title": "Chicken Keema",
        "description": "Spiced minced chicken cooked with onions, tomatoes, and peas. Quick-cooking and deeply flavored.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget", "quick"],
        "instructions": "1. Heat oil and add cumin seeds, bay leaf, and cinnamon stick.\n2. Add finely chopped onions and cook until brown.\n3. Add ginger-garlic paste and saute for a minute.\n4. Add minced chicken and cook on high heat, breaking up lumps, for 5 minutes.\n5. Add chopped tomatoes, turmeric, chili powder, and coriander powder.\n6. Cook until tomatoes break down and oil separates.\n7. Add green peas and salt. Cover and cook for 10 minutes.\n8. Finish with garam masala and cilantro. Serve with roti or rice.",
        "ingredients": [
            ("Chicken mince", 500.0, "g"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Green peas", 0.5, "cups"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Garam masala", 1.0, "tsp"),
            ("Oil", 3.0, "tbsp"),
        ],
    },
    {
        "title": "Rasam",
        "description": "South Indian pepper-tamarind soup with a warming spice base. Light, tangy, and perfect for cold days.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Soak tamarind in warm water for 10 minutes and extract the juice.\n2. Cook toor dal until soft and mash it.\n3. Crush black pepper, cumin, and garlic together into a coarse paste.\n4. Add tamarind juice, crushed spice paste, turmeric, and chopped tomato to a pot.\n5. Add 2 cups of water and bring to a boil. Simmer for 10 minutes.\n6. Add the mashed dal and salt. Simmer for 5 more minutes.\n7. Heat ghee, add mustard seeds, curry leaves, and dried red chilies. Pour into rasam.\n8. Garnish with cilantro and serve hot with rice.",
        "ingredients": [
            ("Toor dal", 0.25, "cups"),
            ("Tamarind paste", 1.0, "tbsp"),
            ("Tomato", 2.0, "pieces"),
            ("Black pepper", 1.0, "tsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Curry leaves", 8.0, "pieces"),
            ("Ghee", 1.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Bhindi Masala",
        "description": "Stir-fried okra with onions and spices. A dry sabzi that pairs beautifully with dal and roti.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Wash okra, pat completely dry, and cut into half-inch pieces.\n2. Heat oil in a wide pan on high heat.\n3. Add the okra and spread in a single layer. Cook without stirring for 5 minutes.\n4. Stir and cook until the okra stops being slimy, about 10 minutes total.\n5. Push okra to one side, add cumin seeds and sliced onion. Saute until onion softens.\n6. Add turmeric, coriander powder, chili powder, and amchur. Mix everything together.\n7. Add salt and cook for 2 more minutes.\n8. Serve hot with dal and chapati.",
        "ingredients": [
            ("Okra", 500.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Amchur powder", 1.0, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Poha",
        "description": "Flattened rice tossed with mustard seeds, peanuts, and turmeric. A popular quick Indian breakfast.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Rinse poha in water, drain immediately, and set aside to soften.\n2. Heat oil in a pan and add mustard seeds. Let them splutter.\n3. Add peanuts and fry until light golden.\n4. Add curry leaves, green chilies, and diced onion. Saute until onion softens.\n5. Add turmeric powder and salt. Stir well.\n6. Add the softened poha and toss gently to combine with the spice mixture.\n7. Squeeze lemon juice on top and garnish with cilantro. Serve immediately.",
        "ingredients": [
            ("Flattened rice", 2.0, "cups"),
            ("Peanuts", 2.0, "tbsp"),
            ("Onion", 1.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Curry leaves", 6.0, "pieces"),
            ("Turmeric powder", 0.25, "tsp"),
            ("Lemon", 1.0, "pieces"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Moong Dal Khichdi",
        "description": "Comforting one-pot rice and lentil porridge with gentle spices. The ultimate Indian comfort food.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "one-pot", "budget", "quick"],
        "instructions": "1. Wash rice and moong dal together until water runs clear.\n2. Heat ghee in a pressure cooker and add cumin seeds, bay leaf, and whole pepper.\n3. Add the rice-dal mixture and saute for 2 minutes.\n4. Add turmeric, salt, and 4 cups of water.\n5. Pressure cook for 3 whistles on medium heat.\n6. Let the pressure release naturally. Open and stir gently.\n7. Serve hot with ghee, pickle, and papad.",
        "ingredients": [
            ("Basmati rice", 1.0, "cups"),
            ("Moong dal", 0.5, "cups"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Bay leaf", 1.0, "pieces"),
            ("Black pepper", 4.0, "pieces"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Ghee", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Tandoori Chicken",
        "description": "Yogurt-marinated chicken roasted to charred perfection with smoky tandoori spices. A crowd-pleasing classic.",
        "difficulty": "medium",
        "prep_time": 30,
        "cook_time": 35,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget", "spicy"],
        "instructions": "1. Make deep slashes in chicken leg pieces for the marinade to penetrate.\n2. Mix yogurt with ginger-garlic paste, chili powder, turmeric, coriander powder, garam masala, lemon juice, and salt.\n3. Coat the chicken thoroughly and marinate for at least 2 hours or overnight.\n4. Preheat oven to 220 degrees Celsius.\n5. Place chicken on a wire rack over a baking tray.\n6. Roast for 30-35 minutes, turning once, until charred and cooked through.\n7. Squeeze lemon juice over the chicken and serve with onion rings and mint chutney.",
        "ingredients": [
            ("Chicken legs", 800.0, "g"),
            ("Yogurt", 0.75, "cups"),
            ("Ginger-garlic paste", 2.0, "tbsp"),
            ("Red chili powder", 2.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Garam masala", 1.0, "tsp"),
            ("Lemon", 1.0, "pieces"),
            ("Salt", 1.0, "tsp"),
            ("Oil", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Lauki Chana Dal",
        "description": "Bottle gourd cooked with chana dal in a light, homestyle preparation. Gentle on the stomach and nutritious.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Soak chana dal for 30 minutes and drain.\n2. Peel and dice the bottle gourd into small cubes.\n3. Pressure cook dal and bottle gourd with turmeric and salt for 3 whistles.\n4. Heat oil in a pan and add cumin seeds and asafoetida.\n5. Add chopped tomato and cook until soft.\n6. Add the cooked dal-gourd mixture, chili powder, and coriander powder.\n7. Simmer for 10 minutes, adjusting consistency with water.\n8. Garnish with cilantro and serve with chapati.",
        "ingredients": [
            ("Chana dal", 0.5, "cups"),
            ("Bottle gourd", 2.0, "cups"),
            ("Tomato", 1.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Asafoetida", 0.25, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Upma",
        "description": "Savory semolina porridge tempered with mustard seeds, cashews, and vegetables. A South Indian breakfast staple.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 3,
        "tags": ["vegetarian", "budget", "quick"],
        "instructions": "1. Dry roast semolina in a pan until lightly golden and fragrant. Set aside.\n2. Heat oil and add mustard seeds, urad dal, and cashews. Fry until dal is golden.\n3. Add curry leaves, green chili, and chopped onion. Saute until onion is translucent.\n4. Add diced carrots and peas. Cook for 2 minutes.\n5. Add 2.5 cups of water and salt. Bring to a boil.\n6. Slowly pour in the roasted semolina while stirring continuously to prevent lumps.\n7. Cook on low heat for 3 minutes until the mixture thickens. Serve with chutney.",
        "ingredients": [
            ("Semolina", 1.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Green peas", 0.25, "cups"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Urad dal", 1.0, "tsp"),
            ("Cashews", 8.0, "pieces"),
            ("Curry leaves", 6.0, "pieces"),
            ("Oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Chicken Biryani",
        "description": "Layered rice and chicken dish cooked dum-style with aromatic spices and saffron. The king of Indian rice dishes.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 60,
        "servings": 6,
        "tags": ["high-protein", "budget", "spicy"],
        "instructions": "1. Marinate chicken with yogurt, ginger-garlic paste, chili powder, turmeric, and salt for 1 hour.\n2. Soak basmati rice for 30 minutes, then parboil with whole spices until 70 percent cooked. Drain.\n3. Heat ghee and fry sliced onions until deep golden. Remove half for garnish.\n4. Add marinated chicken to the remaining onions and cook for 10 minutes.\n5. Layer the parboiled rice over the chicken. Top with fried onions, saffron milk, and cilantro.\n6. Seal the pot with foil and a tight lid. Cook on the lowest heat for 25 minutes.\n7. Let it rest for 5 minutes, then gently mix the layers.\n8. Serve with raita and a squeeze of lemon.",
        "ingredients": [
            ("Chicken thighs", 600.0, "g"),
            ("Basmati rice", 2.0, "cups"),
            ("Yogurt", 0.5, "cups"),
            ("Onion", 3.0, "pieces"),
            ("Ginger-garlic paste", 2.0, "tbsp"),
            ("Saffron", 1.0, "pinch"),
            ("Garam masala", 1.0, "tsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Ghee", 4.0, "tbsp"),
            ("Fresh cilantro", 0.25, "cups"),
        ],
    },
    {
        "title": "Masala Dosa",
        "description": "Crispy fermented rice crepe filled with spiced potato. South India's most famous breakfast creation.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 40,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget"],
        "instructions": "1. Soak rice and urad dal separately for 6 hours. Grind to a smooth batter and ferment overnight.\n2. Boil potatoes until soft, peel and crumble them.\n3. Heat oil, add mustard seeds, curry leaves, and green chilies.\n4. Add sliced onion and saute until soft. Add turmeric and mashed potato. Mix well.\n5. Heat a flat tawa, pour a ladleful of batter, and spread in a thin circle.\n6. Drizzle oil around the edges. Cook until the bottom is golden and crispy.\n7. Place a portion of potato filling on one half, fold the dosa over.\n8. Serve immediately with coconut chutney and sambar.",
        "ingredients": [
            ("Rice", 2.0, "cups"),
            ("Urad dal", 0.5, "cups"),
            ("Potato", 4.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Green chili", 3.0, "pieces"),
            ("Mustard seeds", 1.0, "tsp"),
            ("Curry leaves", 8.0, "pieces"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Oil", 4.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Kadai Paneer",
        "description": "Paneer cubes in a thick bell pepper and tomato gravy with freshly ground spices. A restaurant-style favorite.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "spicy"],
        "instructions": "1. Dry roast coriander seeds and dried red chilies. Grind coarsely to make kadai masala.\n2. Cut paneer into cubes and bell pepper into strips.\n3. Heat oil and saute ginger-garlic paste for a minute.\n4. Add chopped tomatoes and cook until they form a thick paste.\n5. Add the kadai masala, turmeric, and salt. Cook for 2 minutes.\n6. Add bell pepper strips and cook for 3 minutes until slightly tender.\n7. Add paneer cubes and toss gently. Cook for 2 more minutes.\n8. Garnish with cilantro and serve with naan or roti.",
        "ingredients": [
            ("Paneer", 250.0, "g"),
            ("Bell pepper", 2.0, "pieces"),
            ("Tomato", 3.0, "pieces"),
            ("Coriander seeds", 1.0, "tbsp"),
            ("Dried red chilies", 4.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Turmeric powder", 0.25, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Fresh cilantro", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Dal Makhani",
        "description": "Creamy black lentils slow-cooked overnight with butter and spices. Rich, indulgent, and deeply satisfying.",
        "difficulty": "hard",
        "prep_time": 15,
        "cook_time": 90,
        "servings": 6,
        "tags": ["vegetarian", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Soak whole black urad dal and rajma overnight. Drain.\n2. Pressure cook with 4 cups water, turmeric, and salt for 5-6 whistles until very soft.\n3. Heat butter in a heavy pot. Add ginger-garlic paste and saute.\n4. Add chopped tomatoes, chili powder, and coriander powder. Cook until oil separates.\n5. Add the cooked dal and an extra cup of water. Bring to a simmer.\n6. Cook on the lowest heat for 1 hour, stirring occasionally, until thick and creamy.\n7. Finish with a generous knob of butter and garam masala.\n8. Serve with naan, roti, or steamed rice.",
        "ingredients": [
            ("Whole black urad dal", 1.0, "cups"),
            ("Kidney beans", 0.25, "cups"),
            ("Butter", 4.0, "tbsp"),
            ("Tomato", 3.0, "pieces"),
            ("Ginger-garlic paste", 1.5, "tbsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Garam masala", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Anda Bhurji",
        "description": "Indian spiced scrambled eggs with onions, tomatoes, and green chilies. A quick and satisfying meal.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["gluten-free", "high-protein", "budget", "quick"],
        "instructions": "1. Beat eggs lightly in a bowl with salt and turmeric.\n2. Heat oil in a pan and add cumin seeds.\n3. Add finely chopped onion and green chilies. Saute until onion softens.\n4. Add chopped tomatoes and cook for 2 minutes.\n5. Pour in the beaten eggs and stir continuously with a spatula.\n6. Cook until the eggs are just set but still moist.\n7. Garnish with cilantro and serve with toast or pav.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Cumin seeds", 0.5, "tsp"),
            ("Turmeric powder", 0.25, "tsp"),
            ("Oil", 1.0, "tbsp"),
            ("Fresh cilantro", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Pav Bhaji",
        "description": "Mashed mixed vegetable curry served with buttered toasted buns. Mumbai's iconic street food.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "budget", "spicy"],
        "instructions": "1. Boil potatoes, cauliflower, peas, and carrots until soft. Mash coarsely together.\n2. Heat butter in a large pan and saute finely chopped onions until golden.\n3. Add ginger-garlic paste and chopped capsicum. Cook for 2 minutes.\n4. Add chopped tomatoes and cook until they break down completely.\n5. Add pav bhaji masala, chili powder, and turmeric. Stir well.\n6. Add the mashed vegetables and half a cup of water. Mix and cook for 10 minutes, mashing further.\n7. Slice pav buns, butter them generously, and toast on a tawa until crispy.\n8. Serve the bhaji topped with butter, onion, and lemon wedge alongside the toasted pav.",
        "ingredients": [
            ("Potato", 3.0, "pieces"),
            ("Cauliflower", 1.0, "cups"),
            ("Green peas", 0.5, "cups"),
            ("Carrot", 1.0, "pieces"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 3.0, "pieces"),
            ("Pav bhaji masala", 2.0, "tbsp"),
            ("Butter", 4.0, "tbsp"),
            ("Pav buns", 8.0, "pieces"),
            ("Lemon", 1.0, "pieces"),
        ],
    },
    {
        "title": "Saag Aloo",
        "description": "Spinach and potato curry with garlic and cumin. A simple, nutritious, and earthy dish.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Blanch spinach in boiling water for 2 minutes, then puree coarsely.\n2. Par-boil potatoes until just fork-tender, then cut into cubes.\n3. Heat oil in a pan, add cumin seeds and let them splutter.\n4. Add chopped garlic and saute until golden.\n5. Add potato cubes and fry until lightly browned on the edges.\n6. Add the spinach puree, turmeric, chili powder, and salt.\n7. Cook together for 10 minutes on medium heat, stirring occasionally.\n8. Serve with chapati or rice.",
        "ingredients": [
            ("Spinach", 4.0, "cups"),
            ("Potato", 3.0, "pieces"),
            ("Garlic cloves", 5.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Tarka Dal (Urad)",
        "description": "Whole black urad dal slow-cooked and tempered with ghee, cumin, and garlic. Rich and hearty.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 45,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Soak whole urad dal for 4 hours and drain.\n2. Pressure cook with turmeric and 3 cups water for 5 whistles.\n3. Mash slightly and simmer on low heat for 15 minutes.\n4. Heat ghee in a small pan and add cumin seeds and asafoetida.\n5. Add sliced garlic and dried red chilies. Fry until garlic is golden.\n6. Add chopped tomato and cook until soft.\n7. Pour the tempering into the dal. Add salt and stir well.\n8. Garnish with cilantro and serve with rice or roti.",
        "ingredients": [
            ("Whole urad dal", 1.0, "cups"),
            ("Garlic cloves", 5.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Dried red chilies", 2.0, "pieces"),
            ("Asafoetida", 0.25, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Ghee", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Idli",
        "description": "Steamed fermented rice and lentil cakes. Soft, fluffy, and the quintessential South Indian breakfast.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget"],
        "instructions": "1. Soak rice and urad dal separately for 6 hours.\n2. Grind urad dal first to a light, fluffy batter. Then grind rice to a slightly coarse paste.\n3. Mix both batters with salt and let ferment overnight in a warm place.\n4. The next morning, gently stir the risen batter without deflating it.\n5. Grease idli molds with oil and pour batter into each mold.\n6. Steam in an idli steamer for 12-15 minutes until a toothpick comes out clean.\n7. Let cool briefly, then unmold and serve hot with sambar and coconut chutney.",
        "ingredients": [
            ("Idli rice", 2.0, "cups"),
            ("Urad dal", 0.5, "cups"),
            ("Fenugreek seeds", 0.5, "tsp"),
            ("Salt", 1.0, "tsp"),
            ("Oil", 1.0, "tsp"),
        ],
    },
    {
        "title": "Methi Thepla",
        "description": "Gujarati flatbread made with fenugreek leaves and spices. Perfect for travel and packed lunches.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Mix whole wheat flour with chopped fenugreek leaves, turmeric, chili powder, cumin, and salt.\n2. Add yogurt and enough water to form a soft dough.\n3. Knead well for 5 minutes and let the dough rest for 10 minutes.\n4. Divide into 12 equal balls and roll each into a thin circle.\n5. Heat a tawa and cook each thepla on both sides, brushing with oil until golden spots appear.\n6. Serve with pickle, yogurt, or tea.",
        "ingredients": [
            ("Whole wheat flour", 2.0, "cups"),
            ("Fenugreek leaves", 1.0, "cups"),
            ("Yogurt", 2.0, "tbsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Salt", 0.75, "tsp"),
        ],
    },
    {
        "title": "Chicken Tikka Masala",
        "description": "Grilled chicken tikka pieces in a creamy, spiced tomato sauce. Rich, aromatic, and universally loved.",
        "difficulty": "medium",
        "prep_time": 30,
        "cook_time": 30,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget", "spicy"],
        "instructions": "1. Marinate chicken thigh pieces with yogurt, ginger-garlic paste, chili powder, turmeric, and salt for 1 hour.\n2. Thread onto skewers and grill or bake at 220C until charred, about 15 minutes.\n3. Heat butter in a pan and saute chopped onions until golden.\n4. Add ginger-garlic paste, chopped tomatoes, and cook until tomatoes break down.\n5. Add coriander powder, garam masala, and chili powder. Cook for 2 minutes.\n6. Blend the sauce until smooth and return to pan.\n7. Add the grilled chicken pieces to the sauce. Simmer for 10 minutes.\n8. Garnish with cilantro and serve with naan or rice.",
        "ingredients": [
            ("Chicken thighs", 500.0, "g"),
            ("Yogurt", 0.5, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 4.0, "pieces"),
            ("Ginger-garlic paste", 2.0, "tbsp"),
            ("Garam masala", 1.0, "tsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Butter", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Aloo Tikki",
        "description": "Crispy pan-fried potato patties flavored with green peas and spices. A popular chaat and snack.",
        "difficulty": "easy",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget"],
        "instructions": "1. Boil potatoes until soft, peel, and mash thoroughly.\n2. Boil green peas and mash lightly.\n3. Mix potatoes, peas, chopped green chili, ginger, cumin powder, coriander, and salt.\n4. Shape into 8 round, flat patties.\n5. Heat oil in a flat pan.\n6. Place patties on the pan and cook on medium heat until golden and crispy on the bottom.\n7. Flip carefully and cook the other side until equally crispy.\n8. Serve hot with green chutney and tamarind chutney.",
        "ingredients": [
            ("Potato", 4.0, "pieces"),
            ("Green peas", 0.5, "cups"),
            ("Green chili", 2.0, "pieces"),
            ("Ginger", 1.0, "tsp"),
            ("Cumin powder", 1.0, "tsp"),
            ("Coriander leaves", 2.0, "tbsp"),
            ("Salt", 0.75, "tsp"),
            ("Oil", 4.0, "tbsp"),
        ],
    },
    {
        "title": "Lemon Rice",
        "description": "Tangy turmeric-tinted rice with a crunchy tempering of peanuts and mustard seeds. A South Indian lunch staple.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Cook rice and spread on a plate to cool and separate the grains.\n2. Heat oil in a pan and add mustard seeds and urad dal.\n3. When they splutter, add peanuts and fry until golden.\n4. Add curry leaves, green chilies, and a pinch of asafoetida.\n5. Add turmeric powder and the cooked rice. Toss gently.\n6. Squeeze fresh lemon juice over the rice, add salt, and mix well.\n7. Serve at room temperature.",
        "ingredients": [
            ("Basmati rice", 2.0, "cups"),
            ("Lemon", 2.0, "pieces"),
            ("Peanuts", 2.0, "tbsp"),
            ("Mustard seeds", 1.0, "tsp"),
            ("Urad dal", 1.0, "tsp"),
            ("Curry leaves", 8.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Curd Rice",
        "description": "Yogurt-mixed rice tempered with mustard seeds and curry leaves. A cooling, soothing South Indian staple.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick"],
        "instructions": "1. Cook rice until very soft and let it cool slightly.\n2. Mash the rice gently with a spoon.\n3. Add yogurt and milk. Mix well until creamy.\n4. Heat oil and add mustard seeds, urad dal, curry leaves, and green chili.\n5. Pour the tempering over the curd rice and mix.\n6. Add salt and grated ginger. Stir to combine.\n7. Serve at room temperature or chilled with pickle.",
        "ingredients": [
            ("Rice", 1.0, "cups"),
            ("Yogurt", 1.5, "cups"),
            ("Milk", 0.25, "cups"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Urad dal", 0.5, "tsp"),
            ("Curry leaves", 6.0, "pieces"),
            ("Green chili", 1.0, "pieces"),
            ("Ginger", 0.5, "tsp"),
            ("Oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Chana Dal Fry",
        "description": "Split Bengal gram cooked until creamy and finished with a smoky tempering. Earthy and comforting.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Soak chana dal for 1 hour and drain.\n2. Pressure cook with turmeric and 2.5 cups water for 4 whistles.\n3. Mash lightly, keeping some texture.\n4. Heat oil in a pan and add cumin seeds and a pinch of asafoetida.\n5. Add chopped onion and cook until golden. Add ginger and green chili.\n6. Add chopped tomato, coriander powder, and chili powder. Cook until soft.\n7. Add the cooked dal, salt, and simmer for 10 minutes.\n8. Garnish with cilantro and serve with rice or roti.",
        "ingredients": [
            ("Chana dal", 1.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Ginger", 1.0, "tsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Aloo Bhujia",
        "description": "Simple dry-fried potatoes with turmeric and cumin. A quick everyday side dish found in every Indian home.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 3,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Peel and cut potatoes into thin matchstick-like strips.\n2. Heat oil in a wide pan and add cumin seeds and mustard seeds.\n3. Add the potato strips and spread in a single layer.\n4. Add turmeric, chili powder, and salt. Toss to coat.\n5. Cook on medium heat without stirring too much, allowing the potatoes to crisp.\n6. Stir occasionally and cook for 12-15 minutes until golden and crispy.\n7. Garnish with cilantro and serve as a side with dal and roti.",
        "ingredients": [
            ("Potato", 4.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Matar Paneer",
        "description": "Paneer and green peas in a mildly spiced tomato gravy. A North Indian restaurant classic.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Cut paneer into cubes and lightly fry until golden. Set aside.\n2. Heat oil and add cumin seeds. Add finely chopped onions and saute until golden.\n3. Add ginger-garlic paste and cook for a minute.\n4. Add pureed tomatoes, turmeric, chili powder, and coriander powder. Cook until oil separates.\n5. Add green peas and half a cup of water. Simmer for 5 minutes.\n6. Add the fried paneer cubes and garam masala. Simmer for 5 more minutes.\n7. Garnish with cilantro and serve with naan or roti.",
        "ingredients": [
            ("Paneer", 250.0, "g"),
            ("Green peas", 1.0, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 3.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Garam masala", 0.5, "tsp"),
            ("Oil", 3.0, "tbsp"),
        ],
    },
    {
        "title": "Egg Biryani",
        "description": "Fragrant layered rice with spiced hard-boiled eggs. A quicker, budget-friendly take on biryani.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 40,
        "servings": 4,
        "tags": ["high-protein", "budget"],
        "instructions": "1. Hard boil eggs, peel, and make shallow slits. Fry in oil until golden. Set aside.\n2. Soak basmati rice for 20 minutes, then parboil with whole spices until 70 percent done.\n3. Heat ghee and fry sliced onions until deep golden. Remove half for garnish.\n4. Add ginger-garlic paste, chopped tomato, and biryani masala. Cook until tomatoes soften.\n5. Place fried eggs in the gravy. Layer parboiled rice on top.\n6. Top with fried onions, cilantro, and mint. Sprinkle a little saffron milk.\n7. Seal with foil and lid. Cook on the lowest heat for 20 minutes.\n8. Gently open and serve with raita.",
        "ingredients": [
            ("Eggs", 6.0, "pieces"),
            ("Basmati rice", 1.5, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Biryani masala", 1.0, "tbsp"),
            ("Saffron", 1.0, "pinch"),
            ("Ghee", 3.0, "tbsp"),
            ("Fresh mint", 2.0, "tbsp"),
            ("Oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Coconut Chutney",
        "description": "Fresh ground coconut chutney with green chilies and tempered mustard seeds. Essential with dosa and idli.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 5,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Grind grated coconut, roasted chana dal, green chilies, ginger, and salt with a little water to a smooth paste.\n2. Adjust consistency with water as needed.\n3. Heat oil in a small pan and add mustard seeds.\n4. When they splutter, add urad dal and curry leaves.\n5. Fry until the dal turns golden.\n6. Pour the tempering over the chutney and mix well.\n7. Serve alongside dosa, idli, or vada.",
        "ingredients": [
            ("Grated coconut", 1.0, "cups"),
            ("Roasted chana dal", 1.0, "tbsp"),
            ("Green chili", 2.0, "pieces"),
            ("Ginger", 0.5, "tsp"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Urad dal", 0.5, "tsp"),
            ("Curry leaves", 5.0, "pieces"),
            ("Oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Cabbage Poriyal",
        "description": "South Indian stir-fried cabbage with mustard seeds, urad dal, and coconut. A dry, crunchy side dish.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Finely shred the cabbage and set aside.\n2. Heat oil in a pan, add mustard seeds and urad dal.\n3. When they splutter, add curry leaves and dried red chili.\n4. Add the shredded cabbage and turmeric. Stir well.\n5. Add salt, cover, and cook on medium heat for 8-10 minutes, stirring occasionally.\n6. Remove lid, add grated coconut, and toss well.\n7. Cook uncovered for 2 more minutes. Serve as a side dish.",
        "ingredients": [
            ("Cabbage", 4.0, "cups"),
            ("Grated coconut", 3.0, "tbsp"),
            ("Mustard seeds", 1.0, "tsp"),
            ("Urad dal", 1.0, "tsp"),
            ("Curry leaves", 6.0, "pieces"),
            ("Dried red chili", 1.0, "pieces"),
            ("Turmeric powder", 0.25, "tsp"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tomato Rasam",
        "description": "Spicy tomato-based South Indian soup with pepper and garlic. Light, warming, and great for digestion.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Chop tomatoes finely and add to a pot with 2 cups water.\n2. Add crushed garlic, black pepper, cumin, turmeric, and salt.\n3. Bring to a boil and simmer for 10 minutes.\n4. Mash the tomatoes with the back of a ladle.\n5. Heat ghee, add mustard seeds, curry leaves, and dried red chili.\n6. Pour the tempering into the rasam.\n7. Garnish with cilantro and serve hot over steamed rice.",
        "ingredients": [
            ("Tomato", 4.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Black pepper", 1.0, "tsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Curry leaves", 6.0, "pieces"),
            ("Turmeric powder", 0.25, "tsp"),
            ("Ghee", 1.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Aloo Capsicum",
        "description": "Potatoes and bell peppers stir-fried with cumin and coriander. A colorful, quick dry sabzi.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 3,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Dice potatoes into small cubes and chop bell peppers into similar-sized pieces.\n2. Heat oil and add cumin seeds and mustard seeds.\n3. Add diced potatoes and turmeric. Cover and cook on medium-low for 10 minutes.\n4. Add bell peppers, chili powder, coriander powder, and salt.\n5. Stir and cook uncovered for 8 more minutes until peppers are tender-crisp.\n6. Add amchur powder and fresh cilantro. Toss and serve.",
        "ingredients": [
            ("Potato", 3.0, "pieces"),
            ("Bell pepper", 2.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Amchur powder", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Chicken Do Pyaza",
        "description": "Chicken cooked with a generous amount of onions in two stages. Intensely flavored and aromatic.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget"],
        "instructions": "1. Slice 2 onions finely and quarter 2 more onions. Keep separate.\n2. Heat oil and fry the sliced onions until deep golden brown.\n3. Add ginger-garlic paste and chicken thigh pieces. Sear for 5 minutes.\n4. Add chopped tomatoes, turmeric, chili powder, and coriander powder. Cook until tomatoes soften.\n5. Add half a cup of water, cover, and cook for 20 minutes.\n6. Add the quartered onions and cook for 10 more minutes until they are soft but hold their shape.\n7. Finish with garam masala and fresh cilantro.\n8. Serve with naan or paratha.",
        "ingredients": [
            ("Chicken thighs", 500.0, "g"),
            ("Onion", 4.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Ginger-garlic paste", 1.5, "tbsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Coriander powder", 1.0, "tsp"),
            ("Garam masala", 1.0, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Mixed Dal",
        "description": "A blend of five lentils cooked together into a creamy, protein-packed dal. Everyday comfort food.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-protein", "budget", "one-pot"],
        "instructions": "1. Wash all five dals together and soak for 30 minutes.\n2. Pressure cook with turmeric and 4 cups water for 4 whistles.\n3. Mash well and simmer on low heat.\n4. Heat oil, add cumin seeds, and let them splutter.\n5. Add sliced onion, ginger, and green chili. Saute until onion is golden.\n6. Add chopped tomatoes and cook until soft.\n7. Pour the tempering into the dal. Add salt and simmer for 10 minutes.\n8. Garnish with cilantro and serve with rice.",
        "ingredients": [
            ("Toor dal", 0.25, "cups"),
            ("Masoor dal", 0.25, "cups"),
            ("Moong dal", 0.25, "cups"),
            ("Chana dal", 0.25, "cups"),
            ("Urad dal", 0.25, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Pakora",
        "description": "Crispy gram flour fritters loaded with onions and spices. The quintessential Indian rainy-day snack.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget", "quick"],
        "instructions": "1. Slice onions thinly and add chopped green chili, cilantro, and curry leaves.\n2. Add gram flour, rice flour, turmeric, chili powder, and salt.\n3. Mix well, adding water a tablespoon at a time to make a thick batter that coats the onions.\n4. Heat oil for deep frying until hot.\n5. Drop spoonfuls of the mixture into the hot oil.\n6. Fry in batches until golden brown and crispy, about 3-4 minutes per batch.\n7. Drain on paper towels and serve hot with green chutney.",
        "ingredients": [
            ("Onion", 3.0, "pieces"),
            ("Gram flour", 1.0, "cups"),
            ("Rice flour", 2.0, "tbsp"),
            ("Green chili", 2.0, "pieces"),
            ("Turmeric powder", 0.25, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Fresh cilantro", 2.0, "tbsp"),
            ("Oil", 2.0, "cups"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Paneer Bhurji",
        "description": "Crumbled paneer scrambled with onions, tomatoes, and spices. A vegetarian twist on egg bhurji.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 3,
        "tags": ["vegetarian", "gluten-free", "high-protein", "budget", "quick"],
        "instructions": "1. Crumble the paneer into small pieces.\n2. Heat oil and add cumin seeds.\n3. Add finely chopped onion and green chili. Saute until onion is translucent.\n4. Add chopped tomatoes and cook for 3 minutes.\n5. Add turmeric, chili powder, coriander powder, and salt.\n6. Add the crumbled paneer and mix well.\n7. Cook for 5 minutes, stirring occasionally, until flavors meld.\n8. Garnish with cilantro and serve with roti or as a filling for wraps.",
        "ingredients": [
            ("Paneer", 250.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Green chili", 2.0, "pieces"),
            ("Cumin seeds", 0.5, "tsp"),
            ("Turmeric powder", 0.25, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Coriander powder", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Vegetable Korma",
        "description": "Mixed vegetables in a creamy coconut and cashew gravy with aromatic whole spices. Mild and rich.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget"],
        "instructions": "1. Dice carrots, beans, potatoes, and cauliflower into bite-sized pieces.\n2. Grind cashews and coconut with a little water into a smooth paste.\n3. Heat oil and add bay leaf, cinnamon, cardamom, and cloves.\n4. Add sliced onions and cook until golden.\n5. Add ginger-garlic paste and the mixed vegetables. Saute for 5 minutes.\n6. Add the cashew-coconut paste, turmeric, chili powder, and one cup of water.\n7. Cover and simmer for 20 minutes until vegetables are tender.\n8. Add salt and garam masala. Serve with rice, roti, or appam.",
        "ingredients": [
            ("Mixed vegetables", 3.0, "cups"),
            ("Cashews", 10.0, "pieces"),
            ("Grated coconut", 3.0, "tbsp"),
            ("Onion", 2.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Bay leaf", 1.0, "pieces"),
            ("Cinnamon stick", 1.0, "pieces"),
            ("Garam masala", 0.5, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Oil", 3.0, "tbsp"),
        ],
    },
    {
        "title": "Egg Fried Rice",
        "description": "Indo-Chinese style fried rice with scrambled eggs and vegetables. A popular street food fusion dish.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 3,
        "tags": ["high-protein", "budget", "quick"],
        "instructions": "1. Cook rice ahead of time and spread to cool completely. Day-old rice works best.\n2. Heat oil in a wok on high heat. Scramble eggs and break into small pieces. Set aside.\n3. Add more oil, then add chopped garlic and green chili.\n4. Add diced carrots, beans, and spring onion whites. Stir-fry for 3 minutes.\n5. Add the cold rice and toss on high heat.\n6. Add soy sauce, black pepper, and salt. Toss vigorously.\n7. Add the scrambled eggs back and mix through.\n8. Garnish with spring onion greens and serve hot.",
        "ingredients": [
            ("Cooked rice", 3.0, "cups"),
            ("Eggs", 3.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Spring onion", 3.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Green chili", 1.0, "pieces"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Black pepper", 0.5, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Kootu",
        "description": "South Indian lentil and vegetable stew thickened with ground coconut. Wholesome and subtly spiced.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Cook chana dal until soft but not mushy. Set aside.\n2. Cook chopped vegetables like raw banana, yam, or snake gourd until tender.\n3. Grind coconut with cumin and black pepper into a coarse paste.\n4. Combine cooked dal, vegetables, and turmeric in a pot. Add one cup water.\n5. Bring to a simmer and add the ground coconut paste.\n6. Cook for 10 minutes until the flavors meld and the stew thickens.\n7. Heat coconut oil, add mustard seeds, curry leaves, and dried red chili. Pour over the kootu.\n8. Serve with steamed rice.",
        "ingredients": [
            ("Chana dal", 0.5, "cups"),
            ("Raw banana", 2.0, "pieces"),
            ("Grated coconut", 0.5, "cups"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Black pepper", 0.5, "tsp"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Curry leaves", 6.0, "pieces"),
            ("Turmeric powder", 0.25, "tsp"),
            ("Coconut oil", 1.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Murgh Shorba",
        "description": "Spiced Indian chicken soup with warming ginger and pepper. Light yet deeply flavorful.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget", "one-pot"],
        "instructions": "1. Heat ghee in a pot and add whole spices: bay leaf, cinnamon, cardamom, and cloves.\n2. Add sliced onion and saute until softened.\n3. Add ginger-garlic paste and chicken thigh pieces. Sear for 5 minutes.\n4. Add turmeric, black pepper, and cumin powder.\n5. Pour in 4 cups of water and bring to a boil.\n6. Reduce heat and simmer for 20 minutes until chicken is cooked through.\n7. Add salt and a squeeze of lemon juice.\n8. Garnish with cilantro and serve hot.",
        "ingredients": [
            ("Chicken thighs", 400.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Bay leaf", 1.0, "pieces"),
            ("Cinnamon stick", 1.0, "pieces"),
            ("Black pepper", 1.0, "tsp"),
            ("Cumin powder", 0.5, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Ghee", 1.0, "tbsp"),
            ("Lemon", 1.0, "pieces"),
        ],
    },
    {
        "title": "Gobi Manchurian",
        "description": "Indo-Chinese crispy cauliflower florets tossed in a spicy soy-chili sauce. An addictive appetizer.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "budget", "spicy"],
        "instructions": "1. Cut cauliflower into small florets. Make a batter with corn flour, all-purpose flour, and salt.\n2. Dip florets in batter and deep fry in batches until golden and crispy. Set aside.\n3. Heat oil in a wok, add chopped garlic, ginger, and green chili.\n4. Add diced onion and bell pepper. Stir-fry on high heat for 2 minutes.\n5. Add soy sauce, vinegar, and chili sauce. Toss well.\n6. Add the fried cauliflower and toss to coat evenly in the sauce.\n7. Garnish with spring onion greens and serve immediately.",
        "ingredients": [
            ("Cauliflower", 1.0, "pieces"),
            ("Corn flour", 3.0, "tbsp"),
            ("All-purpose flour", 2.0, "tbsp"),
            ("Garlic cloves", 5.0, "pieces"),
            ("Ginger", 1.0, "tbsp"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Vinegar", 1.0, "tbsp"),
            ("Green chili", 2.0, "pieces"),
            ("Oil", 2.0, "cups"),
            ("Spring onion", 2.0, "pieces"),
        ],
    },
    {
        "title": "Moth Dal Curry",
        "description": "Sprouted moth beans cooked in a spiced tomato gravy. High in protein and deeply nourishing.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Soak moth dal overnight. Drain and sprout for 12 hours if desired.\n2. Pressure cook moth dal with turmeric and salt for 4 whistles.\n3. Heat oil, add cumin seeds and asafoetida.\n4. Add chopped onion and cook until golden.\n5. Add ginger-garlic paste, chopped tomatoes, and chili powder. Cook until tomatoes soften.\n6. Add the cooked moth dal and half a cup of water.\n7. Simmer for 15 minutes until the gravy thickens.\n8. Add garam masala and cilantro. Serve with rice or roti.",
        "ingredients": [
            ("Moth dal", 1.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato", 2.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Asafoetida", 0.25, "tsp"),
            ("Red chili powder", 0.5, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Garam masala", 0.5, "tsp"),
            ("Oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Chicken Pepper Fry",
        "description": "South Indian dry chicken fry loaded with cracked black pepper and curry leaves. Bold and spicy.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget", "spicy"],
        "instructions": "1. Marinate chicken thigh pieces with turmeric, chili powder, and salt for 15 minutes.\n2. Heat oil in a heavy pan and add mustard seeds and curry leaves.\n3. Add sliced onions and cook until softened.\n4. Add ginger-garlic paste and saute for a minute.\n5. Add the marinated chicken and sear on high heat for 5 minutes.\n6. Add crushed black pepper and cover. Cook on medium heat for 20 minutes.\n7. Remove lid and cook on high heat until chicken is dry and well coated with spices.\n8. Garnish with fresh curry leaves and serve.",
        "ingredients": [
            ("Chicken thighs", 500.0, "g"),
            ("Onion", 2.0, "pieces"),
            ("Ginger-garlic paste", 1.0, "tbsp"),
            ("Black pepper", 2.0, "tsp"),
            ("Curry leaves", 10.0, "pieces"),
            ("Mustard seeds", 0.5, "tsp"),
            ("Turmeric powder", 0.5, "tsp"),
            ("Red chili powder", 1.0, "tsp"),
            ("Oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
]
