ITALIAN_RECIPES = [
    {
        "title": "Spaghetti Aglio e Olio",
        "description": "A classic Roman pasta dish with garlic, olive oil, and chili flakes. Simple yet deeply flavorful.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegan", "budget", "pasta", "quick"],
        "instructions": "1. Bring a large pot of salted water to a boil and cook spaghetti until al dente.\n2. While pasta cooks, thinly slice garlic and heat olive oil in a large skillet over medium-low heat.\n3. Add garlic to the oil and cook gently until golden, about 2 minutes.\n4. Add red pepper flakes and cook for 30 seconds.\n5. Reserve one cup of pasta water, then drain the spaghetti.\n6. Add spaghetti to the skillet and toss with the garlic oil, adding pasta water as needed.\n7. Season with salt, toss in fresh parsley, and serve immediately.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Garlic cloves", 6.0, "pieces"),
            ("Extra virgin olive oil", 80.0, "ml"),
            ("Red pepper flakes", 1.0, "tsp"),
            ("Fresh parsley", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Cacio e Pepe",
        "description": "A beloved Roman pasta made with just pecorino cheese and black pepper. Deceptively simple and incredibly rich.",
        "difficulty": "medium",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "budget", "pasta", "quick"],
        "instructions": "1. Bring a large pot of salted water to a boil and cook tonnarelli or spaghetti until al dente.\n2. Finely grate the pecorino romano into a bowl.\n3. Toast whole black peppercorns in a dry skillet, then crack them coarsely.\n4. Add cracked pepper to the skillet with a ladle of pasta water and let it simmer.\n5. Reserve two cups of pasta water, then drain the pasta.\n6. Add pasta to the skillet, remove from heat, and toss vigorously while adding pecorino a little at a time.\n7. Add splashes of pasta water as needed to form a creamy sauce.\n8. Serve immediately with extra pecorino and pepper on top.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Pecorino romano", 200.0, "g"),
            ("Black peppercorns", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pasta al Pomodoro",
        "description": "The quintessential Italian tomato pasta. Sweet San Marzano tomatoes, garlic, and fresh basil over perfectly cooked pasta.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegan", "budget", "pasta"],
        "instructions": "1. Heat olive oil in a large saucepan over medium heat.\n2. Add garlic and cook for one minute until fragrant.\n3. Crush the canned tomatoes by hand and add them to the pan with salt.\n4. Simmer the sauce for 20 minutes, stirring occasionally.\n5. Meanwhile, cook spaghetti in salted boiling water until al dente.\n6. Toss the drained pasta into the sauce with fresh basil leaves.\n7. Serve with a drizzle of olive oil.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Canned San Marzano tomatoes", 800.0, "g"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Fresh basil leaves", 10.0, "pieces"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pasta alla Carbonara",
        "description": "Iconic Roman pasta with guanciale, eggs, pecorino, and black pepper. No cream ever touches this dish.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["budget", "pasta", "high-protein"],
        "instructions": "1. Cut guanciale into small strips and cook in a skillet over medium heat until crispy and the fat has rendered.\n2. In a bowl, whisk together egg yolks, whole egg, grated pecorino, and generous black pepper.\n3. Cook rigatoni in salted boiling water until al dente.\n4. Reserve a cup of pasta water and drain the pasta.\n5. Add pasta to the skillet with guanciale, remove from heat.\n6. Quickly pour the egg and cheese mixture over the pasta, tossing vigorously.\n7. Add small splashes of pasta water to achieve a silky, creamy consistency.\n8. Serve immediately with extra pecorino and black pepper.",
        "ingredients": [
            ("Rigatoni", 400.0, "g"),
            ("Guanciale", 200.0, "g"),
            ("Egg yolks", 4.0, "pieces"),
            ("Whole egg", 1.0, "pieces"),
            ("Pecorino romano", 100.0, "g"),
            ("Black pepper", 1.0, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pasta alla Puttanesca",
        "description": "A bold, punchy Neapolitan pasta with olives, capers, anchovies, and tomatoes. Ready in under 30 minutes.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["budget", "pasta", "quick"],
        "instructions": "1. Heat olive oil in a large skillet and add minced garlic and anchovy fillets, stirring until anchovies dissolve.\n2. Add red pepper flakes and cook for 30 seconds.\n3. Pour in crushed tomatoes and simmer for 10 minutes.\n4. Add olives and capers, stir, and continue simmering for 5 minutes.\n5. Cook spaghetti in salted boiling water until al dente.\n6. Drain pasta and toss it into the sauce.\n7. Garnish with fresh parsley and serve.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Canned crushed tomatoes", 400.0, "g"),
            ("Black olives", 80.0, "g"),
            ("Capers", 2.0, "tbsp"),
            ("Anchovy fillets", 6.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Red pepper flakes", 0.5, "tsp"),
            ("Fresh parsley", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Minestrone Soup",
        "description": "A hearty Italian vegetable soup loaded with beans, pasta, and seasonal vegetables. Perfect for using up whatever is in the fridge.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 6,
        "tags": ["vegan", "budget", "soup", "one-pot"],
        "instructions": "1. Heat olive oil in a large pot over medium heat and sauté diced onion, carrot, and celery until softened.\n2. Add diced zucchini and green beans, cook for 3 minutes.\n3. Pour in canned tomatoes, vegetable broth, and drained cannellini beans.\n4. Bring to a boil, then reduce heat and simmer for 20 minutes.\n5. Add small pasta and cook until tender, about 10 minutes.\n6. Season with salt and pepper to taste.\n7. Serve with a drizzle of olive oil and crusty bread.",
        "ingredients": [
            ("Onion", 1.0, "pieces"),
            ("Carrot", 2.0, "pieces"),
            ("Celery stalks", 2.0, "pieces"),
            ("Zucchini", 1.0, "pieces"),
            ("Green beans", 100.0, "g"),
            ("Canned cannellini beans", 400.0, "g"),
            ("Canned diced tomatoes", 400.0, "g"),
            ("Small pasta like ditalini", 100.0, "g"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Ribollita",
        "description": "A thick Tuscan bread soup made with cannellini beans, lacinato kale, and day-old bread. The ultimate peasant comfort food.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 50,
        "servings": 6,
        "tags": ["vegan", "budget", "soup", "one-pot"],
        "instructions": "1. Heat olive oil in a large pot and sauté onion, carrot, and celery until soft.\n2. Add chopped kale and cook until wilted, about 5 minutes.\n3. Stir in canned tomatoes and drained cannellini beans.\n4. Pour in vegetable broth and bring to a simmer.\n5. Cook for 30 minutes until vegetables are very tender.\n6. Tear day-old bread into chunks and stir it into the soup.\n7. Let the soup sit for 10 minutes so the bread absorbs the liquid.\n8. Serve drizzled with olive oil and seasoned with black pepper.",
        "ingredients": [
            ("Cannellini beans", 400.0, "g"),
            ("Lacinato kale", 200.0, "g"),
            ("Day-old crusty bread", 200.0, "g"),
            ("Canned diced tomatoes", 400.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Carrot", 2.0, "pieces"),
            ("Celery stalks", 2.0, "pieces"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 1.0, "to taste"),
        ],
    },
    {
        "title": "Risotto alla Milanese",
        "description": "A golden saffron risotto from Milan. Luxuriously creamy and traditionally served alongside ossobuco.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "budget", "gluten-free"],
        "instructions": "1. Heat broth in a saucepan and keep it at a gentle simmer.\n2. In a separate heavy pot, melt half the butter and sauté diced onion until translucent.\n3. Add arborio rice and toast for 2 minutes, stirring constantly.\n4. Add saffron threads to a ladle of warm broth to dissolve, then add to the rice.\n5. Add broth one ladle at a time, stirring frequently and waiting until each addition is absorbed.\n6. Continue for about 18 minutes until rice is creamy and al dente.\n7. Remove from heat, stir in remaining butter and grated parmesan.\n8. Season with salt, cover for 2 minutes, then serve.",
        "ingredients": [
            ("Arborio rice", 320.0, "g"),
            ("Chicken or vegetable broth", 1.0, "l"),
            ("Saffron threads", 0.25, "tsp"),
            ("Onion", 1.0, "pieces"),
            ("Butter", 60.0, "g"),
            ("Parmesan cheese", 80.0, "g"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Polenta with Mushroom Ragu",
        "description": "Creamy polenta topped with a rich, earthy mushroom sauce. Hearty northern Italian comfort food at its best.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 40,
        "servings": 4,
        "tags": ["vegetarian", "budget", "gluten-free"],
        "instructions": "1. Bring salted water to a boil and slowly whisk in polenta, stirring constantly to prevent lumps.\n2. Reduce heat to low and cook polenta for 30 minutes, stirring frequently.\n3. Meanwhile, heat olive oil in a skillet and sauté sliced mushrooms until golden.\n4. Add minced garlic and fresh thyme, cook for another minute.\n5. Pour in a splash of broth and simmer until the sauce thickens.\n6. Stir butter and parmesan into the finished polenta.\n7. Serve polenta in bowls topped with the mushroom ragu.",
        "ingredients": [
            ("Polenta cornmeal", 250.0, "g"),
            ("Mixed mushrooms", 400.0, "g"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh thyme", 1.0, "tbsp"),
            ("Vegetable broth", 100.0, "ml"),
            ("Butter", 30.0, "g"),
            ("Parmesan cheese", 50.0, "g"),
            ("Extra virgin olive oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Frittata di Zucchine",
        "description": "A simple Italian egg and zucchini frittata. Versatile enough for breakfast, lunch, or dinner.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "budget", "gluten-free", "quick", "high-protein"],
        "instructions": "1. Slice zucchini into thin rounds.\n2. Heat olive oil in an oven-safe skillet and sauté zucchini until lightly golden.\n3. Beat eggs in a bowl with grated parmesan, salt, and pepper.\n4. Pour the egg mixture over the zucchini in the skillet.\n5. Cook on medium-low heat until the edges are set, about 5 minutes.\n6. Transfer the skillet under a hot broiler for 3-4 minutes until the top is golden.\n7. Let cool slightly, then slide onto a plate and serve.",
        "ingredients": [
            ("Eggs", 8.0, "pieces"),
            ("Zucchini", 3.0, "pieces"),
            ("Parmesan cheese", 50.0, "g"),
            ("Extra virgin olive oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Pasta e Fagioli",
        "description": "A thick, rustic pasta and bean soup from southern Italy. Filling, nutritious, and incredibly cheap to make.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 6,
        "tags": ["vegan", "budget", "soup", "one-pot", "pasta", "high-protein"],
        "instructions": "1. Heat olive oil in a large pot and sauté diced onion, carrot, and celery until soft.\n2. Add minced garlic and rosemary, cook for one minute.\n3. Add canned tomatoes and half the drained cannellini beans.\n4. Mash the remaining beans with a fork and add them to the pot for thickness.\n5. Pour in broth, bring to a boil, then add small pasta.\n6. Cook until pasta is tender, about 10 minutes.\n7. Season with salt and pepper and serve with a drizzle of olive oil.",
        "ingredients": [
            ("Ditalini pasta", 200.0, "g"),
            ("Canned cannellini beans", 800.0, "g"),
            ("Canned diced tomatoes", 400.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Celery stalk", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh rosemary", 1.0, "tsp"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Bruschetta al Pomodoro",
        "description": "Toasted bread rubbed with garlic and topped with fresh diced tomatoes, basil, and olive oil. The perfect antipasto.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 5,
        "servings": 4,
        "tags": ["vegan", "budget", "quick"],
        "instructions": "1. Dice ripe tomatoes and combine with torn basil, olive oil, and a pinch of salt.\n2. Let the tomato mixture rest for 10 minutes to develop flavor.\n3. Slice the bread into thick pieces and toast or grill until golden.\n4. Rub each slice with a cut garlic clove while still warm.\n5. Spoon the tomato mixture generously on top of each bread slice.\n6. Drizzle with extra olive oil and serve immediately.",
        "ingredients": [
            ("Ripe tomatoes", 4.0, "pieces"),
            ("Crusty Italian bread", 8.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh basil leaves", 8.0, "pieces"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Penne all'Arrabbiata",
        "description": "An angry pasta from Rome with a spicy tomato sauce loaded with garlic and chili. Quick and fiery.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegan", "budget", "pasta", "quick"],
        "instructions": "1. Heat olive oil in a skillet over medium heat and add sliced garlic.\n2. Cook garlic until just golden, then add red pepper flakes.\n3. Pour in crushed tomatoes and season with salt.\n4. Simmer the sauce for 15 minutes until thickened.\n5. Cook penne in salted boiling water until al dente.\n6. Drain the penne and toss it into the spicy tomato sauce.\n7. Garnish with fresh parsley and serve.",
        "ingredients": [
            ("Penne", 400.0, "g"),
            ("Canned crushed tomatoes", 400.0, "g"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Red pepper flakes", 1.0, "tsp"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Fresh parsley", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Focaccia Genovese",
        "description": "A pillowy, olive oil-drenched Ligurian flatbread with a crispy bottom and dimpled top sprinkled with flaky salt.",
        "difficulty": "medium",
        "prep_time": 30,
        "cook_time": 25,
        "servings": 6,
        "tags": ["vegan", "budget"],
        "instructions": "1. Dissolve yeast in warm water and let it sit for 5 minutes until foamy.\n2. Combine flour and salt in a bowl, then add the yeast mixture and olive oil.\n3. Mix until a shaggy dough forms, then knead for 8 minutes until smooth.\n4. Place dough in an oiled bowl, cover, and let rise for 90 minutes until doubled.\n5. Oil a baking sheet generously and stretch the dough to fill it.\n6. Dimple the surface with your fingers, drizzle with more oil, and sprinkle with flaky salt.\n7. Let rest for 20 minutes while preheating oven to 220 degrees Celsius.\n8. Bake for 20-25 minutes until golden and crisp on the bottom.",
        "ingredients": [
            ("Bread flour", 500.0, "g"),
            ("Warm water", 350.0, "ml"),
            ("Instant yeast", 2.0, "tsp"),
            ("Extra virgin olive oil", 80.0, "ml"),
            ("Flaky sea salt", 1.0, "tsp"),
            ("Salt", 2.0, "tsp"),
        ],
    },
    {
        "title": "Panzanella",
        "description": "A Tuscan bread and tomato salad that makes stale bread shine. Best in summer when tomatoes are at peak ripeness.",
        "difficulty": "easy",
        "prep_time": 20,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegan", "budget", "quick"],
        "instructions": "1. Tear day-old bread into rough chunks and soak briefly in water, then squeeze dry.\n2. Dice ripe tomatoes and place in a large bowl, catching all the juices.\n3. Slice cucumber, red onion, and tear fresh basil leaves.\n4. Combine bread, tomatoes, cucumber, onion, and basil in the bowl.\n5. Dress with olive oil and red wine vinegar, season with salt and pepper.\n6. Toss everything together and let sit for 15 minutes before serving so flavors meld.",
        "ingredients": [
            ("Day-old crusty bread", 300.0, "g"),
            ("Ripe tomatoes", 4.0, "pieces"),
            ("Cucumber", 1.0, "pieces"),
            ("Red onion", 0.5, "pieces"),
            ("Fresh basil", 10.0, "pieces"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Red wine vinegar", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pasta alla Norma",
        "description": "A Sicilian masterpiece of fried eggplant tossed with tomato sauce, pasta, and ricotta salata. Named after Bellini's opera.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "budget", "pasta"],
        "instructions": "1. Slice eggplant into rounds, salt them, and let drain for 15 minutes, then pat dry.\n2. Fry eggplant slices in olive oil until golden on both sides, then drain on paper towels.\n3. In the same pan, sauté garlic until fragrant, then add crushed tomatoes.\n4. Simmer the sauce for 15 minutes with torn basil.\n5. Cook rigatoni in salted boiling water until al dente.\n6. Toss drained pasta with the tomato sauce.\n7. Plate the pasta, top with fried eggplant and crumbled ricotta salata.\n8. Garnish with fresh basil and serve.",
        "ingredients": [
            ("Rigatoni", 400.0, "g"),
            ("Eggplant", 2.0, "pieces"),
            ("Canned crushed tomatoes", 400.0, "g"),
            ("Ricotta salata", 80.0, "g"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh basil leaves", 10.0, "pieces"),
            ("Extra virgin olive oil", 80.0, "ml"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Spaghetti alle Vongole",
        "description": "Spaghetti with clams in a white wine and garlic sauce. A coastal Italian classic from Naples.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "tags": ["budget", "pasta", "quick"],
        "instructions": "1. Soak clams in cold salted water for 30 minutes to purge sand, then scrub clean.\n2. Heat olive oil in a large pan, add garlic and red pepper flakes.\n3. Add clams and white wine, cover, and cook until clams open, about 5 minutes.\n4. Discard any clams that remain closed.\n5. Cook spaghetti in salted boiling water until al dente.\n6. Add drained pasta to the pan with the clams and toss together.\n7. Add pasta water if needed and finish with fresh parsley.\n8. Serve immediately.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Fresh clams", 1.0, "kg"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Dry white wine", 120.0, "ml"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Red pepper flakes", 0.5, "tsp"),
            ("Fresh parsley", 3.0, "tbsp"),
        ],
    },
    {
        "title": "Insalata Caprese",
        "description": "Fresh mozzarella, ripe tomatoes, and basil drizzled with olive oil. The colors of the Italian flag on a plate.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick"],
        "instructions": "1. Slice fresh mozzarella and ripe tomatoes into even rounds.\n2. Arrange tomato and mozzarella slices alternating on a platter.\n3. Tuck fresh basil leaves between the slices.\n4. Drizzle generously with extra virgin olive oil.\n5. Season with flaky salt and black pepper.\n6. Serve at room temperature for the best flavor.",
        "ingredients": [
            ("Fresh mozzarella", 250.0, "g"),
            ("Ripe tomatoes", 4.0, "pieces"),
            ("Fresh basil leaves", 12.0, "pieces"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Flaky salt", 1.0, "pinch"),
            ("Black pepper", 1.0, "to taste"),
        ],
    },
    {
        "title": "Risotto ai Funghi Porcini",
        "description": "A rich, woodsy mushroom risotto using dried porcini to create an intensely savory dish. Northern Italian elegance.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "budget", "gluten-free"],
        "instructions": "1. Soak dried porcini in warm water for 20 minutes, then drain and reserve the soaking liquid.\n2. Heat broth in a saucepan and add the strained porcini soaking liquid.\n3. Sauté diced onion in butter and olive oil until translucent.\n4. Add rice and toast for 2 minutes, stirring constantly.\n5. Add soaked porcini and begin adding warm broth one ladle at a time, stirring frequently.\n6. Continue for about 18 minutes until rice is creamy and al dente.\n7. Remove from heat, stir in butter and parmesan.\n8. Season with salt and pepper, then serve.",
        "ingredients": [
            ("Arborio rice", 320.0, "g"),
            ("Dried porcini mushrooms", 40.0, "g"),
            ("Vegetable broth", 1.0, "l"),
            ("Onion", 1.0, "pieces"),
            ("Butter", 50.0, "g"),
            ("Parmesan cheese", 80.0, "g"),
            ("Extra virgin olive oil", 1.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Acquacotta",
        "description": "A Tuscan egg-drop vegetable soup meaning 'cooked water'. A humble shepherd's dish elevated by a poached egg and pecorino.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "budget", "soup", "one-pot"],
        "instructions": "1. Heat olive oil in a pot and sauté sliced onion and celery until softened.\n2. Add diced tomatoes and cook for 5 minutes.\n3. Pour in water or light broth and bring to a simmer.\n4. Cook for 20 minutes until vegetables are very tender.\n5. Crack eggs gently into the simmering soup and poach for 3 minutes.\n6. Place slices of toasted bread in each bowl and ladle soup over them.\n7. Top with grated pecorino and serve.",
        "ingredients": [
            ("Onions", 2.0, "pieces"),
            ("Celery stalks", 3.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Eggs", 4.0, "pieces"),
            ("Day-old bread", 4.0, "pieces"),
            ("Pecorino cheese", 50.0, "g"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Orecchiette con Cime di Rapa",
        "description": "Ear-shaped pasta with broccoli rabe, garlic, chili, and anchovies. A signature dish of Puglia.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["budget", "pasta", "quick"],
        "instructions": "1. Trim and wash broccoli rabe, cutting away thick stems.\n2. Blanch broccoli rabe in salted boiling water for 2 minutes, remove and set aside.\n3. Cook orecchiette in the same water until al dente.\n4. Heat olive oil in a large skillet and add garlic, anchovy fillets, and red pepper flakes.\n5. Cook until anchovies dissolve and garlic is golden.\n6. Add the blanched broccoli rabe and sauté for 3 minutes.\n7. Drain pasta and add to the skillet, tossing everything together.\n8. Serve with a drizzle of olive oil.",
        "ingredients": [
            ("Orecchiette", 400.0, "g"),
            ("Broccoli rabe", 500.0, "g"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Anchovy fillets", 4.0, "pieces"),
            ("Red pepper flakes", 0.5, "tsp"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Caponata",
        "description": "A Sicilian sweet and sour eggplant stew with tomatoes, olives, and capers. Served as an appetizer or side dish.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 6,
        "tags": ["vegan", "budget", "gluten-free"],
        "instructions": "1. Dice eggplant into cubes, salt them, and let drain for 15 minutes.\n2. Fry eggplant cubes in olive oil until golden, then drain on paper towels.\n3. In the same pan, sauté diced onion and celery until soft.\n4. Add crushed tomatoes and simmer for 10 minutes.\n5. Stir in olives, capers, and red wine vinegar.\n6. Return fried eggplant to the pan and cook together for 5 minutes.\n7. Season with salt and pepper, then let cool to room temperature before serving.",
        "ingredients": [
            ("Eggplant", 3.0, "pieces"),
            ("Canned crushed tomatoes", 300.0, "g"),
            ("Celery stalks", 2.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Green olives", 60.0, "g"),
            ("Capers", 2.0, "tbsp"),
            ("Red wine vinegar", 2.0, "tbsp"),
            ("Extra virgin olive oil", 80.0, "ml"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Farinata di Ceci",
        "description": "A crispy Ligurian chickpea flatbread made from just chickpea flour, water, and olive oil. Naturally gluten-free.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegan", "gluten-free", "budget"],
        "instructions": "1. Whisk chickpea flour with water and a pinch of salt until smooth.\n2. Stir in olive oil and let the batter rest for at least 30 minutes.\n3. Preheat oven to 230 degrees Celsius with a well-oiled baking pan inside.\n4. Skim any foam from the batter surface.\n5. Pour batter into the hot pan, tilting to spread evenly.\n6. Bake for 20-25 minutes until the top is golden and the edges crisp.\n7. Season with black pepper, cut into wedges, and serve warm.",
        "ingredients": [
            ("Chickpea flour", 200.0, "g"),
            ("Water", 500.0, "ml"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Pasta e Ceci",
        "description": "A Roman pasta and chickpea soup that is thick, creamy, and deeply satisfying. Humble pantry cooking at its finest.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegan", "budget", "pasta", "soup", "one-pot", "high-protein"],
        "instructions": "1. Heat olive oil in a pot and sauté diced onion, carrot, and celery until soft.\n2. Add garlic and rosemary, cook for one minute.\n3. Add drained chickpeas and canned tomatoes, stir well.\n4. Mash about a third of the chickpeas against the side of the pot for thickness.\n5. Pour in broth and bring to a boil.\n6. Add small pasta and cook until tender.\n7. Season with salt and pepper, drizzle with olive oil, and serve.",
        "ingredients": [
            ("Short pasta like ditalini", 200.0, "g"),
            ("Canned chickpeas", 800.0, "g"),
            ("Canned diced tomatoes", 200.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Celery stalk", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh rosemary", 1.0, "tsp"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Frittata di Pasta",
        "description": "A Neapolitan way to use leftover pasta by turning it into a golden, crispy egg cake. The original Italian leftovers hack.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "budget", "quick", "high-protein"],
        "instructions": "1. Beat eggs in a large bowl with grated parmesan, salt, and pepper.\n2. Add leftover cooked pasta to the egg mixture and toss to coat.\n3. Heat olive oil in a non-stick skillet over medium heat.\n4. Pour the pasta-egg mixture into the skillet and press down gently.\n5. Cook undisturbed for 8 minutes until the bottom is golden and set.\n6. Place a plate over the skillet, flip the frittata onto it, then slide back into the pan.\n7. Cook the other side for 5 minutes until golden.\n8. Slide onto a plate, let cool slightly, and slice into wedges.",
        "ingredients": [
            ("Leftover cooked pasta", 400.0, "g"),
            ("Eggs", 6.0, "pieces"),
            ("Parmesan cheese", 60.0, "g"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Zuppa di Lenticchie",
        "description": "A warming Italian lentil soup with tomatoes, carrots, and a generous drizzle of olive oil. Protein-rich and nourishing.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 40,
        "servings": 6,
        "tags": ["vegan", "budget", "soup", "one-pot", "gluten-free", "high-protein"],
        "instructions": "1. Heat olive oil in a large pot and sauté diced onion, carrot, and celery until soft.\n2. Add minced garlic and cook for one minute.\n3. Rinse lentils and add them to the pot along with canned tomatoes.\n4. Pour in broth and bring to a boil.\n5. Reduce heat and simmer for 30 minutes until lentils are tender.\n6. Season with salt and pepper.\n7. Serve drizzled with extra virgin olive oil and crusty bread on the side.",
        "ingredients": [
            ("Green or brown lentils", 300.0, "g"),
            ("Canned diced tomatoes", 400.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Carrots", 2.0, "pieces"),
            ("Celery stalks", 2.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Vegetable broth", 1.0, "l"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pappa al Pomodoro",
        "description": "A thick Tuscan tomato and bread soup. A genius way to transform stale bread into silky comfort food.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegan", "budget", "soup"],
        "instructions": "1. Heat olive oil in a pot and sauté minced garlic until fragrant.\n2. Add crushed tomatoes and simmer for 10 minutes.\n3. Tear stale bread into pieces and stir into the tomato mixture.\n4. Add broth and cook, stirring frequently, until the bread dissolves into a thick porridge.\n5. Tear in fresh basil leaves and stir.\n6. Season with salt and pepper.\n7. Serve warm or at room temperature with a generous drizzle of olive oil.",
        "ingredients": [
            ("Day-old Tuscan bread", 300.0, "g"),
            ("Canned crushed tomatoes", 600.0, "g"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Fresh basil leaves", 10.0, "pieces"),
            ("Vegetable broth", 250.0, "ml"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Linguine al Pesto Genovese",
        "description": "Ligurian basil pesto with pine nuts and pecorino tossed with linguine. Bright, fragrant, and utterly addictive.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 12,
        "servings": 4,
        "tags": ["vegetarian", "budget", "pasta", "quick"],
        "instructions": "1. Pound garlic and pine nuts in a mortar with a pinch of salt until a paste forms.\n2. Add fresh basil leaves in batches, grinding to a bright green paste.\n3. Work in grated pecorino and parmesan cheese.\n4. Slowly drizzle in olive oil while stirring until smooth and emulsified.\n5. Cook linguine in salted boiling water until al dente.\n6. Reserve pasta water, then drain linguine and toss with the pesto.\n7. Add splashes of pasta water to loosen, and serve immediately.",
        "ingredients": [
            ("Linguine", 400.0, "g"),
            ("Fresh basil leaves", 60.0, "g"),
            ("Pine nuts", 30.0, "g"),
            ("Garlic cloves", 1.0, "pieces"),
            ("Pecorino cheese", 30.0, "g"),
            ("Parmesan cheese", 50.0, "g"),
            ("Extra virgin olive oil", 80.0, "ml"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Spaghetti alla Gricia",
        "description": "The lesser-known Roman classic and ancestor of carbonara. Guanciale, pecorino, and black pepper with no eggs or tomato.",
        "difficulty": "medium",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "tags": ["budget", "pasta", "quick"],
        "instructions": "1. Cut guanciale into strips and cook in a dry skillet over medium heat until crispy.\n2. Remove guanciale and reserve the rendered fat in the pan.\n3. Cook spaghetti in salted boiling water until al dente.\n4. Reserve a cup of starchy pasta water.\n5. Add pasta to the skillet with guanciale fat, toss to coat.\n6. Remove from heat and toss in grated pecorino, adding pasta water to make a creamy sauce.\n7. Return crispy guanciale to the pan, add black pepper, and toss.\n8. Serve immediately with extra pecorino.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Guanciale", 200.0, "g"),
            ("Pecorino romano", 120.0, "g"),
            ("Black pepper", 1.5, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pasta al Burro e Parmigiano",
        "description": "The simplest Italian pasta: butter and parmesan. What Italian children eat and what adults crave when nothing else will do.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 12,
        "servings": 4,
        "tags": ["vegetarian", "budget", "pasta", "quick"],
        "instructions": "1. Cook pasta in generously salted boiling water until al dente.\n2. Reserve a cup of pasta water before draining.\n3. Return pasta to the pot, add butter, and toss until melted.\n4. Add grated parmesan cheese in batches, tossing vigorously.\n5. Add splashes of pasta water as needed to create a silky coating.\n6. Season with a touch of black pepper and serve immediately.",
        "ingredients": [
            ("Fettuccine or tagliatelle", 400.0, "g"),
            ("Butter", 80.0, "g"),
            ("Parmesan cheese", 120.0, "g"),
            ("Black pepper", 0.5, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Stracciatella alla Romana",
        "description": "A Roman egg-drop soup with whisked eggs and parmesan swirled into hot broth. Ready in minutes and wonderfully light.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick", "soup"],
        "instructions": "1. Bring chicken or vegetable broth to a gentle simmer in a pot.\n2. In a bowl, whisk together eggs, grated parmesan, and a pinch of salt.\n3. While stirring the broth in a circular motion, slowly drizzle in the egg mixture.\n4. Let the egg strands cook for 2 minutes without stirring.\n5. Season with salt, pepper, and a dash of nutmeg.\n6. Ladle into bowls and serve immediately.",
        "ingredients": [
            ("Chicken or vegetable broth", 1.0, "l"),
            ("Eggs", 3.0, "pieces"),
            ("Parmesan cheese", 50.0, "g"),
            ("Nutmeg", 1.0, "pinch"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pomodori Ripieni di Riso",
        "description": "Roman-style tomatoes stuffed with herbed rice and baked until tender. A classic summer dish from the Eternal City.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 50,
        "servings": 4,
        "tags": ["vegan", "budget", "gluten-free"],
        "instructions": "1. Cut tops off ripe tomatoes and scoop out the pulp, reserving it.\n2. Chop the tomato pulp and mix with uncooked rice, garlic, basil, and olive oil.\n3. Season the filling with salt and pepper.\n4. Stuff each tomato with the rice mixture, leaving room for the rice to expand.\n5. Place stuffed tomatoes in a baking dish with potatoes cut into wedges alongside.\n6. Drizzle everything with olive oil and add a splash of water to the dish.\n7. Bake at 180 degrees Celsius for 50 minutes until rice is cooked and tomatoes are soft.\n8. Serve warm or at room temperature.",
        "ingredients": [
            ("Large ripe tomatoes", 8.0, "pieces"),
            ("Arborio rice", 200.0, "g"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh basil", 8.0, "pieces"),
            ("Potatoes", 3.0, "pieces"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Fettuccine ai Funghi",
        "description": "Wide ribbons of pasta tossed with sauteed mushrooms, garlic, and a touch of cream. Earthy and elegant.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "budget", "pasta", "quick"],
        "instructions": "1. Slice mushrooms and mince garlic.\n2. Heat olive oil and butter in a large skillet over high heat.\n3. Add mushrooms in a single layer and cook without stirring for 3 minutes until golden.\n4. Stir, add garlic and thyme, and cook for 2 more minutes.\n5. Cook fettuccine in salted boiling water until al dente.\n6. Add pasta to the skillet with a splash of pasta water and toss.\n7. Finish with grated parmesan, parsley, and black pepper.",
        "ingredients": [
            ("Fettuccine", 400.0, "g"),
            ("Mixed mushrooms", 400.0, "g"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Butter", 30.0, "g"),
            ("Extra virgin olive oil", 2.0, "tbsp"),
            ("Fresh thyme", 1.0, "tsp"),
            ("Parmesan cheese", 50.0, "g"),
            ("Fresh parsley", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Peperonata",
        "description": "Slow-cooked Italian peppers with tomatoes, onions, and olive oil. A vibrant side dish or topping for crostini.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegan", "gluten-free", "budget"],
        "instructions": "1. Slice bell peppers and onion into strips.\n2. Heat olive oil in a large skillet over medium heat.\n3. Add onion and cook until softened, about 5 minutes.\n4. Add peppers and cook, stirring occasionally, for 10 minutes.\n5. Add diced tomatoes, season with salt, and cover.\n6. Cook on low heat for 20 minutes until peppers are very tender.\n7. Adjust seasoning and serve warm or at room temperature.",
        "ingredients": [
            ("Bell peppers mixed colors", 4.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Canned diced tomatoes", 200.0, "g"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Pasta con le Sarde",
        "description": "A Sicilian pasta with sardines, fennel, pine nuts, and saffron. A unique sweet-savory flavor profile of the island.",
        "difficulty": "hard",
        "prep_time": 20,
        "cook_time": 30,
        "servings": 4,
        "tags": ["budget", "pasta"],
        "instructions": "1. Trim and chop wild fennel fronds and blanch them in salted water, reserving the water.\n2. Cook bucatini in the fennel water until al dente.\n3. Clean fresh sardines, removing heads and bones.\n4. Sauté onion in olive oil until soft, then add sardine fillets and break them up.\n5. Add soaked saffron, pine nuts, and blanched fennel, stirring gently.\n6. Drain pasta and toss into the sardine sauce.\n7. Transfer to a baking dish, top with breadcrumbs.\n8. Bake at 200 degrees Celsius for 10 minutes until the top is crisp.",
        "ingredients": [
            ("Bucatini", 400.0, "g"),
            ("Fresh sardines", 400.0, "g"),
            ("Fennel fronds", 200.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Pine nuts", 30.0, "g"),
            ("Saffron threads", 0.25, "tsp"),
            ("Breadcrumbs", 3.0, "tbsp"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Uova in Purgatorio",
        "description": "Eggs poached in a spicy tomato sauce, Italian-style. A quick, satisfying meal often eaten with bread for dipping.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 2,
        "tags": ["vegetarian", "gluten-free", "budget", "quick", "one-pot", "high-protein"],
        "instructions": "1. Heat olive oil in a skillet and sauté garlic until fragrant.\n2. Add red pepper flakes and cook for 30 seconds.\n3. Pour in canned crushed tomatoes, season with salt, and simmer for 10 minutes.\n4. Make small wells in the sauce and crack eggs into them.\n5. Cover the skillet and cook for 5-7 minutes until egg whites are set but yolks are runny.\n6. Scatter fresh basil on top and serve with crusty bread.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Canned crushed tomatoes", 400.0, "g"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Red pepper flakes", 0.5, "tsp"),
            ("Fresh basil leaves", 6.0, "pieces"),
            ("Extra virgin olive oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pizzoccheri della Valtellina",
        "description": "Buckwheat pasta baked with cabbage, potatoes, and melted fontina cheese. A hearty mountain dish from Lombardy.",
        "difficulty": "hard",
        "prep_time": 20,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Peel and dice potatoes into small cubes.\n2. Shred savoy cabbage into strips.\n3. Boil potatoes and cabbage together in salted water for 5 minutes.\n4. Add pizzoccheri pasta and cook until tender, about 10 minutes.\n5. Meanwhile, melt butter with whole garlic cloves and sage leaves.\n6. Drain everything and layer in a warm dish: pasta and vegetables, fontina, parmesan, and sage butter.\n7. Repeat layers, ending with cheese and butter.\n8. Let rest for 2 minutes so cheese melts, then serve.",
        "ingredients": [
            ("Pizzoccheri or buckwheat pasta", 400.0, "g"),
            ("Savoy cabbage", 200.0, "g"),
            ("Potatoes", 2.0, "pieces"),
            ("Fontina cheese", 150.0, "g"),
            ("Parmesan cheese", 60.0, "g"),
            ("Butter", 80.0, "g"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh sage leaves", 8.0, "pieces"),
        ],
    },
    {
        "title": "Zuppa Toscana",
        "description": "A creamy Tuscan soup with Italian sausage, potatoes, and kale. Warming and full of robust flavors.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 6,
        "tags": ["budget", "soup", "one-pot", "gluten-free"],
        "instructions": "1. Brown Italian sausage in a large pot, breaking it into pieces.\n2. Add diced onion and garlic, cook until softened.\n3. Pour in chicken broth and add sliced potatoes.\n4. Bring to a boil and simmer for 15 minutes until potatoes are tender.\n5. Add chopped kale and cook for 5 more minutes.\n6. Stir in a splash of milk or cream for richness.\n7. Season with salt, pepper, and red pepper flakes.\n8. Serve hot with crusty bread.",
        "ingredients": [
            ("Italian sausage", 500.0, "g"),
            ("Potatoes", 4.0, "pieces"),
            ("Kale", 200.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Chicken broth", 1.0, "l"),
            ("Milk", 120.0, "ml"),
            ("Red pepper flakes", 0.5, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Gnocchi di Patate",
        "description": "Pillowy potato gnocchi made from scratch. Light, fluffy dumplings perfect with any sauce.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Boil unpeeled potatoes until fork-tender, about 25 minutes.\n2. Peel the hot potatoes and rice them onto a clean work surface.\n3. Let the potatoes cool slightly, then add flour, egg, and a pinch of salt.\n4. Gently knead until a soft dough forms, being careful not to overwork it.\n5. Roll dough into long ropes and cut into small pieces.\n6. Roll each piece along a fork to create ridges.\n7. Cook gnocchi in batches in salted boiling water until they float.\n8. Toss with your choice of sauce and serve immediately.",
        "ingredients": [
            ("Starchy potatoes", 1.0, "kg"),
            ("All-purpose flour", 250.0, "g"),
            ("Egg", 1.0, "pieces"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Involtini di Melanzane",
        "description": "Eggplant rolls stuffed with ricotta and baked in tomato sauce. Elegant enough for company, easy enough for weeknights.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget"],
        "instructions": "1. Slice eggplants lengthwise into thin planks and grill or fry until pliable.\n2. Mix ricotta with parmesan, garlic, basil, salt, and pepper.\n3. Spread a tablespoon of ricotta mixture on each eggplant slice.\n4. Roll up tightly and place seam-side down in a baking dish.\n5. Pour tomato sauce over the rolls and sprinkle with mozzarella.\n6. Bake at 190 degrees Celsius for 25 minutes until bubbly.\n7. Let rest for 5 minutes, garnish with basil, and serve.",
        "ingredients": [
            ("Eggplants", 2.0, "pieces"),
            ("Ricotta", 250.0, "g"),
            ("Parmesan cheese", 50.0, "g"),
            ("Mozzarella", 100.0, "g"),
            ("Canned tomato sauce", 400.0, "g"),
            ("Fresh basil leaves", 8.0, "pieces"),
            ("Garlic clove", 1.0, "pieces"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pasta con Patate e Provola",
        "description": "A Neapolitan comfort dish of pasta cooked directly with potatoes and smoked provola cheese. Rich and starchy.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "budget", "pasta", "one-pot"],
        "instructions": "1. Dice potatoes into small cubes and finely chop onion, carrot, and celery.\n2. Sauté the vegetables in olive oil until softened.\n3. Add potatoes and enough water to cover, then season with salt.\n4. Bring to a simmer and cook for 10 minutes.\n5. Add mixed short pasta and cook until tender, adding more water if needed.\n6. The consistency should be thick and creamy, not soupy.\n7. Remove from heat and stir in cubed smoked provola.\n8. Let rest for 2 minutes so cheese melts, then serve with black pepper.",
        "ingredients": [
            ("Mixed short pasta", 300.0, "g"),
            ("Potatoes", 3.0, "pieces"),
            ("Smoked provola cheese", 150.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Celery stalk", 1.0, "pieces"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Polpette al Sugo",
        "description": "Italian meatballs braised in a rich tomato sauce. Tender, juicy, and nothing like the oversized versions found elsewhere.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 40,
        "servings": 4,
        "tags": ["budget", "high-protein"],
        "instructions": "1. Soak bread in milk until soft, then squeeze dry.\n2. Combine ground beef, soaked bread, egg, parmesan, garlic, parsley, salt, and pepper.\n3. Mix gently and form into walnut-sized meatballs.\n4. Brown meatballs in olive oil on all sides, then set aside.\n5. In the same pan, add crushed tomatoes and simmer for 10 minutes.\n6. Return meatballs to the sauce, cover, and simmer gently for 25 minutes.\n7. Serve with crusty bread or over pasta.",
        "ingredients": [
            ("Ground beef", 500.0, "g"),
            ("Day-old bread", 80.0, "g"),
            ("Milk", 60.0, "ml"),
            ("Egg", 1.0, "pieces"),
            ("Parmesan cheese", 40.0, "g"),
            ("Garlic clove", 1.0, "pieces"),
            ("Fresh parsley", 2.0, "tbsp"),
            ("Canned crushed tomatoes", 500.0, "g"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Brodo di Pollo con Pastina",
        "description": "Chicken broth with tiny pasta shapes. The Italian cure for everything from colds to sadness.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["budget", "soup", "quick"],
        "instructions": "1. Bring chicken broth to a boil in a pot.\n2. Add pastina and cook until tender, about 6 minutes.\n3. Beat an egg in a small bowl with grated parmesan.\n4. Remove pot from heat and stir in the egg mixture, creating silky strands.\n5. Season with salt and pepper.\n6. Ladle into bowls and serve with extra parmesan on top.",
        "ingredients": [
            ("Chicken broth", 1.0, "l"),
            ("Pastina or stelline", 150.0, "g"),
            ("Egg", 1.0, "pieces"),
            ("Parmesan cheese", 40.0, "g"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 1.0, "to taste"),
        ],
    },
    {
        "title": "Ciceri e Tria",
        "description": "A Puglian dish of chickpeas with fresh pasta, part boiled and part fried for crunch. Ancient and utterly unique.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegan", "budget", "pasta", "high-protein"],
        "instructions": "1. If using dried chickpeas, soak overnight and cook until tender. Otherwise, drain canned chickpeas.\n2. Make pasta dough with flour, water, and salt; roll thin and cut into irregular strips.\n3. Set aside one third of the raw pasta strips for frying.\n4. Fry the reserved strips in olive oil until golden and crispy, then drain on paper towels.\n5. Sauté garlic, onion, and a bay leaf in olive oil, then add chickpeas and broth.\n6. Simmer for 10 minutes, then add the remaining fresh pasta and cook until tender.\n7. Serve the soup topped with the crispy fried pasta strips.\n8. Drizzle with olive oil and season with black pepper.",
        "ingredients": [
            ("Canned chickpeas", 400.0, "g"),
            ("All-purpose flour", 300.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Bay leaf", 1.0, "pieces"),
            ("Extra virgin olive oil", 80.0, "ml"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Spaghetti con Acciughe e Pangrattato",
        "description": "Spaghetti with anchovies and toasted breadcrumbs, known as poor man's parmesan in southern Italy.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "tags": ["budget", "pasta", "quick"],
        "instructions": "1. Toast breadcrumbs in a dry skillet until golden and crispy, then set aside.\n2. Heat olive oil in a skillet and add garlic and anchovy fillets.\n3. Stir until anchovies dissolve into the oil.\n4. Add red pepper flakes and chopped parsley.\n5. Cook spaghetti in salted boiling water until al dente.\n6. Drain and toss the pasta in the anchovy oil.\n7. Serve topped with a generous coating of toasted breadcrumbs.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Anchovy fillets", 8.0, "pieces"),
            ("Breadcrumbs", 80.0, "g"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Red pepper flakes", 0.5, "tsp"),
            ("Fresh parsley", 3.0, "tbsp"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
        ],
    },
    {
        "title": "Patate al Forno",
        "description": "Italian oven-roasted potatoes with rosemary and garlic. Crispy outside, fluffy inside, and impossibly fragrant.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 45,
        "servings": 4,
        "tags": ["vegan", "gluten-free", "budget"],
        "instructions": "1. Preheat oven to 200 degrees Celsius.\n2. Peel potatoes and cut into wedges.\n3. Toss with olive oil, minced garlic, rosemary, salt, and pepper.\n4. Spread in a single layer on a baking sheet.\n5. Roast for 40-45 minutes, turning halfway, until golden and crispy.\n6. Serve hot as a side dish.",
        "ingredients": [
            ("Potatoes", 1.0, "kg"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Fresh rosemary", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Fave e Cicoria",
        "description": "Pureed fava beans served alongside sauteed wild chicory greens. A staple of Puglian cucina povera.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegan", "gluten-free", "budget", "high-protein"],
        "instructions": "1. Rinse dried split fava beans and place in a pot with cold water.\n2. Bring to a boil, skim off foam, and simmer for 25 minutes until very soft.\n3. Stir vigorously until the beans become a creamy puree, adding salt to taste.\n4. Meanwhile, blanch chicory or dandelion greens in salted water for 5 minutes.\n5. Drain greens and sauté them in olive oil with garlic until tender.\n6. Spoon the fava puree onto plates, place the greens alongside.\n7. Drizzle with extra virgin olive oil and serve.",
        "ingredients": [
            ("Dried split fava beans", 300.0, "g"),
            ("Chicory or dandelion greens", 500.0, "g"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Melanzane alla Parmigiana",
        "description": "Layers of fried eggplant, tomato sauce, mozzarella, and parmesan baked until bubbly. Southern Italian comfort at its peak.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 45,
        "servings": 6,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Slice eggplants lengthwise, salt them, and let drain for 30 minutes.\n2. Pat eggplant dry and fry in olive oil until golden, drain on paper towels.\n3. Prepare a simple tomato sauce with crushed tomatoes, garlic, basil, and salt.\n4. Spread a thin layer of sauce on the bottom of a baking dish.\n5. Layer fried eggplant, sauce, mozzarella slices, parmesan, and basil.\n6. Repeat layers until all ingredients are used.\n7. Top with remaining sauce, mozzarella, and parmesan.\n8. Bake at 180 degrees Celsius for 35 minutes until golden and bubbling.",
        "ingredients": [
            ("Eggplants", 3.0, "pieces"),
            ("Canned crushed tomatoes", 600.0, "g"),
            ("Mozzarella", 300.0, "g"),
            ("Parmesan cheese", 100.0, "g"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh basil leaves", 15.0, "pieces"),
            ("Extra virgin olive oil", 120.0, "ml"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Risotto al Limone",
        "description": "A bright, citrusy lemon risotto from the Amalfi Coast. Refreshing and elegant with just a handful of ingredients.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget"],
        "instructions": "1. Heat broth in a saucepan and keep at a gentle simmer.\n2. Sauté diced onion in butter until translucent.\n3. Add rice and toast for 2 minutes.\n4. Begin adding broth one ladle at a time, stirring frequently.\n5. Continue for about 18 minutes until rice is creamy and al dente.\n6. Remove from heat and stir in lemon zest, lemon juice, butter, and parmesan.\n7. Season with salt and serve garnished with lemon zest.",
        "ingredients": [
            ("Arborio rice", 320.0, "g"),
            ("Vegetable broth", 1.0, "l"),
            ("Lemons", 2.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Butter", 50.0, "g"),
            ("Parmesan cheese", 80.0, "g"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Bagna Cauda",
        "description": "A Piedmontese warm dip of garlic, anchovies, and olive oil served with raw vegetables for dunking.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["gluten-free", "budget"],
        "instructions": "1. Peel garlic cloves and slice thinly.\n2. Place garlic in a small saucepan with milk and simmer gently for 10 minutes until very soft.\n3. Drain the garlic and return it to the pan.\n4. Add anchovy fillets and olive oil, mashing everything together over low heat.\n5. Cook gently for 10 minutes, stirring, until it becomes a smooth, warm dip.\n6. Prepare raw vegetables: cardoons, peppers, celery, and carrots cut into sticks.\n7. Serve the warm bagna cauda in a fondue pot or small dish with vegetables for dipping.",
        "ingredients": [
            ("Garlic cloves", 8.0, "pieces"),
            ("Anchovy fillets", 8.0, "pieces"),
            ("Extra virgin olive oil", 120.0, "ml"),
            ("Milk", 120.0, "ml"),
            ("Bell peppers", 2.0, "pieces"),
            ("Celery stalks", 3.0, "pieces"),
            ("Carrots", 3.0, "pieces"),
        ],
    },
    {
        "title": "Frisella con Pomodori",
        "description": "Twice-baked Puglian bread rounds soaked and topped with juicy tomatoes, oregano, and olive oil. A summer staple.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegan", "budget", "quick"],
        "instructions": "1. Briefly dip friselle in cold water until softened but still slightly firm.\n2. Dice ripe tomatoes and season with salt, oregano, and olive oil.\n3. Let tomatoes rest for 5 minutes to release their juices.\n4. Place soaked friselle on a platter.\n5. Spoon the tomato mixture generously on top.\n6. Drizzle with extra olive oil and serve immediately.",
        "ingredients": [
            ("Friselle bread rounds", 4.0, "pieces"),
            ("Ripe tomatoes", 4.0, "pieces"),
            ("Dried oregano", 1.0, "tsp"),
            ("Extra virgin olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Spaghetti al Tonno",
        "description": "A quick pantry pasta with canned tuna, tomatoes, and olives. A weeknight staple across Italy.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "tags": ["budget", "pasta", "quick", "high-protein"],
        "instructions": "1. Heat olive oil in a skillet and sauté garlic until fragrant.\n2. Add canned tomatoes and simmer for 10 minutes.\n3. Stir in drained tuna, breaking it up slightly, and add olives and capers.\n4. Cook for 5 more minutes.\n5. Cook spaghetti in salted boiling water until al dente.\n6. Drain and toss pasta with the tuna sauce.\n7. Garnish with fresh parsley and serve.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Canned tuna in olive oil", 240.0, "g"),
            ("Canned crushed tomatoes", 400.0, "g"),
            ("Black olives", 50.0, "g"),
            ("Capers", 1.0, "tbsp"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh parsley", 2.0, "tbsp"),
            ("Extra virgin olive oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Verdure Grigliate",
        "description": "Italian grilled mixed vegetables marinated in olive oil, garlic, and herbs. A versatile side dish or antipasto.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Slice zucchini, eggplant, and bell peppers into even pieces.\n2. Brush vegetables with olive oil and season with salt.\n3. Grill or use a grill pan on high heat, cooking each side for 3-4 minutes.\n4. Arrange grilled vegetables on a platter.\n5. Whisk together olive oil, garlic, oregano, and salt for the dressing.\n6. Drizzle dressing over the warm vegetables and let marinate for 10 minutes.\n7. Serve at room temperature.",
        "ingredients": [
            ("Zucchini", 2.0, "pieces"),
            ("Eggplant", 1.0, "pieces"),
            ("Bell peppers", 2.0, "pieces"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Dried oregano", 1.0, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pesto di Pomodori Secchi",
        "description": "A Sicilian sun-dried tomato pesto with almonds and basil. Intense, savory, and perfect tossed with pasta.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 12,
        "servings": 4,
        "tags": ["vegan", "budget", "pasta", "quick"],
        "instructions": "1. Blend sun-dried tomatoes, almonds, garlic, and basil in a food processor.\n2. Pulse until coarsely chopped.\n3. With the processor running, drizzle in olive oil until a rough paste forms.\n4. Season with salt and pepper.\n5. Cook your choice of pasta in salted boiling water until al dente.\n6. Toss drained pasta with the sun-dried tomato pesto and a splash of pasta water.\n7. Serve with fresh basil on top.",
        "ingredients": [
            ("Pasta of choice", 400.0, "g"),
            ("Sun-dried tomatoes", 120.0, "g"),
            ("Almonds", 40.0, "g"),
            ("Garlic clove", 1.0, "pieces"),
            ("Fresh basil", 15.0, "g"),
            ("Extra virgin olive oil", 60.0, "ml"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Zucchine alla Scapece",
        "description": "Fried zucchini marinated in vinegar, garlic, and mint. A Neapolitan antipasto that improves the longer it sits.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegan", "gluten-free", "budget"],
        "instructions": "1. Slice zucchini into thin rounds.\n2. Fry zucchini slices in olive oil until golden on both sides.\n3. Drain on paper towels and layer on a serving plate.\n4. While still hot, sprinkle with sliced garlic and torn mint leaves.\n5. Drizzle with white wine vinegar.\n6. Let marinate for at least 30 minutes before serving at room temperature.",
        "ingredients": [
            ("Zucchini", 4.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Fresh mint leaves", 10.0, "pieces"),
            ("White wine vinegar", 3.0, "tbsp"),
            ("Extra virgin olive oil", 80.0, "ml"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Ribollita Bianca",
        "description": "A white Tuscan bean soup without tomatoes. Creamy white beans, cavolo nero, and bread for pure rustic simplicity.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 45,
        "servings": 6,
        "tags": ["vegan", "budget", "soup", "one-pot"],
        "instructions": "1. Heat olive oil and sauté diced onion, carrot, and celery until soft.\n2. Add half the cannellini beans and all the broth, bring to a simmer.\n3. Puree the remaining beans with a splash of broth until smooth and add to the pot.\n4. Add chopped cavolo nero and simmer for 20 minutes.\n5. Tear stale bread into pieces and stir into the soup.\n6. Cook for another 10 minutes until thick and porridge-like.\n7. Drizzle with olive oil and season with salt and pepper before serving.",
        "ingredients": [
            ("Canned cannellini beans", 800.0, "g"),
            ("Cavolo nero or kale", 300.0, "g"),
            ("Day-old bread", 200.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Celery stalk", 1.0, "pieces"),
            ("Vegetable broth", 750.0, "ml"),
            ("Extra virgin olive oil", 4.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Pasta alla Amatriciana",
        "description": "A spicy tomato and guanciale sauce from Amatrice. One of Rome's four iconic pasta dishes.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["budget", "pasta"],
        "instructions": "1. Cut guanciale into small strips.\n2. Cook guanciale in a dry skillet over medium heat until crispy and fat is rendered.\n3. Remove guanciale and pour off most of the fat, leaving 2 tablespoons.\n4. Add red pepper flakes to the fat, then pour in crushed tomatoes.\n5. Simmer the sauce for 15 minutes until thickened.\n6. Return guanciale to the sauce.\n7. Cook bucatini in salted boiling water until al dente.\n8. Toss pasta with the sauce and serve topped with grated pecorino.",
        "ingredients": [
            ("Bucatini", 400.0, "g"),
            ("Guanciale", 150.0, "g"),
            ("Canned crushed tomatoes", 400.0, "g"),
            ("Pecorino romano", 80.0, "g"),
            ("Red pepper flakes", 0.5, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
]
