AFRICAN_RECIPES = [
    # === WEST AFRICAN RECIPES ===
    {
        "title": "Jollof Rice",
        "description": "A beloved West African one-pot rice dish cooked in a rich, spiced tomato sauce. A staple at celebrations across Nigeria and Ghana.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 45,
        "servings": 6,
        "tags": ["one-pot", "budget", "gluten-free"],
        "instructions": "1. Blend tomatoes, red bell peppers, and scotch bonnet pepper into a smooth paste.\n2. Heat vegetable oil in a large pot and sauté diced onions until translucent.\n3. Pour in the blended tomato mixture and fry on medium heat for 20 minutes, stirring occasionally.\n4. Add tomato paste, thyme, curry powder, and bay leaves, then cook for another 5 minutes.\n5. Stir in the washed long-grain rice and mix until evenly coated.\n6. Pour in chicken stock, season with salt, and bring to a boil.\n7. Reduce heat to low, cover tightly with foil and a lid, and steam for 30 minutes.\n8. Fluff with a fork, remove bay leaves, and serve hot.",
        "ingredients": [
            ("Long-grain rice", 3.0, "cups"),
            ("Tomatoes", 6.0, "pieces"),
            ("Red bell pepper", 2.0, "pieces"),
            ("Scotch bonnet pepper", 1.0, "pieces"),
            ("Onion", 2.0, "pieces"),
            ("Tomato paste", 3.0, "tbsp"),
            ("Vegetable oil", 0.33, "cups"),
            ("Chicken stock", 3.0, "cups"),
            ("Thyme", 1.0, "tsp"),
            ("Curry powder", 1.0, "tsp"),
        ],
    },
    {
        "title": "Egusi Soup",
        "description": "A thick, hearty Nigerian soup made from ground melon seeds, leafy greens, and palm oil. Traditionally served with fufu or pounded yam.",
        "difficulty": "medium",
        "prep_time": 25,
        "cook_time": 40,
        "servings": 6,
        "tags": ["stew", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Grind the egusi (melon seeds) into a fine powder.\n2. Heat palm oil in a large pot and sauté chopped onions until soft.\n3. Add the locust beans and crayfish, then stir for 2 minutes.\n4. Pour in blended tomatoes and scotch bonnet, cook for 15 minutes.\n5. Mix egusi powder with a small amount of water to form a paste, then stir into the pot.\n6. Simmer on low heat for 15 minutes, stirring occasionally to prevent sticking.\n7. Add chopped spinach and season with salt and bouillon.\n8. Cook for 5 more minutes until the greens are wilted, then serve with fufu.",
        "ingredients": [
            ("Ground egusi seeds", 2.0, "cups"),
            ("Spinach", 300.0, "g"),
            ("Palm oil", 0.33, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Scotch bonnet pepper", 1.0, "pieces"),
            ("Crayfish", 2.0, "tbsp"),
            ("Locust beans", 1.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Groundnut Soup",
        "description": "A creamy, nutty West African soup made with peanut butter, tomatoes, and chicken. Popular across Ghana, Nigeria, and Mali.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 50,
        "servings": 6,
        "tags": ["stew", "high-protein", "gluten-free", "budget"],
        "instructions": "1. Season chicken pieces with salt, pepper, and onion, then boil until tender and set broth aside.\n2. Heat oil in a large pot and fry onions until golden.\n3. Add blended tomatoes and cook down for 15 minutes.\n4. Stir in the peanut butter and mix until fully dissolved.\n5. Pour in the reserved chicken broth and stir well.\n6. Add the cooked chicken pieces back to the pot.\n7. Simmer on low heat for 20 minutes, stirring occasionally to prevent the peanut butter from settling.\n8. Season with salt and serve hot over rice or with fufu.",
        "ingredients": [
            ("Chicken pieces", 500.0, "g"),
            ("Natural peanut butter", 1.0, "cups"),
            ("Tomatoes", 4.0, "pieces"),
            ("Onion", 2.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Black pepper", 0.5, "tsp"),
            ("Water", 4.0, "cups"),
        ],
    },
    {
        "title": "Fufu",
        "description": "A smooth, stretchy West African staple made from cassava and plantain, pounded until elastic. The classic accompaniment for soups and stews.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Peel the cassava and plantain, then cut into small chunks.\n2. Boil the cassava and plantain in water until completely soft and tender.\n3. Drain most of the water, reserving some for pounding.\n4. Transfer to a large mortar and pound with a pestle, adding small amounts of water as needed.\n5. Continue pounding until the mixture is smooth, stretchy, and free of lumps.\n6. Shape into round balls using wet hands.\n7. Serve immediately alongside your favorite African soup.",
        "ingredients": [
            ("Cassava", 500.0, "g"),
            ("Green plantain", 2.0, "pieces"),
            ("Water", 4.0, "cups"),
        ],
    },
    {
        "title": "Suya",
        "description": "Nigerian street food of spiced, grilled beef skewers coated in a fiery peanut spice blend called yaji. Smoky, nutty, and intensely flavorful.",
        "difficulty": "easy",
        "prep_time": 30,
        "cook_time": 15,
        "servings": 4,
        "tags": ["high-protein", "gluten-free", "spicy", "budget"],
        "instructions": "1. Slice beef into thin strips against the grain.\n2. Mix ground peanuts, cayenne pepper, paprika, onion powder, garlic powder, ginger, and salt to make the yaji spice.\n3. Coat the beef strips generously in vegetable oil, then roll in the yaji spice mix.\n4. Thread the seasoned beef onto wooden skewers.\n5. Grill over high heat or under a broiler for 5-7 minutes per side until charred.\n6. Sprinkle with extra yaji spice and serve with sliced onions and tomatoes.",
        "ingredients": [
            ("Beef sirloin", 500.0, "g"),
            ("Ground roasted peanuts", 0.5, "cups"),
            ("Cayenne pepper", 1.0, "tbsp"),
            ("Paprika", 1.0, "tbsp"),
            ("Onion powder", 1.0, "tsp"),
            ("Garlic powder", 1.0, "tsp"),
            ("Ground ginger", 0.5, "tsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Waakye",
        "description": "A Ghanaian staple of rice and black-eyed peas cooked together with dried millet leaves that give it a distinctive reddish-brown color.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 45,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "one-pot", "high-protein"],
        "instructions": "1. Soak black-eyed peas overnight, then drain and rinse.\n2. Boil the peas in a large pot of water for 20 minutes until half cooked.\n3. Add washed rice and dried millet leaves (or baking soda for color) to the pot.\n4. Season with salt and stir once.\n5. Cook on medium heat until the water is absorbed and rice is tender, about 25 minutes.\n6. Remove the millet leaves, fluff with a fork, and serve with shito (pepper sauce).",
        "ingredients": [
            ("Long-grain rice", 2.0, "cups"),
            ("Black-eyed peas", 1.0, "cups"),
            ("Dried millet leaves", 3.0, "pieces"),
            ("Salt", 1.0, "tsp"),
            ("Water", 5.0, "cups"),
        ],
    },
    {
        "title": "Pepper Soup",
        "description": "A spicy, aromatic West African broth loaded with traditional spices and tender goat meat. A favorite comfort food and cold remedy.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 60,
        "servings": 4,
        "tags": ["spicy", "gluten-free", "high-protein", "budget", "stew"],
        "instructions": "1. Wash goat meat thoroughly, place in a pot, and add diced onion and salt.\n2. Add enough water to cover the meat and boil for 30 minutes.\n3. Blend scotch bonnet peppers with the pepper soup spice mix.\n4. Add the blended pepper mixture to the pot and stir well.\n5. Add whole basil leaves (scent leaves) and continue cooking for 20 minutes.\n6. Adjust seasoning with salt and add more water if a thinner broth is desired.\n7. Simmer for 10 more minutes and serve hot in deep bowls.",
        "ingredients": [
            ("Goat meat", 500.0, "g"),
            ("Scotch bonnet pepper", 3.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Pepper soup spice mix", 2.0, "tbsp"),
            ("Scent leaves", 0.25, "cups"),
            ("Salt", 1.0, "to taste"),
            ("Water", 6.0, "cups"),
        ],
    },
    {
        "title": "Thieboudienne",
        "description": "Senegal's national dish of seasoned fish, rice, and vegetables slow-cooked in a rich tomato sauce. Also known as ceebu jen.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 60,
        "servings": 6,
        "tags": ["one-pot", "high-protein", "budget", "gluten-free"],
        "instructions": "1. Make a stuffing paste from parsley, garlic, and scotch bonnet, then stuff into slits cut in the fish.\n2. Fry the stuffed fish in vegetable oil until golden on both sides, then set aside.\n3. In the same oil, sauté onions and add tomato paste, cooking for 5 minutes.\n4. Add water, cassava, carrot, cabbage, and eggplant, then season with salt and pepper.\n5. Simmer vegetables for 20 minutes until tender, then remove and keep warm.\n6. Add broken rice to the pot liquid, stir, and cook covered on low heat for 25 minutes.\n7. Arrange the rice on a platter, top with fish and vegetables.\n8. Serve with lime wedges and hot sauce on the side.",
        "ingredients": [
            ("White fish fillets", 500.0, "g"),
            ("Broken rice", 3.0, "cups"),
            ("Tomato paste", 3.0, "tbsp"),
            ("Cassava", 200.0, "g"),
            ("Carrot", 2.0, "pieces"),
            ("Cabbage", 0.25, "pieces"),
            ("Eggplant", 1.0, "pieces"),
            ("Onion", 2.0, "pieces"),
            ("Garlic", 4.0, "pieces"),
            ("Vegetable oil", 0.25, "cups"),
        ],
    },
    {
        "title": "Mafe",
        "description": "A rich Senegalese peanut stew with tender beef and root vegetables simmered in a thick, savory groundnut sauce.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 60,
        "servings": 6,
        "tags": ["stew", "high-protein", "budget", "gluten-free"],
        "instructions": "1. Cut beef into cubes and season with salt and pepper.\n2. Brown the beef in oil in a large pot, then remove and set aside.\n3. Sauté onions and garlic in the same pot until fragrant.\n4. Add tomato paste and cook for 3 minutes.\n5. Stir in peanut butter and slowly add water, mixing until smooth.\n6. Return beef to the pot, add cubed sweet potato and carrot.\n7. Simmer covered for 45 minutes until meat is tender and vegetables are cooked.\n8. Season to taste and serve over steamed rice.",
        "ingredients": [
            ("Beef stew meat", 500.0, "g"),
            ("Natural peanut butter", 0.75, "cups"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Sweet potato", 2.0, "pieces"),
            ("Carrot", 2.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Okra Soup",
        "description": "A slimy, flavorful West African soup made with fresh okra, palm oil, and dried fish. A classic pairing with garri or pounded yam.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["stew", "gluten-free", "budget", "high-protein"],
        "instructions": "1. Wash and chop okra into thin rounds.\n2. Boil assorted meat with onion and salt until tender, reserve the broth.\n3. Heat palm oil in a pot and sauté chopped onions.\n4. Add the meat broth and bring to a simmer.\n5. Stir in the chopped okra and dried fish.\n6. Add crayfish and season with salt and pepper.\n7. Cook on low heat for 15 minutes, stirring frequently.\n8. Serve hot with fufu or pounded yam.",
        "ingredients": [
            ("Fresh okra", 300.0, "g"),
            ("Beef pieces", 300.0, "g"),
            ("Dried fish", 100.0, "g"),
            ("Palm oil", 3.0, "tbsp"),
            ("Onion", 1.0, "pieces"),
            ("Crayfish", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Water", 3.0, "cups"),
        ],
    },
    {
        "title": "Kelewele",
        "description": "Ghanaian spiced fried plantain cubes seasoned with ginger, cayenne, and cloves. A popular street snack bursting with flavor.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 3,
        "tags": ["vegetarian", "vegan", "gluten-free", "quick", "spicy", "budget"],
        "instructions": "1. Peel ripe plantains and cut into bite-sized cubes.\n2. Grate fresh ginger and mix with cayenne pepper, ground cloves, and salt.\n3. Toss the plantain cubes in the spice mixture until well coated.\n4. Let marinate for 10 minutes.\n5. Heat vegetable oil in a deep pan to 350F.\n6. Fry plantain cubes in batches until golden brown and crispy, about 3-4 minutes per batch.\n7. Drain on paper towels and serve hot.",
        "ingredients": [
            ("Ripe plantain", 3.0, "pieces"),
            ("Fresh ginger", 1.0, "tbsp"),
            ("Cayenne pepper", 0.5, "tsp"),
            ("Ground cloves", 0.25, "tsp"),
            ("Vegetable oil", 1.0, "cups"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Nigerian Beans Porridge",
        "description": "A thick, hearty one-pot dish of brown beans cooked with palm oil, peppers, and onions. A protein-packed Nigerian comfort food.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 60,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "one-pot", "high-protein", "budget", "gluten-free"],
        "instructions": "1. Soak beans overnight, then rinse and drain.\n2. Place beans in a pot, cover with water, and bring to a boil.\n3. Cook for 30 minutes until beans begin to soften.\n4. Add diced onion, palm oil, and blended scotch bonnet pepper.\n5. Continue cooking until beans are very soft and the liquid thickens.\n6. Season with salt and stir well.\n7. Simmer for 10 more minutes until the porridge is thick and creamy.",
        "ingredients": [
            ("Brown beans", 2.0, "cups"),
            ("Palm oil", 3.0, "tbsp"),
            ("Onion", 1.0, "pieces"),
            ("Scotch bonnet pepper", 1.0, "pieces"),
            ("Salt", 1.0, "to taste"),
            ("Water", 5.0, "cups"),
        ],
    },
    {
        "title": "Yam Pottage (Asaro)",
        "description": "A comforting Nigerian dish of mashed yam cooked in a peppery tomato sauce until thick and creamy. Also called yam porridge.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "one-pot"],
        "instructions": "1. Peel the yam and cut into medium cubes.\n2. Boil yam in salted water until fork-tender, about 15 minutes.\n3. While yam boils, blend tomatoes, scotch bonnet, and onion into a paste.\n4. Add palm oil and the blended tomato mixture to the yam pot.\n5. Stir and mash some of the yam pieces to thicken the porridge.\n6. Season with salt and cook on low heat for 10 minutes, stirring frequently.\n7. Add spinach leaves in the last 2 minutes of cooking.",
        "ingredients": [
            ("White yam", 500.0, "g"),
            ("Tomatoes", 3.0, "pieces"),
            ("Scotch bonnet pepper", 1.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Palm oil", 3.0, "tbsp"),
            ("Spinach", 100.0, "g"),
            ("Salt", 1.0, "to taste"),
            ("Water", 3.0, "cups"),
        ],
    },
    {
        "title": "Akara (Bean Fritters)",
        "description": "Crispy Nigerian fritters made from blended black-eyed peas, peppers, and onions. A beloved breakfast street food across West Africa.",
        "difficulty": "medium",
        "prep_time": 30,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "high-protein", "budget", "quick"],
        "instructions": "1. Soak black-eyed peas for 2 hours, then rub to remove the skins and rinse.\n2. Blend the peeled beans with onion and scotch bonnet until smooth but thick.\n3. Transfer to a bowl and beat vigorously with a wooden spoon to incorporate air.\n4. Season with salt and mix well.\n5. Heat vegetable oil in a deep pot to 350F.\n6. Drop spoonfuls of batter into the hot oil using two spoons.\n7. Fry until golden brown on all sides, about 3-4 minutes.\n8. Drain on paper towels and serve hot.",
        "ingredients": [
            ("Black-eyed peas", 2.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Scotch bonnet pepper", 1.0, "pieces"),
            ("Salt", 1.0, "tsp"),
            ("Vegetable oil", 2.0, "cups"),
        ],
    },
    {
        "title": "Ghanaian Red Red",
        "description": "A hearty Ghanaian black-eyed pea stew cooked in palm oil and tomatoes, served with fried ripe plantain. Named for its deep red color.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein", "one-pot"],
        "instructions": "1. Soak black-eyed peas overnight, then boil until tender and drain.\n2. Heat palm oil in a pot and sauté diced onions until soft.\n3. Add blended tomatoes and tomato paste, cook for 15 minutes until oil floats on top.\n4. Add the cooked beans and stir to combine.\n5. Season with salt and cayenne pepper, simmer for 10 minutes.\n6. Meanwhile, slice ripe plantains and fry in oil until golden on both sides.\n7. Serve the stewed beans alongside the fried plantain.",
        "ingredients": [
            ("Black-eyed peas", 2.0, "cups"),
            ("Ripe plantain", 2.0, "pieces"),
            ("Palm oil", 0.25, "cups"),
            ("Tomatoes", 4.0, "pieces"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Onion", 1.0, "pieces"),
            ("Cayenne pepper", 0.5, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    # === EAST AFRICAN RECIPES ===
    {
        "title": "Injera",
        "description": "A spongy, sour Ethiopian flatbread made from teff flour. The foundation of Ethiopian cuisine, used as both plate and utensil.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "budget"],
        "instructions": "1. Mix teff flour with water in a large bowl to form a thin batter.\n2. Cover and let ferment at room temperature for 2-3 days until bubbly and slightly sour.\n3. Stir the fermented batter and add a pinch of salt.\n4. Heat a large non-stick skillet over medium heat.\n5. Pour batter in a thin, even spiral from the outside in, like a crepe.\n6. Cover and cook for 2-3 minutes until bubbles form across the surface and edges lift.\n7. Do not flip. Remove with a spatula and lay flat to cool.\n8. Stack cooked injera and serve with stews and curries.",
        "ingredients": [
            ("Teff flour", 2.0, "cups"),
            ("Water", 3.0, "cups"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Shiro Wot",
        "description": "A smooth, creamy Ethiopian stew made from roasted chickpea flour simmered with berbere spice and garlic. A fasting-day staple.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Dice onions finely and cook in a dry pot until softened, stirring constantly.\n2. Add vegetable oil and minced garlic, cook for 2 minutes.\n3. Stir in berbere spice and cook until fragrant.\n4. Slowly add water while stirring to prevent lumps.\n5. Gradually whisk in the shiro (chickpea flour) while stirring continuously.\n6. Simmer on low heat for 15 minutes, stirring often to prevent sticking.\n7. Season with salt and serve on injera.",
        "ingredients": [
            ("Shiro powder (chickpea flour)", 1.0, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Garlic", 4.0, "pieces"),
            ("Berbere spice", 2.0, "tbsp"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Water", 3.0, "cups"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Misir Wot",
        "description": "A deeply spiced Ethiopian red lentil stew simmered with berbere, onions, and garlic. Rich, warming, and perfect for any day.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein", "stew", "spicy"],
        "instructions": "1. Rinse red lentils thoroughly under running water.\n2. Finely dice onions and cook in a dry pot over medium heat until deeply browned.\n3. Add vegetable oil, minced garlic, and grated ginger, cook for 2 minutes.\n4. Stir in berbere spice and tomato paste, cook for 1 minute.\n5. Add the rinsed lentils and water, stir well.\n6. Bring to a boil, then reduce to a simmer.\n7. Cook for 25 minutes, stirring occasionally, until lentils are soft and stew is thick.\n8. Season with salt and serve over injera.",
        "ingredients": [
            ("Red lentils", 1.5, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Garlic", 4.0, "pieces"),
            ("Fresh ginger", 1.0, "tbsp"),
            ("Berbere spice", 2.0, "tbsp"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Water", 3.5, "cups"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Ugali",
        "description": "A firm East African cornmeal porridge that is the daily staple across Kenya, Tanzania, and Uganda. Simple, filling, and versatile.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Bring water to a rolling boil in a heavy-bottomed pot.\n2. Add a handful of cornmeal while stirring to prevent lumps.\n3. Gradually add the remaining cornmeal, stirring vigorously with a wooden spoon.\n4. Continue stirring and pressing out lumps for 5-8 minutes.\n5. The ugali is ready when it pulls away from the sides of the pot cleanly.\n6. Wet a bowl, pack the ugali in, and flip onto a plate.\n7. Serve alongside sukuma wiki, stews, or grilled meat.",
        "ingredients": [
            ("White cornmeal", 2.0, "cups"),
            ("Water", 3.0, "cups"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Sukuma Wiki",
        "description": "Kenya's most popular everyday vegetable dish of sauteed collard greens with onions and tomatoes. The name means 'stretch the week' in Swahili.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Wash collard greens thoroughly and slice into thin strips.\n2. Dice the onion and slice the tomatoes.\n3. Heat vegetable oil in a pan and sauté onions until translucent.\n4. Add sliced tomatoes and cook until softened.\n5. Add the sliced collard greens and stir to combine.\n6. Season with salt and pepper, cover, and cook for 8-10 minutes until tender.\n7. Serve immediately alongside ugali.",
        "ingredients": [
            ("Collard greens", 400.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
            ("Black pepper", 0.25, "tsp"),
        ],
    },
    {
        "title": "Pilau",
        "description": "A fragrant Swahili spiced rice dish cooked with whole spices, caramelized onions, and tender beef. East Africa's answer to biryani.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 40,
        "servings": 6,
        "tags": ["one-pot", "high-protein", "budget", "gluten-free"],
        "instructions": "1. Season beef cubes with salt and pilau masala, set aside for 15 minutes.\n2. Heat oil in a heavy pot and fry sliced onions until dark brown and caramelized.\n3. Add the seasoned beef and sear on all sides.\n4. Add minced garlic, grated ginger, and whole cumin seeds, stir for 2 minutes.\n5. Pour in enough water to cover the meat and simmer until tender, about 20 minutes.\n6. Add washed basmati rice and enough water to cook the rice.\n7. Cover tightly, reduce heat to very low, and cook for 20 minutes without opening.\n8. Fluff with a fork and serve hot.",
        "ingredients": [
            ("Basmati rice", 2.0, "cups"),
            ("Beef stew meat", 300.0, "g"),
            ("Onion", 3.0, "pieces"),
            ("Garlic", 4.0, "pieces"),
            ("Fresh ginger", 1.0, "tbsp"),
            ("Pilau masala", 2.0, "tbsp"),
            ("Cumin seeds", 1.0, "tsp"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Doro Wot",
        "description": "Ethiopia's iconic slow-cooked chicken stew in a rich berbere and onion sauce with hard-boiled eggs. The crown jewel of Ethiopian cuisine.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 90,
        "servings": 6,
        "tags": ["stew", "high-protein", "gluten-free", "spicy", "budget"],
        "instructions": "1. Score chicken legs and marinate in lemon juice and salt for 30 minutes.\n2. Finely dice 6 large onions and slow-cook in a dry pot, stirring often for 30 minutes until deeply browned.\n3. Add niter kibbeh (spiced butter) and minced garlic, cook for 5 minutes.\n4. Stir in berbere spice and tomato paste, cook for 5 minutes.\n5. Add water and bring to a simmer.\n6. Add the marinated chicken pieces and cook covered for 45 minutes.\n7. Add peeled hard-boiled eggs, pricking them with a fork so they absorb the sauce.\n8. Simmer 10 more minutes, season with salt, and serve on injera.",
        "ingredients": [
            ("Chicken legs", 6.0, "pieces"),
            ("Onion", 6.0, "pieces"),
            ("Berbere spice", 3.0, "tbsp"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Garlic", 6.0, "pieces"),
            ("Butter", 3.0, "tbsp"),
            ("Eggs", 6.0, "pieces"),
            ("Lemon", 1.0, "pieces"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Chapati (East African)",
        "description": "Flaky, layered flatbread popular in Kenya, Tanzania, and Uganda. Made by coiling oiled dough for distinctive layers.",
        "difficulty": "medium",
        "prep_time": 30,
        "cook_time": 20,
        "servings": 6,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Mix flour and salt in a bowl, then add warm water gradually to form a soft dough.\n2. Knead for 10 minutes until smooth and elastic.\n3. Divide into 6 equal balls and let rest for 15 minutes.\n4. Roll each ball into a thin circle, brush with oil, then roll up like a Swiss roll.\n5. Coil the roll into a spiral, press flat, and roll out again into a circle.\n6. Heat a flat pan over medium heat and cook each chapati for 2 minutes per side.\n7. Brush with oil while cooking until golden brown and flaky on both sides.",
        "ingredients": [
            ("All-purpose flour", 3.0, "cups"),
            ("Warm water", 1.0, "cups"),
            ("Vegetable oil", 0.25, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Githeri",
        "description": "A rustic Kenyan dish of boiled maize and beans, often sauteed with vegetables. Simple, nutritious, and deeply satisfying.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 60,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein", "one-pot"],
        "instructions": "1. Soak dried maize kernels and kidney beans overnight.\n2. Boil together in a large pot of water for 45 minutes until tender.\n3. Drain excess water, reserving some.\n4. In a separate pan, heat oil and sauté diced onion and tomatoes.\n5. Add the boiled maize and beans to the pan.\n6. Season with salt and pepper, stir well.\n7. Cook together for 10 minutes, adding reserved water if needed.",
        "ingredients": [
            ("Dried maize kernels", 1.5, "cups"),
            ("Kidney beans", 1.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
            ("Black pepper", 0.25, "tsp"),
        ],
    },
    {
        "title": "Matoke",
        "description": "A Ugandan staple of green bananas steamed and mashed in banana leaves, then served with a savory groundnut or meat sauce.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Peel green bananas and place in salted water to prevent browning.\n2. Wrap the bananas tightly in banana leaves or foil.\n3. Place in a steamer pot with water in the bottom.\n4. Steam for 30-40 minutes until completely soft.\n5. Unwrap and mash the bananas until smooth.\n6. Meanwhile, prepare a sauce by sauteing onions, tomatoes, and garlic in oil.\n7. Season with salt and pepper, serve the mashed matoke topped with the sauce.",
        "ingredients": [
            ("Green bananas", 6.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("Garlic", 2.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Nyama Choma",
        "description": "East Africa's beloved grilled meat, simply seasoned with salt, pepper, and lime. A Kenyan barbecue tradition best enjoyed with friends.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["high-protein", "gluten-free", "budget"],
        "instructions": "1. Cut goat meat into large chunks, keeping some on the bone for flavor.\n2. Season generously with salt, black pepper, and lime juice.\n3. Let marinate for at least 30 minutes.\n4. Prepare a charcoal grill to medium-high heat.\n5. Grill the meat pieces, turning occasionally, for 25-30 minutes until charred on the outside and cooked through.\n6. Serve hot with ugali, kachumbari (tomato-onion salad), and a squeeze of lime.",
        "ingredients": [
            ("Goat meat", 600.0, "g"),
            ("Lime", 2.0, "pieces"),
            ("Salt", 1.0, "tsp"),
            ("Black pepper", 1.0, "tsp"),
            ("Vegetable oil", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Kachumbari",
        "description": "A fresh East African tomato and onion salad with chili and lime. A bright, tangy condiment served alongside grilled meats.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "quick", "budget"],
        "instructions": "1. Dice tomatoes into small cubes and place in a bowl.\n2. Slice onion into very thin rings and add to the tomatoes.\n3. Finely chop the chili pepper and cilantro.\n4. Add the chili and cilantro to the bowl.\n5. Squeeze lime juice over everything.\n6. Season with salt and toss gently to combine.\n7. Let sit for 5 minutes before serving to allow flavors to meld.",
        "ingredients": [
            ("Tomatoes", 4.0, "pieces"),
            ("Red onion", 1.0, "pieces"),
            ("Hot chili pepper", 1.0, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Lime", 1.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    # === NORTH AFRICAN RECIPES ===
    {
        "title": "Shakshuka",
        "description": "Eggs poached in a spiced tomato and pepper sauce, a beloved breakfast across North Africa and the Middle East. Simple, bold, and satisfying.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "quick", "budget", "one-pot"],
        "instructions": "1. Heat olive oil in a large skillet and sauté diced onion until soft.\n2. Add minced garlic and diced bell pepper, cook for 3 minutes.\n3. Stir in cumin, paprika, and cayenne pepper.\n4. Add crushed tomatoes and season with salt and pepper.\n5. Simmer the sauce for 10 minutes until thickened.\n6. Make 4 wells in the sauce and crack an egg into each.\n7. Cover and cook on low heat for 5-7 minutes until egg whites are set but yolks are runny.\n8. Garnish with fresh cilantro and serve with crusty bread.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Crushed tomatoes", 400.0, "g"),
            ("Bell pepper", 1.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Cumin", 1.0, "tsp"),
            ("Paprika", 1.0, "tsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Vegetable Couscous",
        "description": "A North African staple of fluffy steamed couscous topped with a fragrant vegetable stew seasoned with cumin and coriander.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget", "quick"],
        "instructions": "1. Place couscous in a bowl, pour over boiling water, cover, and let sit for 5 minutes.\n2. Fluff with a fork and stir in a tablespoon of olive oil.\n3. Heat olive oil in a pan and sauté onion and garlic.\n4. Add diced carrot, zucchini, and chickpeas.\n5. Season with cumin, coriander, turmeric, and salt.\n6. Add tomato paste and a splash of water, simmer for 15 minutes.\n7. Serve the vegetable stew over the fluffed couscous.",
        "ingredients": [
            ("Couscous", 1.5, "cups"),
            ("Chickpeas", 1.0, "cups"),
            ("Carrot", 2.0, "pieces"),
            ("Zucchini", 1.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Cumin", 1.0, "tsp"),
            ("Ground coriander", 1.0, "tsp"),
        ],
    },
    {
        "title": "Harissa Chicken",
        "description": "Chicken thighs marinated in fiery North African harissa paste, then roasted until crispy-skinned and juicy inside.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["high-protein", "gluten-free", "spicy", "budget"],
        "instructions": "1. Mix harissa paste with olive oil, minced garlic, lemon juice, cumin, and salt.\n2. Score the chicken thighs and coat thoroughly with the harissa marinade.\n3. Let marinate for at least 30 minutes.\n4. Preheat oven to 200C (400F).\n5. Place chicken on a baking tray and roast for 35-40 minutes until skin is crispy.\n6. Let rest for 5 minutes before serving with couscous or flatbread.",
        "ingredients": [
            ("Chicken thighs", 6.0, "pieces"),
            ("Harissa paste", 3.0, "tbsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Garlic", 3.0, "pieces"),
            ("Lemon", 1.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Chicken Tagine with Preserved Lemons and Olives",
        "description": "A Moroccan slow-cooked stew of tender chicken with preserved lemons, green olives, and warm spices. Fragrant and deeply complex.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 60,
        "servings": 4,
        "tags": ["stew", "high-protein", "gluten-free", "budget"],
        "instructions": "1. Season chicken pieces with salt, pepper, turmeric, ginger, and saffron.\n2. Heat olive oil in a tagine or heavy pot and brown the chicken on all sides.\n3. Remove chicken and sauté sliced onions until soft and golden.\n4. Add minced garlic and a splash of water, then return the chicken.\n5. Add preserved lemon slices and green olives.\n6. Cover and simmer on low heat for 45 minutes until chicken is very tender.\n7. Garnish with fresh cilantro and serve with bread or couscous.",
        "ingredients": [
            ("Chicken pieces", 600.0, "g"),
            ("Preserved lemon", 1.0, "pieces"),
            ("Green olives", 0.5, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Garlic", 4.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Turmeric", 1.0, "tsp"),
            ("Ground ginger", 1.0, "tsp"),
            ("Fresh cilantro", 0.25, "cups"),
        ],
    },
    {
        "title": "Moroccan Lentil Soup (Harira)",
        "description": "A thick, warming Moroccan soup with lentils, chickpeas, and tomatoes, seasoned with cumin, cinnamon, and fresh herbs. Traditional Ramadan fare.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 45,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "budget", "high-protein", "stew"],
        "instructions": "1. Heat olive oil in a large pot and sauté diced onion and celery.\n2. Add minced garlic, cumin, cinnamon, and turmeric, cook for 1 minute.\n3. Add crushed tomatoes, rinsed lentils, and drained chickpeas.\n4. Pour in water and bring to a boil.\n5. Reduce heat and simmer for 35 minutes until lentils are very soft.\n6. Stir in chopped fresh cilantro and lemon juice.\n7. Season with salt and pepper, serve hot with lemon wedges.",
        "ingredients": [
            ("Green lentils", 1.0, "cups"),
            ("Chickpeas", 0.5, "cups"),
            ("Crushed tomatoes", 400.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Celery", 2.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Cumin", 1.0, "tsp"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Lemon", 1.0, "pieces"),
        ],
    },
    {
        "title": "Ful Medames",
        "description": "Egypt's national breakfast dish of slow-cooked fava beans mashed with garlic, lemon, and olive oil. Earthy, hearty, and ancient.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein", "quick"],
        "instructions": "1. Drain and rinse the canned fava beans.\n2. Place beans in a pot with a little water and heat over medium.\n3. Mash about half the beans with a fork, leaving some whole for texture.\n4. Stir in minced garlic, cumin, and lemon juice.\n5. Drizzle generously with olive oil.\n6. Season with salt and pepper.\n7. Serve in bowls topped with chopped parsley and a drizzle of olive oil.",
        "ingredients": [
            ("Fava beans", 400.0, "g"),
            ("Garlic", 3.0, "pieces"),
            ("Lemon", 1.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Cumin", 1.0, "tsp"),
            ("Fresh parsley", 0.25, "cups"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tunisian Brik",
        "description": "A crispy Tunisian pastry filled with egg, tuna, and capers, deep-fried until golden. A crunchy, savory snack bursting with Mediterranean flavors.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 10,
        "servings": 4,
        "tags": ["high-protein", "quick", "budget"],
        "instructions": "1. Mix drained tuna with chopped parsley, capers, and a squeeze of lemon juice.\n2. Lay out a sheet of brik pastry (or phyllo dough).\n3. Place a spoonful of tuna mixture in the center.\n4. Crack an egg on top of the tuna filling.\n5. Fold the pastry in half to form a triangle, pressing edges to seal.\n6. Deep fry in hot oil for 2-3 minutes per side until golden and crispy.\n7. Drain on paper towels and serve immediately with lemon wedges.",
        "ingredients": [
            ("Brik pastry sheets", 4.0, "pieces"),
            ("Canned tuna", 200.0, "g"),
            ("Eggs", 4.0, "pieces"),
            ("Capers", 2.0, "tbsp"),
            ("Fresh parsley", 0.25, "cups"),
            ("Lemon", 1.0, "pieces"),
            ("Vegetable oil", 2.0, "cups"),
        ],
    },
    {
        "title": "Moroccan Zaalouk",
        "description": "A smoky Moroccan salad of roasted eggplant and tomatoes, seasoned with garlic, cumin, and paprika. Served warm or cold as a dip.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Roast the whole eggplant over an open flame or under a broiler until skin is charred and flesh is soft.\n2. Peel the eggplant and roughly chop the flesh.\n3. In a pan, heat olive oil and sauté minced garlic for 30 seconds.\n4. Add diced tomatoes and cook for 10 minutes until broken down.\n5. Add the chopped eggplant, cumin, paprika, and cayenne.\n6. Mash and stir together, cooking for another 10 minutes.\n7. Season with salt, drizzle with olive oil, and serve with crusty bread.",
        "ingredients": [
            ("Eggplant", 2.0, "pieces"),
            ("Tomatoes", 4.0, "pieces"),
            ("Garlic", 4.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Cumin", 1.0, "tsp"),
            ("Paprika", 1.0, "tsp"),
            ("Cayenne pepper", 0.25, "tsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Algerian Chakchouka",
        "description": "An Algerian variant of shakshuka with roasted peppers, tomatoes, and merguez sausage. Smoky, spicy, and deeply satisfying.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["high-protein", "gluten-free", "spicy", "budget"],
        "instructions": "1. Roast bell peppers over a flame until charred, peel and dice.\n2. Slice merguez sausage into rounds.\n3. Heat olive oil and brown the sausage pieces.\n4. Add diced onion and garlic, sauté until soft.\n5. Add roasted peppers, diced tomatoes, cumin, and paprika.\n6. Simmer for 15 minutes until sauce thickens.\n7. Make wells and crack in the eggs, cover and cook for 5-7 minutes.\n8. Serve from the pan with bread.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Merguez sausage", 200.0, "g"),
            ("Bell pepper", 3.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Cumin", 1.0, "tsp"),
            ("Paprika", 1.0, "tsp"),
        ],
    },
    # === SOUTH AFRICAN RECIPES ===
    {
        "title": "Bobotie",
        "description": "South Africa's national dish of spiced minced meat topped with a savory egg custard, baked until golden. A Cape Malay classic.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 45,
        "servings": 6,
        "tags": ["high-protein", "budget"],
        "instructions": "1. Preheat oven to 180C (350F).\n2. Heat oil and sauté diced onion until golden.\n3. Add minced beef and cook until browned, breaking up lumps.\n4. Stir in curry powder, turmeric, and cumin, cook for 2 minutes.\n5. Add tomato paste, vinegar, and soaked bread (squeezed dry), mix well.\n6. Transfer to a baking dish and smooth the top.\n7. Beat eggs with milk and pour over the meat mixture.\n8. Place bay leaves on top and bake for 30-35 minutes until custard is set and golden.",
        "ingredients": [
            ("Minced beef", 500.0, "g"),
            ("Onion", 2.0, "pieces"),
            ("Eggs", 2.0, "pieces"),
            ("Milk", 0.5, "cups"),
            ("White bread", 2.0, "pieces"),
            ("Curry powder", 2.0, "tbsp"),
            ("Turmeric", 1.0, "tsp"),
            ("Tomato paste", 1.0, "tbsp"),
            ("White vinegar", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Chakalaka",
        "description": "A fiery South African vegetable relish of baked beans, peppers, carrots, and tomatoes. A vibrant braai (barbecue) side dish.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "gluten-free", "spicy", "budget"],
        "instructions": "1. Heat vegetable oil in a large pot and sauté diced onions and garlic.\n2. Add grated carrot and diced bell peppers, cook for 5 minutes.\n3. Add diced tomatoes, curry powder, and cayenne pepper.\n4. Cook for 10 minutes until vegetables are softened.\n5. Stir in baked beans (drained) and mix well.\n6. Season with salt and pepper.\n7. Simmer for 10 minutes and serve warm or at room temperature.",
        "ingredients": [
            ("Baked beans", 400.0, "g"),
            ("Carrot", 2.0, "pieces"),
            ("Bell pepper", 2.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Garlic", 2.0, "pieces"),
            ("Curry powder", 1.0, "tbsp"),
            ("Cayenne pepper", 0.5, "tsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Pap (Mieliepap)",
        "description": "South Africa's staple maize porridge, similar to polenta, served stiff alongside braai meat and saucy relishes.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Bring salted water to a boil in a heavy pot.\n2. Slowly sprinkle in the maize meal while stirring to prevent lumps.\n3. Reduce heat to very low.\n4. Cover the pot tightly and cook for 15 minutes.\n5. Remove lid and stir vigorously with a wooden spoon until smooth.\n6. The pap is ready when it is thick and pulls away from the pot.\n7. Serve hot alongside chakalaka, braised meat, or tomato relish.",
        "ingredients": [
            ("White maize meal", 2.0, "cups"),
            ("Water", 3.5, "cups"),
            ("Salt", 1.0, "tsp"),
            ("Butter", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Bunny Chow",
        "description": "A Durban street food legend: a hollowed-out loaf of bread filled with spicy curry. Born from South Africa's Indian community.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 45,
        "servings": 4,
        "tags": ["spicy", "high-protein", "budget"],
        "instructions": "1. Heat oil in a pot and sauté diced onion until golden.\n2. Add minced garlic, grated ginger, and curry leaves.\n3. Stir in curry powder, turmeric, cumin, and cayenne, cook for 1 minute.\n4. Add diced chicken and brown on all sides.\n5. Add diced tomatoes and potatoes, pour in water.\n6. Simmer covered for 30 minutes until chicken is tender and sauce is thick.\n7. Cut a bread loaf into quarters, hollow out each piece.\n8. Fill the bread shells with curry and serve with the scooped-out bread for dipping.",
        "ingredients": [
            ("Chicken breast", 400.0, "g"),
            ("White bread loaf", 1.0, "pieces"),
            ("Potato", 2.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Fresh ginger", 1.0, "tbsp"),
            ("Curry powder", 2.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Samp and Beans",
        "description": "A traditional South African dish of dried corn kernels and sugar beans slow-cooked until creamy. A Xhosa and Zulu staple called umngqusho.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 120,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein", "one-pot"],
        "instructions": "1. Soak samp and sugar beans separately overnight.\n2. Drain and place both in a large pot, cover with fresh water.\n3. Bring to a boil, then reduce to a steady simmer.\n4. Cook for 1.5-2 hours, adding water as needed, until samp is tender.\n5. In the last 20 minutes, add salt, pepper, and a knob of butter.\n6. The dish is ready when the beans and samp are soft and creamy.\n7. Serve as a side dish alongside braised meats or stews.",
        "ingredients": [
            ("Samp (dried corn kernels)", 2.0, "cups"),
            ("Sugar beans", 1.0, "cups"),
            ("Butter", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
            ("Black pepper", 0.5, "tsp"),
            ("Water", 8.0, "cups"),
        ],
    },
    {
        "title": "Potjiekos",
        "description": "A South African cast-iron pot stew layered with meat and vegetables, slow-cooked over coals without stirring. A braai tradition.",
        "difficulty": "medium",
        "prep_time": 25,
        "cook_time": 120,
        "servings": 6,
        "tags": ["stew", "high-protein", "gluten-free", "budget"],
        "instructions": "1. Heat oil in a cast-iron pot (potjie) over coals and brown beef cubes on all sides.\n2. Add sliced onions on top of the meat.\n3. Layer in diced carrots, potatoes, and cabbage wedges.\n4. Season each layer with salt, pepper, and mixed herbs.\n5. Pour in beef broth, being careful not to disturb the layers.\n6. Cover with a tight-fitting lid and cook over low coals for 2 hours.\n7. Do not stir at any point during cooking.\n8. Serve by scooping from top to bottom to get all layers.",
        "ingredients": [
            ("Beef stew meat", 500.0, "g"),
            ("Potato", 3.0, "pieces"),
            ("Carrot", 3.0, "pieces"),
            ("Cabbage", 0.25, "pieces"),
            ("Onion", 2.0, "pieces"),
            ("Beef broth", 1.0, "cups"),
            ("Mixed dried herbs", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    # === MORE DIVERSE AFRICAN RECIPES ===
    {
        "title": "Koshari",
        "description": "Egypt's beloved street food of rice, lentils, and pasta topped with spiced tomato sauce and crispy fried onions. Carb heaven.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 40,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "budget", "high-protein"],
        "instructions": "1. Cook rice, lentils, and small pasta separately according to package directions, then drain.\n2. For the sauce, heat oil and sauté garlic until golden.\n3. Add crushed tomatoes, vinegar, cumin, and chili flakes, simmer for 15 minutes.\n4. For the crispy onions, thinly slice 3 onions and deep fry in oil until dark golden.\n5. Drain fried onions on paper towels.\n6. Layer the rice, lentils, and pasta in a serving bowl.\n7. Top with tomato sauce and crispy fried onions.\n8. Serve with extra hot sauce and vinegar on the side.",
        "ingredients": [
            ("Rice", 1.0, "cups"),
            ("Brown lentils", 0.75, "cups"),
            ("Small elbow pasta", 1.0, "cups"),
            ("Crushed tomatoes", 400.0, "g"),
            ("Onion", 4.0, "pieces"),
            ("Garlic", 4.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("White vinegar", 2.0, "tbsp"),
            ("Vegetable oil", 0.5, "cups"),
            ("Chili flakes", 0.5, "tsp"),
        ],
    },
    {
        "title": "Jollof Spaghetti",
        "description": "A fun Nigerian twist that applies the classic jollof rice technique to spaghetti. Quick, flavorful, and loved by kids and adults alike.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["budget", "quick", "one-pot"],
        "instructions": "1. Blend tomatoes, scotch bonnet pepper, and red bell pepper into a smooth paste.\n2. Heat vegetable oil in a large pot and sauté diced onion until translucent.\n3. Add tomato paste and fry for 3 minutes.\n4. Pour in the blended pepper mixture and cook for 10 minutes.\n5. Add water, season with salt, thyme, and curry powder.\n6. Break spaghetti in half and add to the pot.\n7. Cook covered on low heat, stirring occasionally, until spaghetti is tender.\n8. Serve hot as is or alongside fried plantain.",
        "ingredients": [
            ("Spaghetti", 400.0, "g"),
            ("Tomatoes", 4.0, "pieces"),
            ("Red bell pepper", 1.0, "pieces"),
            ("Scotch bonnet pepper", 1.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Ndole",
        "description": "Cameroon's national dish of bitter leaves cooked with groundnuts, shrimp, and spinach. Complex, nutty, and deeply savory.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 60,
        "servings": 6,
        "tags": ["stew", "high-protein", "gluten-free", "budget"],
        "instructions": "1. Wash bitter leaves multiple times, boiling and squeezing to remove bitterness.\n2. Grind roasted peanuts to a smooth paste.\n3. Boil beef until tender, reserving the broth.\n4. Soak and clean dried shrimp.\n5. In a pot, combine the peanut paste with some broth and cook for 15 minutes.\n6. Add the washed bitter leaves (or substitute with spinach) and stir.\n7. Add cooked beef and dried shrimp, simmer for 20 minutes.\n8. Season with salt and serve with boiled plantains or rice.",
        "ingredients": [
            ("Spinach", 500.0, "g"),
            ("Roasted peanuts", 1.0, "cups"),
            ("Beef stew meat", 300.0, "g"),
            ("Dried shrimp", 100.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Matooke Stew",
        "description": "A hearty Ugandan stew featuring green bananas slow-cooked with beef, tomatoes, and onions until everything melts together.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 50,
        "servings": 4,
        "tags": ["stew", "gluten-free", "budget", "one-pot"],
        "instructions": "1. Peel green bananas and keep in salted water to prevent browning.\n2. Cut beef into small cubes and season with salt.\n3. Heat oil and brown the beef, then add diced onion.\n4. Add chopped tomatoes and cook for 10 minutes.\n5. Add the green bananas and enough water to cover.\n6. Cover tightly and simmer for 40 minutes until everything is very soft.\n7. Mash some bananas into the sauce to thicken it.\n8. Season with salt and serve hot.",
        "ingredients": [
            ("Green bananas", 6.0, "pieces"),
            ("Beef stew meat", 300.0, "g"),
            ("Tomatoes", 3.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
            ("Water", 3.0, "cups"),
        ],
    },
    {
        "title": "Tibs",
        "description": "Ethiopian sauteed beef cubes with onions, peppers, and rosemary in butter. Quick to prepare and intensely flavorful.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["high-protein", "gluten-free", "quick", "budget"],
        "instructions": "1. Cut beef into bite-sized cubes.\n2. Heat butter in a hot skillet until foaming.\n3. Add the beef cubes and sear on high heat without stirring for 2 minutes.\n4. Add sliced onion, diced green pepper, and minced garlic.\n5. Toss in fresh rosemary and a pinch of black pepper.\n6. Stir-fry for 5-7 minutes until beef is cooked to your liking.\n7. Season with salt and serve immediately with injera.",
        "ingredients": [
            ("Beef sirloin", 400.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Green bell pepper", 1.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Butter", 2.0, "tbsp"),
            ("Fresh rosemary", 1.0, "tbsp"),
            ("Black pepper", 0.5, "tsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Attiéké",
        "description": "A light, tangy cassava couscous from Ivory Coast, fermented and steamed. The West African alternative to rice.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. If using dried attieke, rehydrate by soaking in warm water for 10 minutes.\n2. Break up any clumps with your fingers.\n3. Place attieke in a steamer basket lined with cheesecloth.\n4. Steam over boiling water for 15-20 minutes until fluffy and hot.\n5. Fluff with a fork and drizzle with a small amount of vegetable oil.\n6. Season with salt.\n7. Serve alongside grilled fish, fried plantains, or alloco.",
        "ingredients": [
            ("Attieke (cassava couscous)", 400.0, "g"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
            ("Onion", 1.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
        ],
    },
    {
        "title": "Moroccan Chickpea and Spinach Stew",
        "description": "A nourishing Moroccan one-pot stew of chickpeas, spinach, and tomatoes spiced with cumin and paprika. Simple and deeply comforting.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "one-pot", "high-protein", "quick"],
        "instructions": "1. Heat olive oil in a pot and sauté diced onion and garlic until fragrant.\n2. Add cumin, paprika, and a pinch of cayenne, stir for 30 seconds.\n3. Add diced tomatoes and cook for 5 minutes.\n4. Stir in drained chickpeas and add water.\n5. Simmer for 15 minutes to let flavors meld.\n6. Add fresh spinach and stir until wilted.\n7. Season with salt and lemon juice, serve with crusty bread.",
        "ingredients": [
            ("Chickpeas", 400.0, "g"),
            ("Spinach", 200.0, "g"),
            ("Tomatoes", 3.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Cumin", 1.0, "tsp"),
            ("Paprika", 1.0, "tsp"),
            ("Lemon", 0.5, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tanzanian Coconut Bean Soup",
        "description": "A creamy Tanzanian soup of kidney beans simmered in coconut milk with garlic and cumin. Rich, warming, and gently spiced.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein", "stew"],
        "instructions": "1. Heat oil in a pot and sauté diced onion and garlic.\n2. Add cumin and turmeric, cook for 1 minute.\n3. Add drained kidney beans and diced tomatoes.\n4. Pour in coconut milk and water, stir well.\n5. Bring to a boil then simmer for 20 minutes.\n6. Mash some beans against the side of the pot to thicken the soup.\n7. Season with salt and pepper, serve with rice or bread.",
        "ingredients": [
            ("Kidney beans", 400.0, "g"),
            ("Coconut milk", 400.0, "ml"),
            ("Tomatoes", 2.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Turmeric", 0.5, "tsp"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Eritrean Tsebhi Birsen (Red Lentil Stew)",
        "description": "A warmly spiced Eritrean red lentil stew made with berbere, tomatoes, and onions. A staple of the Eritrean meal platter.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein", "stew", "spicy"],
        "instructions": "1. Finely dice onions and cook in oil over medium heat until deeply softened.\n2. Add tomato paste and berbere spice, stir for 2 minutes.\n3. Add diced tomatoes and cook for 5 minutes.\n4. Rinse red lentils and add to the pot with water.\n5. Bring to a boil, then reduce heat and simmer for 25 minutes.\n6. Stir occasionally and add more water if needed.\n7. Season with salt and serve on injera or with flatbread.",
        "ingredients": [
            ("Red lentils", 1.5, "cups"),
            ("Onion", 2.0, "pieces"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Tomatoes", 2.0, "pieces"),
            ("Berbere spice", 2.0, "tbsp"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Water", 3.0, "cups"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "West African Tomato Stew",
        "description": "A rich, versatile tomato-based stew that forms the base of countless West African dishes. Slow-cooked until deep red and intensely flavored.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "stew"],
        "instructions": "1. Blend tomatoes, scotch bonnet pepper, and red bell pepper into a smooth paste.\n2. Heat vegetable oil in a pot until shimmering.\n3. Sauté diced onion until golden brown.\n4. Add the blended tomato mixture carefully (it will splatter).\n5. Cook on medium heat for 25-30 minutes, stirring often, until oil separates.\n6. Add thyme, bay leaf, and salt to taste.\n7. Simmer for 5 more minutes and serve over rice, yam, or pasta.",
        "ingredients": [
            ("Tomatoes", 6.0, "pieces"),
            ("Red bell pepper", 2.0, "pieces"),
            ("Scotch bonnet pepper", 1.0, "pieces"),
            ("Onion", 2.0, "pieces"),
            ("Vegetable oil", 0.33, "cups"),
            ("Thyme", 1.0, "tsp"),
            ("Bay leaf", 1.0, "pieces"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Senegalese Black-Eyed Pea Stew (Thiou Niebe)",
        "description": "A simple Senegalese stew of black-eyed peas in a savory tomato sauce with onions and spices. Protein-rich and filling.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein", "stew", "one-pot"],
        "instructions": "1. Soak black-eyed peas overnight, then drain.\n2. Boil peas in fresh water for 20 minutes until half-cooked.\n3. In a separate pot, heat oil and sauté diced onion until soft.\n4. Add tomato paste and cook for 3 minutes.\n5. Add the half-cooked peas with their cooking liquid.\n6. Season with salt, pepper, and a bay leaf.\n7. Simmer for 20 minutes until peas are tender and sauce has thickened.\n8. Serve over rice.",
        "ingredients": [
            ("Black-eyed peas", 2.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato paste", 3.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Bay leaf", 1.0, "pieces"),
            ("Salt", 1.0, "tsp"),
            ("Black pepper", 0.25, "tsp"),
            ("Water", 4.0, "cups"),
        ],
    },
    {
        "title": "Gomen (Ethiopian Collard Greens)",
        "description": "Tender Ethiopian collard greens braised with garlic, ginger, and a touch of cardamom. A clean, simple vegetable side.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Wash collard greens thoroughly and chop finely, discarding thick stems.\n2. Heat vegetable oil in a pot over medium heat.\n3. Sauté minced garlic and grated ginger for 1 minute.\n4. Add the chopped greens and stir to coat with the oil.\n5. Add a small amount of water, cover, and steam for 15 minutes.\n6. Season with salt, black pepper, and a pinch of cardamom.\n7. Serve as part of an Ethiopian meal platter on injera.",
        "ingredients": [
            ("Collard greens", 500.0, "g"),
            ("Garlic", 4.0, "pieces"),
            ("Fresh ginger", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Ground cardamom", 0.25, "tsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Moroccan Lamb Kefta",
        "description": "Spiced Moroccan lamb meatballs simmered in a cumin-tomato sauce. Easy to make and full of North African flavor.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 30,
        "servings": 4,
        "tags": ["high-protein", "budget", "spicy"],
        "instructions": "1. Mix ground lamb with grated onion, chopped parsley, cumin, paprika, cinnamon, and salt.\n2. Shape into small meatballs about the size of walnuts.\n3. Heat olive oil in a pan and sauté diced onion and garlic.\n4. Add crushed tomatoes, cumin, and paprika, simmer for 10 minutes.\n5. Gently place meatballs into the simmering sauce.\n6. Cover and cook for 15-20 minutes until meatballs are cooked through.\n7. Garnish with fresh cilantro and serve with crusty bread or couscous.",
        "ingredients": [
            ("Ground lamb", 400.0, "g"),
            ("Crushed tomatoes", 400.0, "g"),
            ("Onion", 2.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Fresh parsley", 0.25, "cups"),
            ("Cumin", 1.5, "tsp"),
            ("Paprika", 1.0, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Nigerian Fried Rice",
        "description": "A colorful Nigerian party rice stir-fried with mixed vegetables, liver, and shrimp. A celebration staple found at every Nigerian gathering.",
        "difficulty": "medium",
        "prep_time": 25,
        "cook_time": 30,
        "servings": 6,
        "tags": ["gluten-free", "high-protein", "budget"],
        "instructions": "1. Cook long-grain rice until fluffy, spread on a tray to cool.\n2. Dice carrots, green beans, and green bell pepper into small pieces.\n3. Blanch the vegetables in boiling salted water for 2 minutes, then drain.\n4. Heat vegetable oil in a large pan or wok over high heat.\n5. Stir-fry the blanched vegetables for 3 minutes.\n6. Add the cooked rice and toss everything together.\n7. Season with thyme, curry powder, and salt.\n8. Serve hot alongside jollof rice and fried chicken.",
        "ingredients": [
            ("Long-grain rice", 3.0, "cups"),
            ("Carrot", 2.0, "pieces"),
            ("Green beans", 100.0, "g"),
            ("Green bell pepper", 1.0, "pieces"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Thyme", 1.0, "tsp"),
            ("Curry powder", 1.0, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
]
