MEXICAN_RECIPES = [
    {
        "title": "Black Bean Tacos",
        "description": "Simple street-style tacos filled with seasoned black beans, fresh onion, and cilantro on warm corn tortillas.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget", "quick"],
        "instructions": "1. Drain and rinse the black beans.\n2. Heat oil in a skillet over medium heat and saute diced onion until soft.\n3. Add black beans, cumin, chili powder, and salt to the skillet and cook for 8 minutes, mashing some beans lightly.\n4. Warm the corn tortillas on a dry comal or skillet.\n5. Spoon the bean mixture onto each tortilla.\n6. Top with fresh cilantro, diced onion, and a squeeze of lime.",
        "ingredients": [
            ("Black beans", 2.0, "cups"),
            ("Corn tortillas", 8.0, "pieces"),
            ("White onion", 1.0, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Lime", 1.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Chili powder", 0.5, "tsp"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Chicken Enchiladas Rojas",
        "description": "Corn tortillas rolled around shredded chicken and smothered in a rich dried chile red sauce with crumbled queso fresco.",
        "difficulty": "medium",
        "prep_time": 25,
        "cook_time": 35,
        "servings": 4,
        "tags": ["budget", "high-protein", "spicy"],
        "instructions": "1. Toast dried guajillo chiles in a dry skillet until fragrant, then soak in hot water for 15 minutes.\n2. Blend the soaked chiles with garlic, cumin, oregano, and a cup of the soaking liquid until smooth.\n3. Strain the sauce through a sieve and season with salt.\n4. Shred the cooked chicken and mix with a few spoonfuls of the red sauce.\n5. Dip each tortilla in the warm sauce, fill with chicken, and roll up tightly.\n6. Place seam-side down in a baking dish, pour remaining sauce over the top.\n7. Bake at 375F for 20 minutes until bubbly.\n8. Garnish with crumbled queso fresco and sliced onion.",
        "ingredients": [
            ("Chicken breast", 500.0, "g"),
            ("Dried guajillo chiles", 6.0, "pieces"),
            ("Corn tortillas", 12.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Dried oregano", 0.5, "tsp"),
            ("Queso fresco", 100.0, "g"),
            ("White onion", 0.5, "pieces"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Pozole Rojo",
        "description": "A hearty traditional Mexican pork and hominy soup in a deeply flavored dried chile broth, served with crunchy toppings.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 120,
        "servings": 6,
        "tags": ["high-protein", "gluten-free", "one-pot", "spicy"],
        "instructions": "1. Place pork shoulder in a large pot, cover with water, add half the onion and garlic, and simmer for 90 minutes until tender.\n2. While pork cooks, toast dried guajillo and ancho chiles in a dry skillet, then soak in hot water for 20 minutes.\n3. Blend soaked chiles with garlic, cumin, oregano, and soaking liquid until smooth, then strain.\n4. Shred the cooked pork and return to the strained broth.\n5. Add the chile sauce and drained hominy to the pot and simmer for 30 minutes.\n6. Season with salt and oregano.\n7. Serve in deep bowls topped with shredded cabbage, sliced radishes, and lime wedges.",
        "ingredients": [
            ("Pork shoulder", 700.0, "g"),
            ("Canned hominy", 3.0, "cups"),
            ("Dried guajillo chiles", 5.0, "pieces"),
            ("Dried ancho chiles", 3.0, "pieces"),
            ("White onion", 1.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Dried oregano", 1.0, "tbsp"),
            ("Cabbage", 2.0, "cups"),
            ("Radishes", 4.0, "pieces"),
            ("Lime", 2.0, "pieces"),
        ],
    },
    {
        "title": "Chilaquiles Verdes",
        "description": "Crispy tortilla chips simmered in tangy tomatillo salsa verde and topped with crema, onion, and cheese.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 3,
        "tags": ["vegetarian", "budget", "quick"],
        "instructions": "1. Boil tomatillos and serrano peppers in water until soft, about 10 minutes.\n2. Blend boiled tomatillos, serranos, garlic, and cilantro until smooth.\n3. Heat oil in a wide skillet, pour in the salsa, and simmer for 5 minutes, seasoning with salt.\n4. Add tortilla chips to the salsa and toss gently to coat, cooking for 2 minutes.\n5. Serve immediately topped with crema, crumbled queso fresco, and sliced onion.",
        "ingredients": [
            ("Tomatillos", 8.0, "pieces"),
            ("Serrano peppers", 2.0, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Tortilla chips", 4.0, "cups"),
            ("Mexican crema", 3.0, "tbsp"),
            ("Queso fresco", 60.0, "g"),
            ("White onion", 0.25, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Pork Tamales",
        "description": "Traditional tamales with a savory pork filling wrapped in masa dough and steamed in corn husks until tender.",
        "difficulty": "hard",
        "prep_time": 60,
        "cook_time": 90,
        "servings": 6,
        "tags": ["budget", "high-protein", "gluten-free"],
        "instructions": "1. Soak dried corn husks in warm water for at least 30 minutes.\n2. Simmer pork shoulder in salted water with onion and garlic until very tender, about 90 minutes, then shred.\n3. Toast and soak dried guajillo chiles, then blend with garlic and cumin into a smooth sauce. Simmer sauce with the shredded pork.\n4. Beat lard until fluffy, then mix in masa harina, broth, baking powder, and salt to form a soft dough.\n5. Spread a thin layer of masa onto each soaked corn husk.\n6. Add a spoonful of the pork filling down the center, fold the sides in and fold up the bottom.\n7. Stand tamales upright in a steamer pot and steam for 60-75 minutes until the masa pulls away from the husk.\n8. Let rest 10 minutes before serving.",
        "ingredients": [
            ("Masa harina", 3.0, "cups"),
            ("Pork shoulder", 500.0, "g"),
            ("Dried corn husks", 20.0, "pieces"),
            ("Lard", 0.75, "cups"),
            ("Dried guajillo chiles", 5.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Baking powder", 1.0, "tsp"),
            ("Salt", 1.5, "tsp"),
        ],
    },
    {
        "title": "Frijoles de Olla",
        "description": "Simple pot beans slow-cooked with onion, garlic, and epazote until creamy and rich, a staple of the Mexican table.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 150,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "one-pot"],
        "instructions": "1. Rinse and sort pinto beans, discarding any broken ones or stones.\n2. Place beans in a large pot and cover with water by at least 3 inches.\n3. Add the quartered onion, whole garlic cloves, and epazote.\n4. Bring to a boil, then reduce heat to a gentle simmer.\n5. Cook uncovered for about 2.5 hours, adding hot water as needed to keep beans submerged.\n6. Season with salt during the last 30 minutes of cooking.\n7. Serve in bowls with plenty of the bean broth.",
        "ingredients": [
            ("Pinto beans", 2.0, "cups"),
            ("White onion", 0.5, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Dried epazote", 1.0, "tbsp"),
            ("Salt", 1.5, "tsp"),
        ],
    },
    {
        "title": "Arroz Rojo",
        "description": "Classic Mexican tomato rice gently toasted and simmered with tomato, onion, and garlic until every grain is fluffy and red.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Blend tomatoes, onion, and garlic with a half cup of water until smooth.\n2. Heat oil in a saucepan over medium heat and toast the rice, stirring constantly, until golden, about 5 minutes.\n3. Pour the tomato mixture into the rice and stir well.\n4. Add chicken broth, salt, and cumin. Bring to a boil.\n5. Reduce heat to low, cover tightly, and cook for 18 minutes without lifting the lid.\n6. Remove from heat and let stand covered for 5 minutes, then fluff with a fork.",
        "ingredients": [
            ("Long grain white rice", 1.5, "cups"),
            ("Tomatoes", 2.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("Chicken broth", 2.0, "cups"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Cumin", 0.5, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Sopa de Fideo",
        "description": "A comforting everyday Mexican noodle soup with toasted fideo pasta in a light tomato broth.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "budget", "quick", "one-pot"],
        "instructions": "1. Heat oil in a pot over medium heat and toast the fideo noodles, stirring constantly, until deep golden brown.\n2. Blend tomatoes, onion, and garlic until smooth.\n3. Pour the tomato mixture over the toasted noodles and stir for 2 minutes.\n4. Add chicken broth and salt, bring to a boil.\n5. Reduce heat and simmer for 10 minutes until noodles are tender and liquid is mostly absorbed.\n6. Serve hot, garnished with a squeeze of lime and diced avocado.",
        "ingredients": [
            ("Fideo noodles", 200.0, "g"),
            ("Tomatoes", 2.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("Chicken broth", 3.0, "cups"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Lime", 1.0, "pieces"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Huevos Rancheros",
        "description": "Fried eggs served on corn tortillas and drenched in a rustic tomato-chile ranchero sauce, a classic Mexican breakfast.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 2,
        "tags": ["vegetarian", "gluten-free", "budget", "quick", "high-protein"],
        "instructions": "1. Roast tomatoes, onion, and serrano pepper on a comal or dry skillet until charred on all sides.\n2. Blend the roasted vegetables with garlic and salt until slightly chunky.\n3. Simmer the sauce in a skillet for 10 minutes until thickened.\n4. In a separate skillet, heat oil and fry eggs sunny-side up.\n5. Warm corn tortillas on the comal.\n6. Place tortillas on plates, top each with a fried egg, and spoon ranchero sauce generously over the top.\n7. Garnish with fresh cilantro and serve with refried beans.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Serrano pepper", 1.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("Corn tortillas", 4.0, "pieces"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Fresh cilantro", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Molletes",
        "description": "Toasted bolillo bread halves spread with refried beans and melted cheese, a beloved quick Mexican snack.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "budget", "quick"],
        "instructions": "1. Slice the bolillo rolls in half lengthwise.\n2. Toast the cut side under a broiler for 2 minutes until lightly crisp.\n3. Spread a generous layer of refried beans on each half.\n4. Top with shredded Oaxaca cheese or Chihuahua cheese.\n5. Return to the broiler and cook until the cheese is fully melted and bubbly, about 3 minutes.\n6. Top with pico de gallo and serve immediately.",
        "ingredients": [
            ("Bolillo rolls", 2.0, "pieces"),
            ("Refried beans", 1.0, "cups"),
            ("Oaxaca cheese", 100.0, "g"),
            ("Tomato", 1.0, "pieces"),
            ("White onion", 2.0, "tbsp"),
            ("Serrano pepper", 0.5, "pieces"),
            ("Fresh cilantro", 1.0, "tbsp"),
            ("Salt", 0.25, "tsp"),
        ],
    },
    {
        "title": "Quesadillas de Queso",
        "description": "Simple corn tortilla quesadillas filled with melty Oaxaca cheese, pressed on a hot comal until golden.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "budget", "quick"],
        "instructions": "1. Shred the Oaxaca cheese into thin strings.\n2. Place a corn tortilla on a hot comal or dry skillet.\n3. Add a generous handful of cheese to one half of the tortilla.\n4. Fold the tortilla over and press lightly with a spatula.\n5. Cook for 2 minutes per side until golden and the cheese is melted.\n6. Serve with salsa verde and a squeeze of lime.",
        "ingredients": [
            ("Corn tortillas", 6.0, "pieces"),
            ("Oaxaca cheese", 200.0, "g"),
            ("Salsa verde", 0.25, "cups"),
            ("Lime", 1.0, "pieces"),
            ("Salt", 0.25, "tsp"),
        ],
    },
    {
        "title": "Enfrijoladas",
        "description": "Tortillas dipped in a silky black bean sauce and folded, topped with crema, queso fresco, and onion rings.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 3,
        "tags": ["vegetarian", "budget", "quick"],
        "instructions": "1. Blend cooked black beans with their broth, garlic, and a chipotle pepper until very smooth.\n2. Heat the bean sauce in a skillet over medium heat, thinning with water if needed, and season with salt.\n3. Lightly fry tortillas in a bit of oil to soften them.\n4. Dip each tortilla in the warm bean sauce, fold into quarters, and arrange on a plate.\n5. Pour extra sauce over the top.\n6. Garnish with crumbled queso fresco, a drizzle of crema, and sliced white onion.",
        "ingredients": [
            ("Black beans", 2.0, "cups"),
            ("Corn tortillas", 9.0, "pieces"),
            ("Chipotle pepper in adobo", 1.0, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("Queso fresco", 60.0, "g"),
            ("Mexican crema", 3.0, "tbsp"),
            ("White onion", 0.5, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Calabacitas con Elote",
        "description": "A summery sauteed side dish of tender Mexican squash with corn, tomatoes, and melted cheese.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick"],
        "instructions": "1. Dice the Mexican squash into small cubes.\n2. Heat oil in a skillet and saute onion until translucent.\n3. Add diced squash and corn kernels, cooking for 5 minutes.\n4. Add diced tomatoes and serrano pepper, season with salt.\n5. Cook for 8 more minutes until the squash is tender.\n6. Stir in cubed Chihuahua cheese and let it melt into the vegetables.\n7. Serve as a side dish or with warm corn tortillas.",
        "ingredients": [
            ("Mexican squash", 4.0, "pieces"),
            ("Corn kernels", 1.0, "cups"),
            ("Tomato", 1.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Serrano pepper", 1.0, "pieces"),
            ("Chihuahua cheese", 80.0, "g"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Caldo de Pollo",
        "description": "Mexican-style chicken soup with whole vegetables simmered low and slow for a deeply nourishing broth.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 60,
        "servings": 6,
        "tags": ["gluten-free", "budget", "one-pot", "high-protein"],
        "instructions": "1. Place chicken pieces in a large pot and cover with cold water.\n2. Bring to a boil, skimming off any foam that rises to the surface.\n3. Add halved onion, garlic, and whole peppercorns, then reduce to a simmer.\n4. After 20 minutes, add large chunks of carrot, potato, and chayote.\n5. Add a sprig of cilantro and continue simmering for 30 more minutes.\n6. Season with salt to taste.\n7. Serve in large bowls with lime wedges, chopped cilantro, and warm tortillas on the side.",
        "ingredients": [
            ("Chicken pieces", 800.0, "g"),
            ("Carrots", 2.0, "pieces"),
            ("Potatoes", 2.0, "pieces"),
            ("Chayote", 1.0, "pieces"),
            ("White onion", 1.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Lime", 2.0, "pieces"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Tostadas de Tinga de Pollo",
        "description": "Crunchy tostadas piled high with smoky chipotle-tomato shredded chicken, lettuce, crema, and cheese.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["budget", "high-protein", "spicy"],
        "instructions": "1. Poach chicken breasts in salted water until cooked through, about 20 minutes, then shred.\n2. Blend tomatoes, chipotle peppers, and garlic into a smooth sauce.\n3. Saute sliced onion in oil until soft, then pour in the chipotle-tomato sauce.\n4. Add the shredded chicken and simmer for 15 minutes until the sauce thickens.\n5. Top crispy tostadas with a layer of refried beans, then the tinga chicken.\n6. Garnish with shredded lettuce, crema, and crumbled queso fresco.",
        "ingredients": [
            ("Chicken breast", 400.0, "g"),
            ("Tostada shells", 8.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Chipotle peppers in adobo", 2.0, "pieces"),
            ("White onion", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Lettuce", 2.0, "cups"),
            ("Mexican crema", 3.0, "tbsp"),
            ("Queso fresco", 60.0, "g"),
            ("Vegetable oil", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Sopes",
        "description": "Thick masa boats with pinched edges, topped with refried beans, lettuce, crema, and salsa for a satisfying antojito.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Mix masa harina with warm water and salt to form a soft dough.\n2. Divide into 8 balls and press each into a thick round disc.\n3. Cook on a hot comal for 2-3 minutes per side until lightly cooked.\n4. While still warm, pinch up the edges to form a shallow rim around each sope.\n5. Lightly fry the sopes in oil for 1 minute on the base to crisp them.\n6. Spread refried beans on each sope.\n7. Top with shredded lettuce, crema, crumbled queso fresco, and salsa verde.",
        "ingredients": [
            ("Masa harina", 2.0, "cups"),
            ("Refried beans", 1.0, "cups"),
            ("Lettuce", 1.0, "cups"),
            ("Mexican crema", 3.0, "tbsp"),
            ("Queso fresco", 60.0, "g"),
            ("Salsa verde", 0.5, "cups"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Rajas con Crema",
        "description": "Roasted poblano pepper strips cooked in a luscious cream sauce with onions and corn, a perfect taco filling.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick"],
        "instructions": "1. Roast poblano peppers directly over a flame or under a broiler until charred all over.\n2. Place in a plastic bag to steam for 10 minutes, then peel, seed, and slice into strips.\n3. Saute sliced onion in oil until softened.\n4. Add the poblano strips and corn kernels, cooking for 3 minutes.\n5. Pour in the crema and stir gently, simmering for 5 minutes until thickened.\n6. Season with salt and serve with warm tortillas.",
        "ingredients": [
            ("Poblano peppers", 4.0, "pieces"),
            ("White onion", 1.0, "pieces"),
            ("Corn kernels", 1.0, "cups"),
            ("Mexican crema", 0.75, "cups"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tacos de Papa",
        "description": "Crispy fried tacos filled with well-seasoned mashed potato, a beloved street food found across Mexico.",
        "difficulty": "easy",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget"],
        "instructions": "1. Boil potatoes until tender, then drain and mash with salt and a pinch of cumin.\n2. Warm corn tortillas so they are pliable.\n3. Place a spoonful of mashed potato in the center of each tortilla and fold in half.\n4. Secure with a toothpick if needed.\n5. Fry in hot oil until golden and crispy on both sides, about 2 minutes per side.\n6. Drain on paper towels and serve topped with shredded lettuce, crema, and salsa.",
        "ingredients": [
            ("Potatoes", 4.0, "pieces"),
            ("Corn tortillas", 12.0, "pieces"),
            ("Vegetable oil", 1.0, "cups"),
            ("Cumin", 0.5, "tsp"),
            ("Lettuce", 1.0, "cups"),
            ("Salsa verde", 0.5, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Chicken Flautas",
        "description": "Tightly rolled corn tortillas stuffed with shredded chicken and fried until shatteringly crisp.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "tags": ["budget", "high-protein"],
        "instructions": "1. Shred cooked chicken and season with salt, cumin, and a squeeze of lime.\n2. Warm corn tortillas to make them pliable.\n3. Place a line of chicken filling along each tortilla and roll as tightly as possible.\n4. Secure each flauta with a toothpick.\n5. Fry in hot oil, turning occasionally, until golden and crispy all over, about 4 minutes.\n6. Drain on paper towels.\n7. Serve on a bed of shredded lettuce with crema, queso fresco, and salsa.",
        "ingredients": [
            ("Chicken breast", 400.0, "g"),
            ("Corn tortillas", 12.0, "pieces"),
            ("Vegetable oil", 1.0, "cups"),
            ("Cumin", 0.5, "tsp"),
            ("Lime", 1.0, "pieces"),
            ("Lettuce", 2.0, "cups"),
            ("Mexican crema", 3.0, "tbsp"),
            ("Queso fresco", 60.0, "g"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Frijoles Charros",
        "description": "Cowboy-style pinto beans in a savory broth with bacon, onion, tomato, and serrano peppers.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 150,
        "servings": 6,
        "tags": ["gluten-free", "budget", "one-pot", "high-protein"],
        "instructions": "1. Cook pinto beans in a large pot of water until tender, about 2 hours.\n2. In a separate skillet, cook diced bacon until crispy.\n3. Add diced onion, tomato, and serrano peppers to the bacon and saute for 5 minutes.\n4. Add the bacon mixture to the pot of cooked beans along with their broth.\n5. Stir in chopped cilantro and simmer together for 20 minutes.\n6. Season with salt and serve in deep bowls with warm tortillas.",
        "ingredients": [
            ("Pinto beans", 2.0, "cups"),
            ("Bacon", 150.0, "g"),
            ("White onion", 1.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("Serrano peppers", 2.0, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Entomatadas",
        "description": "Corn tortillas bathed in a simple cooked tomato sauce, folded, and topped with crema and cheese.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 3,
        "tags": ["vegetarian", "budget", "quick"],
        "instructions": "1. Boil tomatoes until soft, about 10 minutes.\n2. Blend boiled tomatoes with garlic, onion, and salt until smooth.\n3. Heat oil in a skillet, pour in the sauce, and simmer for 10 minutes.\n4. Lightly fry tortillas in oil to soften.\n5. Dip each tortilla in the warm tomato sauce, fold into quarters, and arrange on a plate.\n6. Pour remaining sauce over the top and garnish with crema and crumbled queso fresco.",
        "ingredients": [
            ("Tomatoes", 5.0, "pieces"),
            ("Corn tortillas", 9.0, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Queso fresco", 60.0, "g"),
            ("Mexican crema", 3.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Gorditas de Frijol",
        "description": "Thick masa pockets stuffed with seasoned refried beans, pan-fried until golden with a soft interior.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Mix masa harina with warm water and salt to form a smooth dough.\n2. Divide the dough into 8 portions and flatten each into a thick round.\n3. Place a spoonful of refried beans in the center, fold the dough over, and reshape into a thick disc.\n4. Cook on a hot comal for 3 minutes per side until a light crust forms.\n5. Split open along the edge to form a pocket.\n6. Stuff with shredded lettuce, crema, queso fresco, and salsa.",
        "ingredients": [
            ("Masa harina", 2.0, "cups"),
            ("Refried beans", 1.0, "cups"),
            ("Lettuce", 1.0, "cups"),
            ("Mexican crema", 3.0, "tbsp"),
            ("Queso fresco", 60.0, "g"),
            ("Salsa roja", 0.5, "cups"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Salsa Roja de Chile de Arbol",
        "description": "A fiery and smoky table salsa made from toasted dried chiles de arbol and roasted tomatoes.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick", "spicy"],
        "instructions": "1. Toast dried chiles de arbol in a dry skillet until darkened and fragrant, being careful not to burn them.\n2. Roast tomatoes and garlic on the same skillet until charred.\n3. Blend the chiles, roasted tomatoes, garlic, and salt with a splash of water until smooth.\n4. Taste and adjust salt.\n5. Serve at room temperature as a table salsa with chips or alongside any dish.",
        "ingredients": [
            ("Dried chiles de arbol", 10.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Salt", 0.5, "tsp"),
            ("Water", 0.25, "cups"),
        ],
    },
    {
        "title": "Guacamole",
        "description": "Classic chunky Mexican guacamole with ripe avocados, lime, onion, cilantro, and serrano chile.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Halve the avocados and remove the pits.\n2. Scoop the flesh into a molcajete or bowl and mash to desired consistency.\n3. Finely dice the onion, serrano pepper, and tomato.\n4. Fold the diced vegetables and chopped cilantro into the avocado.\n5. Squeeze lime juice over the top and season with salt.\n6. Mix gently and serve immediately with tortilla chips.",
        "ingredients": [
            ("Avocados", 3.0, "pieces"),
            ("Lime", 1.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Serrano pepper", 1.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("Fresh cilantro", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Sopa de Lentejas",
        "description": "A hearty and affordable Mexican lentil soup with tomato, chipotle, and diced vegetables.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget", "one-pot", "high-protein"],
        "instructions": "1. Rinse lentils and set aside.\n2. Blend tomatoes, onion, garlic, and chipotle pepper until smooth.\n3. Heat oil in a pot and pour in the blended sauce, cooking for 5 minutes.\n4. Add lentils, diced carrot, diced potato, and water.\n5. Bring to a boil, then simmer for 25 minutes until lentils are tender.\n6. Season with salt and a squeeze of lime.\n7. Serve with chopped cilantro on top.",
        "ingredients": [
            ("Green lentils", 1.5, "cups"),
            ("Tomatoes", 2.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Potato", 1.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Chipotle pepper in adobo", 1.0, "pieces"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Nopales Salad",
        "description": "A refreshing cold salad of tender cooked cactus paddles with tomato, onion, cilantro, and queso fresco.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 10,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick"],
        "instructions": "1. Clean nopales by scraping off the thorns and dicing into small squares.\n2. Boil the nopales in salted water with a piece of onion for 8-10 minutes until tender.\n3. Drain and rinse thoroughly under cold water to remove the slime.\n4. Toss the cooked nopales with diced tomato, diced onion, chopped cilantro, and lime juice.\n5. Season with salt and oregano.\n6. Top with crumbled queso fresco and serve at room temperature.",
        "ingredients": [
            ("Nopales", 4.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Lime", 1.0, "pieces"),
            ("Queso fresco", 60.0, "g"),
            ("Dried oregano", 0.5, "tsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Migas",
        "description": "Scrambled eggs mixed with crispy tortilla strips, tomato, onion, and serrano pepper, a Tex-Mex breakfast staple.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "budget", "quick", "high-protein"],
        "instructions": "1. Cut corn tortillas into small strips.\n2. Fry tortilla strips in oil until crispy, then set aside on paper towels.\n3. In the same skillet, saute diced onion, tomato, and serrano pepper for 3 minutes.\n4. Beat the eggs with salt and pour into the skillet.\n5. Scramble the eggs gently, folding in the crispy tortilla strips as the eggs set.\n6. Serve immediately with warm tortillas and salsa.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Corn tortillas", 3.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Serrano pepper", 1.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Birria de Res",
        "description": "A rich and deeply spiced beef stew braised in a complex dried chile sauce, traditionally from Jalisco.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 180,
        "servings": 6,
        "tags": ["gluten-free", "high-protein", "spicy", "one-pot"],
        "instructions": "1. Toast dried guajillo, ancho, and arbol chiles in a dry skillet, then soak in hot water for 20 minutes.\n2. Blend the soaked chiles with roasted tomatoes, garlic, cumin, oregano, black pepper, cloves, and vinegar until very smooth.\n3. Strain the sauce through a sieve.\n4. Season beef chunks with salt and place in a large heavy pot.\n5. Pour the chile sauce over the beef, add bay leaves, and enough water to just cover.\n6. Cover tightly and braise in a 325F oven for 3 hours until the meat is falling apart.\n7. Shred the meat and return to the broth.\n8. Serve in bowls with diced onion, cilantro, and lime wedges.",
        "ingredients": [
            ("Beef chuck", 1.0, "kg"),
            ("Dried guajillo chiles", 5.0, "pieces"),
            ("Dried ancho chiles", 3.0, "pieces"),
            ("Dried chiles de arbol", 3.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Dried oregano", 1.0, "tsp"),
            ("Apple cider vinegar", 1.0, "tbsp"),
            ("Salt", 1.5, "tsp"),
        ],
    },
    {
        "title": "Papas con Chorizo",
        "description": "Diced potatoes fried with crumbled Mexican chorizo until crispy and well-seasoned, perfect for tacos.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["gluten-free", "budget", "quick"],
        "instructions": "1. Peel and dice potatoes into small cubes.\n2. Boil the diced potatoes in salted water until just tender, about 8 minutes, then drain.\n3. Remove chorizo from its casing and crumble into a hot skillet.\n4. Cook the chorizo until it renders its fat and crisps up, about 5 minutes.\n5. Add the parboiled potatoes to the chorizo and fry together until the potatoes are golden and crispy.\n6. Serve in warm corn tortillas with salsa and diced onion.",
        "ingredients": [
            ("Potatoes", 3.0, "pieces"),
            ("Mexican chorizo", 250.0, "g"),
            ("Corn tortillas", 8.0, "pieces"),
            ("Salsa verde", 0.5, "cups"),
            ("White onion", 0.25, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Chiles Rellenos",
        "description": "Roasted poblano peppers stuffed with queso fresco, dipped in egg batter, and fried until puffy and golden.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "budget"],
        "instructions": "1. Roast poblano peppers over an open flame until charred, then steam in a bag for 10 minutes.\n2. Peel the peppers carefully, make a small slit, and remove seeds while keeping the pepper whole.\n3. Stuff each pepper with slices of queso fresco.\n4. Separate eggs. Beat whites to stiff peaks, then fold in yolks and a tablespoon of flour.\n5. Dust stuffed peppers lightly with flour.\n6. Dip each pepper in the egg batter and fry in hot oil until golden on all sides.\n7. Drain on paper towels and serve with warm tomato sauce ladled over the top.",
        "ingredients": [
            ("Poblano peppers", 4.0, "pieces"),
            ("Queso fresco", 200.0, "g"),
            ("Eggs", 4.0, "pieces"),
            ("All-purpose flour", 2.0, "tbsp"),
            ("Tomatoes", 4.0, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Vegetable oil", 1.0, "cups"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tacos de Canasta",
        "description": "Steamed basket tacos filled with potato, beans, or chicharron, sold by street vendors across Mexico City.",
        "difficulty": "medium",
        "prep_time": 25,
        "cook_time": 20,
        "servings": 4,
        "tags": ["budget"],
        "instructions": "1. Boil and mash potatoes with salt and a bit of cooking liquid.\n2. Warm refried beans separately.\n3. Briefly dip corn tortillas in warm oil to soften them.\n4. Fill each tortilla with either mashed potato or refried beans, fold in half.\n5. Line a large pot or basket with plastic bags and a clean cloth.\n6. Pack the tacos tightly inside and cover with the cloth and another plastic bag to trap steam.\n7. Let the tacos steam and compress for at least 30 minutes before serving.",
        "ingredients": [
            ("Corn tortillas", 16.0, "pieces"),
            ("Potatoes", 3.0, "pieces"),
            ("Refried beans", 1.0, "cups"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Chipotle salsa", 0.5, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Esquites",
        "description": "Mexican street corn salad with kernels cooked in butter and epazote, served in cups with mayo, lime, and chile.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick"],
        "instructions": "1. Cut corn kernels off the cobs.\n2. Melt butter in a skillet over medium-high heat.\n3. Add corn kernels and epazote, cooking for 8 minutes until kernels are tender and slightly charred.\n4. Season with salt and a squeeze of lime.\n5. Serve in cups topped with a spoonful of mayonnaise, chile powder, and crumbled queso fresco.",
        "ingredients": [
            ("Corn on the cob", 4.0, "pieces"),
            ("Butter", 1.0, "tbsp"),
            ("Dried epazote", 0.5, "tsp"),
            ("Mayonnaise", 3.0, "tbsp"),
            ("Chile powder", 1.0, "tsp"),
            ("Queso fresco", 40.0, "g"),
            ("Lime", 1.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Carne Asada Tacos",
        "description": "Grilled marinated beef sliced thin and served on warm corn tortillas with onion, cilantro, and lime.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 10,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget", "quick"],
        "instructions": "1. Marinate flank steak with lime juice, garlic, cumin, oil, salt, and pepper for at least 30 minutes.\n2. Heat a grill or cast iron skillet to very high heat.\n3. Grill the steak for 4-5 minutes per side for medium.\n4. Let the meat rest for 5 minutes, then slice thinly against the grain.\n5. Warm corn tortillas on the grill.\n6. Serve sliced steak on tortillas topped with diced onion, fresh cilantro, and lime wedges.",
        "ingredients": [
            ("Flank steak", 500.0, "g"),
            ("Lime", 2.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Corn tortillas", 12.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Refried Beans",
        "description": "Creamy frijoles refritos made by mashing cooked pinto beans in lard with onion until thick and smooth.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "tags": ["gluten-free", "budget", "quick"],
        "instructions": "1. Heat lard in a large skillet over medium heat.\n2. Add finely diced onion and cook until translucent.\n3. Add cooked pinto beans with about half their broth.\n4. Mash the beans with a bean masher or potato masher while they cook.\n5. Continue stirring and mashing for 10 minutes until the beans reach desired consistency.\n6. Season with salt and serve as a side dish or spread on tostadas.",
        "ingredients": [
            ("Cooked pinto beans", 3.0, "cups"),
            ("Lard", 2.0, "tbsp"),
            ("White onion", 0.25, "pieces"),
            ("Bean broth", 0.5, "cups"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Elote Asado",
        "description": "Grilled Mexican street corn on the cob slathered with mayo, cotija cheese, lime, and chile powder.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "quick"],
        "instructions": "1. Shuck the corn and remove all silk.\n2. Grill corn over high heat, turning frequently, until charred in spots, about 10 minutes.\n3. Brush each ear with a thin layer of mayonnaise.\n4. Sprinkle generously with crumbled cotija cheese.\n5. Squeeze lime juice over each ear and dust with chile powder.\n6. Serve immediately on sticks or in husks.",
        "ingredients": [
            ("Corn on the cob", 4.0, "pieces"),
            ("Mayonnaise", 2.0, "tbsp"),
            ("Cotija cheese", 60.0, "g"),
            ("Lime", 1.0, "pieces"),
            ("Chile powder", 1.0, "tsp"),
            ("Salt", 0.25, "tsp"),
        ],
    },
    {
        "title": "Tortilla Soup",
        "description": "A warming Mexican soup with a rich tomato-chile broth, topped with crispy tortilla strips, avocado, and cheese.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["gluten-free", "budget", "spicy"],
        "instructions": "1. Cut corn tortillas into thin strips and fry in oil until crispy. Set aside on paper towels.\n2. Blend tomatoes, onion, garlic, and dried pasilla chile with a splash of water until smooth.\n3. Heat oil in a pot, pour in the blended sauce, and fry for 5 minutes, stirring frequently.\n4. Add chicken broth and simmer for 20 minutes.\n5. Season with salt and a squeeze of lime.\n6. Ladle the soup into bowls and top with crispy tortilla strips, diced avocado, queso fresco, and crema.",
        "ingredients": [
            ("Corn tortillas", 4.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Dried pasilla chile", 1.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Chicken broth", 4.0, "cups"),
            ("Avocado", 1.0, "pieces"),
            ("Queso fresco", 40.0, "g"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Picadillo",
        "description": "Mexican ground beef hash cooked with tomatoes, potatoes, and carrots in a savory tomato sauce.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["gluten-free", "budget", "one-pot"],
        "instructions": "1. Brown ground beef in a skillet over medium-high heat, breaking it into small pieces.\n2. Add diced onion and garlic, cooking until softened.\n3. Stir in diced potato and carrot.\n4. Add blended tomato sauce, cumin, and salt.\n5. Cover and simmer for 20 minutes until potatoes and carrots are tender.\n6. Serve with warm corn tortillas and refried beans on the side.",
        "ingredients": [
            ("Ground beef", 400.0, "g"),
            ("Potatoes", 2.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Cumin", 0.5, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Caldo de Frijol",
        "description": "A simple, soupy black bean broth served with a drizzle of crema and crumbled cheese, pure comfort food.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 3,
        "tags": ["vegetarian", "gluten-free", "budget", "quick", "one-pot"],
        "instructions": "1. Heat cooked black beans with their broth in a pot.\n2. Add a dried chile de arbol and a sprig of epazote for flavor.\n3. Simmer for 10 minutes, adding water if needed for a soupy consistency.\n4. Season with salt.\n5. Serve in bowls with a drizzle of crema, crumbled queso fresco, and a squeeze of lime.",
        "ingredients": [
            ("Cooked black beans", 2.0, "cups"),
            ("Bean broth", 2.0, "cups"),
            ("Dried chile de arbol", 1.0, "pieces"),
            ("Dried epazote", 0.5, "tsp"),
            ("Mexican crema", 2.0, "tbsp"),
            ("Queso fresco", 40.0, "g"),
            ("Lime", 1.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tacos al Pastor",
        "description": "Achiote-marinated pork tacos inspired by Lebanese-Mexican spit-roasted meat, served with pineapple and cilantro.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 25,
        "servings": 4,
        "tags": ["high-protein", "budget", "spicy"],
        "instructions": "1. Blend dried guajillo chiles, achiote paste, garlic, cumin, oregano, vinegar, and salt into a smooth marinade.\n2. Coat thinly sliced pork in the marinade and let sit for at least 1 hour.\n3. Cook the marinated pork in a very hot skillet in batches, getting good char on each piece.\n4. Dice the pineapple slices and char them briefly in the same skillet.\n5. Warm corn tortillas on a comal.\n6. Assemble tacos with the pork, charred pineapple, diced onion, and fresh cilantro.",
        "ingredients": [
            ("Pork shoulder", 500.0, "g"),
            ("Dried guajillo chiles", 4.0, "pieces"),
            ("Achiote paste", 1.0, "tbsp"),
            ("Pineapple slices", 3.0, "pieces"),
            ("Corn tortillas", 12.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Apple cider vinegar", 1.0, "tbsp"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Chilorio",
        "description": "Shredded pork simmered in a concentrated dried chile and vinegar sauce from Sinaloa, intensely flavored.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 90,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "spicy", "budget"],
        "instructions": "1. Simmer pork in salted water until very tender, about 75 minutes, then shred and reserve the broth.\n2. Toast dried ancho chiles in a dry skillet, then soak in hot water for 15 minutes.\n3. Blend soaked chiles with garlic, cumin, oregano, vinegar, and a splash of broth until smooth.\n4. Fry the shredded pork in lard until slightly crispy.\n5. Pour the chile sauce over the pork and cook, stirring, for 10 minutes until the sauce is absorbed.\n6. Serve in warm tortillas or as a filling for burritos.",
        "ingredients": [
            ("Pork shoulder", 500.0, "g"),
            ("Dried ancho chiles", 5.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Dried oregano", 0.5, "tsp"),
            ("Apple cider vinegar", 2.0, "tbsp"),
            ("Lard", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Huevos a la Mexicana",
        "description": "Scrambled eggs cooked with the colors of the Mexican flag: diced tomato, white onion, and green serrano pepper.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 8,
        "servings": 2,
        "tags": ["vegetarian", "gluten-free", "budget", "quick", "high-protein"],
        "instructions": "1. Dice the tomato, onion, and serrano pepper into small pieces.\n2. Heat oil in a skillet over medium heat.\n3. Saute the onion and serrano for 2 minutes until softened.\n4. Add the diced tomato and cook for 1 minute.\n5. Beat the eggs with salt and pour into the skillet.\n6. Scramble gently until just set, keeping them soft and creamy.\n7. Serve immediately with warm tortillas and refried beans.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Serrano pepper", 1.0, "pieces"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tinga de Res",
        "description": "Slow-cooked shredded beef in a smoky chipotle-tomato sauce with sliced onions.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 120,
        "servings": 6,
        "tags": ["gluten-free", "high-protein", "spicy", "budget"],
        "instructions": "1. Place beef brisket in a pot, cover with water, add half the onion and garlic, and simmer for 2 hours until very tender.\n2. Shred the beef and reserve some cooking liquid.\n3. Blend tomatoes, chipotle peppers, and garlic until smooth.\n4. Saute sliced onion in oil until golden.\n5. Pour in the chipotle-tomato sauce and cook for 5 minutes.\n6. Add shredded beef and a splash of cooking liquid, simmer for 15 minutes.\n7. Serve on tostadas or in tacos with avocado slices.",
        "ingredients": [
            ("Beef brisket", 600.0, "g"),
            ("Tomatoes", 3.0, "pieces"),
            ("Chipotle peppers in adobo", 3.0, "pieces"),
            ("White onion", 1.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Pico de Gallo",
        "description": "A fresh and vibrant raw salsa of diced tomato, onion, cilantro, serrano chile, and lime juice.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Dice the tomatoes into small uniform cubes, discarding excess seeds and juice.\n2. Finely dice the white onion.\n3. Mince the serrano pepper, removing seeds for less heat if desired.\n4. Chop fresh cilantro.\n5. Combine all ingredients in a bowl, squeeze lime juice over the top, and season with salt.\n6. Toss gently and let sit 10 minutes before serving.",
        "ingredients": [
            ("Tomatoes", 3.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Serrano pepper", 1.0, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Lime", 1.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Enchiladas Suizas",
        "description": "Chicken enchiladas covered in a creamy tomatillo sauce and melted cheese, Swiss-style from Mexico City.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 30,
        "servings": 4,
        "tags": ["high-protein", "budget"],
        "instructions": "1. Boil tomatillos, serrano peppers, and garlic until soft, about 10 minutes.\n2. Blend the boiled vegetables with crema and cilantro until smooth.\n3. Shred cooked chicken and season with salt.\n4. Dip tortillas in a bit of the sauce, fill with chicken, and roll up.\n5. Place seam-side down in a baking dish, pour remaining sauce over the top.\n6. Sprinkle with shredded Chihuahua cheese.\n7. Bake at 375F for 20 minutes until bubbly and golden on top.",
        "ingredients": [
            ("Chicken breast", 400.0, "g"),
            ("Tomatillos", 8.0, "pieces"),
            ("Serrano peppers", 2.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Mexican crema", 0.5, "cups"),
            ("Corn tortillas", 12.0, "pieces"),
            ("Chihuahua cheese", 150.0, "g"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Pozole Verde",
        "description": "A green version of the classic Mexican hominy soup, made with tomatillos, pepitas, and green chiles.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 120,
        "servings": 6,
        "tags": ["gluten-free", "one-pot", "high-protein"],
        "instructions": "1. Simmer pork shoulder in salted water with onion and garlic until tender, about 90 minutes.\n2. Toast pepitas in a dry skillet until they puff.\n3. Boil tomatillos, poblano peppers, serrano peppers, and garlic until soft.\n4. Blend the boiled greens with toasted pepitas, cilantro, and a cup of broth until very smooth.\n5. Shred the pork and return to the broth. Add drained hominy and the green sauce.\n6. Simmer for 30 minutes, season with salt.\n7. Serve with shredded cabbage, sliced radishes, diced onion, and oregano.",
        "ingredients": [
            ("Pork shoulder", 700.0, "g"),
            ("Canned hominy", 3.0, "cups"),
            ("Tomatillos", 6.0, "pieces"),
            ("Poblano peppers", 2.0, "pieces"),
            ("Serrano peppers", 2.0, "pieces"),
            ("Pepitas", 0.5, "cups"),
            ("Fresh cilantro", 0.5, "cups"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Radishes", 4.0, "pieces"),
            ("Salt", 1.5, "tsp"),
        ],
    },
    {
        "title": "Chicharron en Salsa Verde",
        "description": "Pork cracklings simmered in tangy tomatillo salsa until softened, served with warm tortillas.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["gluten-free", "budget", "quick"],
        "instructions": "1. Boil tomatillos, serrano peppers, and garlic until soft, about 10 minutes.\n2. Blend into a smooth salsa verde with cilantro and salt.\n3. Heat oil in a skillet and pour in the salsa, cooking for 5 minutes.\n4. Break the chicharron into bite-size pieces and add to the simmering salsa.\n5. Cook for 10 minutes until the chicharron softens and absorbs the sauce.\n6. Serve with warm corn tortillas.",
        "ingredients": [
            ("Chicharron", 150.0, "g"),
            ("Tomatillos", 6.0, "pieces"),
            ("Serrano peppers", 2.0, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("Fresh cilantro", 2.0, "tbsp"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Corn tortillas", 8.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Albondigas Soup",
        "description": "Mexican meatball soup with tender beef and rice meatballs simmered in a light tomato broth with vegetables.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 35,
        "servings": 4,
        "tags": ["one-pot", "budget", "high-protein"],
        "instructions": "1. Mix ground beef with cooked rice, egg, chopped mint, garlic, salt, and pepper to form meatballs.\n2. Blend tomatoes with onion and garlic until smooth.\n3. Heat oil in a pot, pour in the tomato sauce, and cook for 5 minutes.\n4. Add water or broth and bring to a boil.\n5. Add diced carrots, potatoes, and zucchini to the broth.\n6. Gently drop in the meatballs one at a time.\n7. Simmer for 25 minutes until meatballs are cooked through and vegetables are tender.\n8. Garnish with fresh cilantro and serve with lime wedges.",
        "ingredients": [
            ("Ground beef", 400.0, "g"),
            ("Cooked rice", 0.5, "cups"),
            ("Egg", 1.0, "pieces"),
            ("Fresh mint", 2.0, "tbsp"),
            ("Tomatoes", 2.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Potato", 1.0, "pieces"),
            ("Zucchini", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Machaca con Huevo",
        "description": "Shredded dried beef rehydrated and scrambled with eggs, onion, tomato, and peppers, a northern Mexico classic.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 3,
        "tags": ["gluten-free", "high-protein", "budget", "quick"],
        "instructions": "1. Shred the dried beef and soak briefly in warm water to soften, then drain.\n2. Heat oil in a skillet and saute diced onion and serrano pepper until softened.\n3. Add diced tomato and the shredded beef, cooking for 5 minutes.\n4. Beat eggs with salt and pour over the beef mixture.\n5. Scramble everything together until the eggs are set.\n6. Serve immediately with flour tortillas and refried beans.",
        "ingredients": [
            ("Dried beef machaca", 150.0, "g"),
            ("Eggs", 4.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("White onion", 0.5, "pieces"),
            ("Serrano pepper", 1.0, "pieces"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Flour tortillas", 4.0, "pieces"),
            ("Salt", 0.25, "tsp"),
        ],
    },
    {
        "title": "Tacos Dorados de Pollo",
        "description": "Golden fried chicken tacos rolled tight and fried until extra crispy, served with all the toppings.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "tags": ["budget", "high-protein"],
        "instructions": "1. Shred cooked chicken and season with salt, cumin, and lime juice.\n2. Warm corn tortillas briefly so they become pliable.\n3. Place a line of shredded chicken along each tortilla and roll tightly.\n4. Secure each rolled taco with a toothpick.\n5. Fry in hot oil, turning occasionally, until golden and crisp, about 4 minutes.\n6. Remove toothpicks and drain on paper towels.\n7. Serve on a platter with shredded lettuce, diced tomato, crema, and salsa.",
        "ingredients": [
            ("Chicken breast", 400.0, "g"),
            ("Corn tortillas", 12.0, "pieces"),
            ("Vegetable oil", 1.0, "cups"),
            ("Lettuce", 2.0, "cups"),
            ("Tomato", 1.0, "pieces"),
            ("Mexican crema", 3.0, "tbsp"),
            ("Cumin", 0.5, "tsp"),
            ("Lime", 1.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Mole Verde",
        "description": "A bright green mole sauce made from tomatillos, pepitas, herbs, and green chiles served over chicken.",
        "difficulty": "hard",
        "prep_time": 25,
        "cook_time": 40,
        "servings": 6,
        "tags": ["gluten-free", "high-protein"],
        "instructions": "1. Toast pepitas in a dry skillet until they start to pop.\n2. Boil tomatillos, poblano peppers, serrano peppers, and garlic until soft.\n3. Blend boiled vegetables with toasted pepitas, cilantro, lettuce leaves, cumin, and a cup of broth until very smooth.\n4. Heat oil in a pot and pour in the green sauce, stirring constantly for 5 minutes.\n5. Add chicken broth to thin the sauce to desired consistency.\n6. Season with salt and simmer for 20 minutes.\n7. Add poached chicken pieces and cook for 10 more minutes.\n8. Serve with white rice and warm tortillas.",
        "ingredients": [
            ("Chicken pieces", 800.0, "g"),
            ("Tomatillos", 6.0, "pieces"),
            ("Poblano peppers", 2.0, "pieces"),
            ("Serrano peppers", 2.0, "pieces"),
            ("Pepitas", 0.5, "cups"),
            ("Fresh cilantro", 0.5, "cups"),
            ("Lettuce leaves", 3.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Arroz con Pollo",
        "description": "A one-pot Mexican chicken and rice dish cooked in a tomato and chicken broth with vegetables.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 4,
        "tags": ["gluten-free", "budget", "one-pot", "high-protein"],
        "instructions": "1. Season chicken pieces with salt, cumin, and garlic powder.\n2. Brown the chicken in oil in a large pot, then remove and set aside.\n3. In the same pot, toast the rice in the remaining oil until golden.\n4. Blend tomatoes with onion and garlic, pour over the rice and stir.\n5. Add chicken broth and bring to a boil, then return the chicken pieces.\n6. Cover tightly, reduce heat to low, and cook for 25 minutes.\n7. Fluff the rice and serve garnished with fresh cilantro.",
        "ingredients": [
            ("Chicken thighs", 600.0, "g"),
            ("Long grain white rice", 1.5, "cups"),
            ("Tomatoes", 2.0, "pieces"),
            ("Chicken broth", 2.5, "cups"),
            ("White onion", 0.5, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Fresh cilantro", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Salsa Verde Cruda",
        "description": "A vibrant raw tomatillo salsa with serrano chiles and cilantro, tangy and fresh, ready in minutes.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "quick"],
        "instructions": "1. Remove the papery husks from the tomatillos and rinse off any stickiness.\n2. Roughly chop tomatillos, onion, and serrano peppers.\n3. Place all ingredients in a blender with cilantro, lime juice, and salt.\n4. Blend until you reach desired consistency, chunky or smooth.\n5. Taste and adjust salt and lime.\n6. Serve immediately or refrigerate for up to a week.",
        "ingredients": [
            ("Tomatillos", 6.0, "pieces"),
            ("Serrano peppers", 2.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Lime", 0.5, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Carne Guisada",
        "description": "Tender chunks of beef simmered in a flavorful tomato and chile gravy, a home-style Mexican stew.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 90,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget", "one-pot"],
        "instructions": "1. Cut beef into bite-sized cubes and season with salt, cumin, and black pepper.\n2. Brown the beef in oil in a heavy pot over high heat, working in batches.\n3. Saute diced onion and garlic in the same pot until softened.\n4. Add diced tomatoes and sliced jalapeno, cooking for 3 minutes.\n5. Return the beef to the pot and add enough water to just cover.\n6. Bring to a boil, then reduce to a simmer, cover, and cook for 75 minutes until beef is very tender.\n7. Adjust seasoning and serve with warm tortillas and rice.",
        "ingredients": [
            ("Beef chuck", 500.0, "g"),
            ("Tomatoes", 2.0, "pieces"),
            ("White onion", 1.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Jalapeno pepper", 1.0, "pieces"),
            ("Cumin", 1.0, "tsp"),
            ("Black pepper", 0.5, "tsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Chicken Tinga Tostadas",
        "description": "Crispy tostadas loaded with smoky chipotle chicken tinga, avocado, and a drizzle of crema.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "tags": ["budget", "high-protein", "spicy"],
        "instructions": "1. Poach chicken thighs in salted water with garlic until cooked, about 20 minutes.\n2. Shred the chicken with two forks.\n3. Blend tomatoes, chipotle peppers, and garlic until smooth.\n4. Saute sliced onion in oil, add the sauce, and cook for 5 minutes.\n5. Add shredded chicken and simmer until the sauce thickens, about 10 minutes.\n6. Spread refried beans on tostada shells, top with chicken tinga.\n7. Garnish with sliced avocado, crema, and fresh cilantro.",
        "ingredients": [
            ("Chicken thighs", 400.0, "g"),
            ("Tostada shells", 8.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Chipotle peppers in adobo", 2.0, "pieces"),
            ("White onion", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Avocado", 1.0, "pieces"),
            ("Refried beans", 0.5, "cups"),
            ("Mexican crema", 3.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Chayotes Rellenos",
        "description": "Baked chayote squash halves stuffed with a savory cheese and egg filling, a traditional side dish.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget"],
        "instructions": "1. Halve the chayotes and boil in salted water until tender, about 20 minutes.\n2. Scoop out the flesh, leaving a shell, and chop the flesh.\n3. Saute onion and garlic in butter until soft.\n4. Add the chopped chayote flesh and cook for 3 minutes.\n5. Remove from heat and mix in beaten egg and shredded cheese.\n6. Fill the chayote shells with the mixture and place in a baking dish.\n7. Bake at 375F for 20 minutes until golden on top.",
        "ingredients": [
            ("Chayotes", 4.0, "pieces"),
            ("Chihuahua cheese", 100.0, "g"),
            ("Egg", 1.0, "pieces"),
            ("White onion", 0.25, "pieces"),
            ("Garlic cloves", 1.0, "pieces"),
            ("Butter", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Bean and Cheese Burritos",
        "description": "Flour tortillas filled with creamy refried beans and melted cheese, simple and deeply satisfying.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "budget", "quick"],
        "instructions": "1. Warm refried beans in a small pot, stirring until smooth.\n2. Heat flour tortillas on a dry skillet to make them pliable.\n3. Spread a thick layer of refried beans down the center of each tortilla.\n4. Sprinkle generously with shredded Oaxaca cheese.\n5. Fold the sides in, then roll the tortilla from bottom to top into a tight burrito.\n6. Place seam-side down on the skillet and toast until the cheese melts and the tortilla is golden.",
        "ingredients": [
            ("Flour tortillas", 4.0, "pieces"),
            ("Refried beans", 1.5, "cups"),
            ("Oaxaca cheese", 150.0, "g"),
            ("Salsa roja", 0.25, "cups"),
            ("Salt", 0.25, "tsp"),
        ],
    },
]
