ASIAN_RECIPES = [
    # =========================================================================
    # CHINESE (recipes 1-10)
    # =========================================================================
    {
        "title": "Egg Fried Rice",
        "description": "Classic Chinese stir-fried rice with eggs and scallions. A staple that turns leftover rice into a satisfying meal.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "quick", "stir-fry", "budget"],
        "instructions": "1. Beat eggs in a bowl and season with a pinch of salt.\n2. Heat vegetable oil in a wok over high heat until smoking.\n3. Pour in eggs and scramble for 30 seconds until just set, then remove.\n4. Add a bit more oil, then add cold cooked rice and stir-fry for 3 minutes, breaking up clumps.\n5. Add soy sauce and white pepper, tossing to coat evenly.\n6. Return scrambled eggs to the wok and toss to combine.\n7. Stir in chopped scallions and serve immediately.",
        "ingredients": [
            ("Cooked white rice", 3.0, "cups"),
            ("Eggs", 3.0, "pieces"),
            ("Scallions", 3.0, "pieces"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("White pepper", 0.25, "tsp"),
            ("Salt", 1.0, "pinch"),
        ],
    },
    {
        "title": "Mapo Tofu",
        "description": "Fiery Sichuan tofu dish with ground pork in a numbing chili bean paste sauce. Deeply savory and intensely flavorful.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["spicy", "high-protein", "budget", "quick"],
        "instructions": "1. Cut tofu into 1-inch cubes and gently blanch in salted boiling water for 2 minutes, then drain.\n2. Heat oil in a wok over medium-high heat and brown the ground pork, breaking it into small pieces.\n3. Push pork to the side and add doubanjiang, stirring until the oil turns red and fragrant.\n4. Add minced garlic, ginger, and Sichuan peppercorns, stir-frying for 30 seconds.\n5. Pour in the chicken broth and bring to a simmer.\n6. Gently slide tofu cubes into the sauce and simmer for 5 minutes without stirring.\n7. Mix cornstarch with 2 tablespoons of water and stir into the sauce to thicken.\n8. Garnish with sliced scallions and serve over steamed rice.",
        "ingredients": [
            ("Firm tofu", 400.0, "g"),
            ("Ground pork", 150.0, "g"),
            ("Doubanjiang (chili bean paste)", 2.0, "tbsp"),
            ("Garlic", 3.0, "pieces"),
            ("Ginger", 1.0, "tbsp"),
            ("Sichuan peppercorns", 1.0, "tsp"),
            ("Chicken broth", 200.0, "ml"),
            ("Cornstarch", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Scallions", 2.0, "pieces"),
        ],
    },
    {
        "title": "Congee with Chicken",
        "description": "Comforting Chinese rice porridge slow-cooked until silky smooth, topped with shredded chicken and ginger.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 60,
        "servings": 4,
        "tags": ["one-pot", "soup", "budget", "gluten-free"],
        "instructions": "1. Rinse rice thoroughly and place in a large pot with chicken broth and water.\n2. Add chicken thighs, sliced ginger, and a pinch of salt.\n3. Bring to a boil, then reduce heat to low and simmer, stirring occasionally, for 50-60 minutes until the rice has broken down into a thick porridge.\n4. Remove chicken thighs and shred the meat with two forks.\n5. Return shredded chicken to the congee and stir to combine.\n6. Season with white pepper and soy sauce to taste.\n7. Serve in bowls topped with sliced scallions and a drizzle of sesame oil.",
        "ingredients": [
            ("Jasmine rice", 1.0, "cups"),
            ("Chicken thighs", 300.0, "g"),
            ("Chicken broth", 1.0, "l"),
            ("Water", 500.0, "ml"),
            ("Ginger", 30.0, "g"),
            ("Scallions", 2.0, "pieces"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Sesame oil", 1.0, "tsp"),
            ("White pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tomato Egg Stir-Fry",
        "description": "A beloved home-style Chinese dish of fluffy scrambled eggs in a tangy tomato sauce. Simple, fast, and universally loved.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "quick", "stir-fry", "budget"],
        "instructions": "1. Cut tomatoes into wedges and beat eggs with a pinch of salt.\n2. Heat oil in a wok over high heat and scramble the eggs until just set, then remove.\n3. Add a little more oil and stir-fry the tomato wedges for 3-4 minutes until they soften and release their juices.\n4. Add tomato paste and a splash of water, stirring to create a sauce.\n5. Return scrambled eggs to the wok and gently fold into the tomato sauce.\n6. Season with salt and white pepper to taste.\n7. Garnish with sliced scallions and serve with steamed rice.",
        "ingredients": [
            ("Tomatoes", 4.0, "pieces"),
            ("Eggs", 4.0, "pieces"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Scallions", 2.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "pinch"),
            ("White pepper", 0.25, "tsp"),
        ],
    },
    {
        "title": "Chinese Stir-Fried Cabbage with Garlic",
        "description": "Crunchy Napa cabbage stir-fried with garlic and dried chilies in a savory soy-based sauce. A classic Chinese side dish.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 8,
        "servings": 3,
        "tags": ["vegetarian", "vegan", "quick", "stir-fry", "budget", "gluten-free"],
        "instructions": "1. Separate Napa cabbage leaves, wash, and cut into 2-inch pieces, keeping stems and leaves separate.\n2. Slice garlic and cut dried chilies into pieces.\n3. Heat oil in a wok over high heat until smoking.\n4. Add dried chilies and garlic, stir-frying for 15 seconds until fragrant.\n5. Add cabbage stems first and stir-fry for 2 minutes.\n6. Add cabbage leaves, soy sauce, and rice vinegar, tossing for another 2 minutes until just wilted but still crisp.\n7. Season with salt to taste and serve immediately.",
        "ingredients": [
            ("Napa cabbage", 500.0, "g"),
            ("Garlic", 4.0, "pieces"),
            ("Dried red chilies", 4.0, "pieces"),
            ("Soy sauce", 1.5, "tbsp"),
            ("Rice vinegar", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "pinch"),
        ],
    },
    {
        "title": "Hot and Sour Soup",
        "description": "A tangy and spicy Chinese soup loaded with tofu, mushrooms, and egg ribbons thickened with cornstarch.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "tags": ["soup", "spicy", "budget", "high-protein"],
        "instructions": "1. Slice mushrooms, cut tofu into thin strips, and shred bamboo shoots.\n2. Bring chicken broth to a boil in a pot.\n3. Add mushrooms and bamboo shoots, simmer for 5 minutes.\n4. Add tofu strips, soy sauce, rice vinegar, and white pepper.\n5. Mix cornstarch with water and stir into the soup to thicken.\n6. Slowly drizzle beaten egg into the simmering soup while stirring gently to form ribbons.\n7. Add sesame oil and adjust seasoning with salt and more vinegar if needed.\n8. Serve hot, garnished with chopped scallions.",
        "ingredients": [
            ("Chicken broth", 1.0, "l"),
            ("Firm tofu", 200.0, "g"),
            ("Dried shiitake mushrooms", 6.0, "pieces"),
            ("Bamboo shoots", 100.0, "g"),
            ("Rice vinegar", 3.0, "tbsp"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Cornstarch", 2.0, "tbsp"),
            ("Eggs", 2.0, "pieces"),
            ("Sesame oil", 1.0, "tsp"),
            ("White pepper", 1.0, "tsp"),
        ],
    },
    {
        "title": "Garlic Soy Chicken Thighs",
        "description": "Braised chicken thighs in a rich garlic and soy sauce. Tender, deeply savory, and incredibly cheap to make.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["high-protein", "budget", "one-pot", "gluten-free"],
        "instructions": "1. Score chicken thighs with shallow cuts and season with salt.\n2. Heat oil in a pan and sear chicken thighs skin-side down for 5 minutes until golden.\n3. Flip and sear the other side for 3 minutes.\n4. Add sliced garlic, ginger, and soy sauce.\n5. Pour in water, bring to a simmer, and cover.\n6. Braise on low heat for 20 minutes, flipping halfway, until chicken is cooked through.\n7. Remove lid, increase heat, and reduce the sauce until glossy.\n8. Serve over rice with the pan sauce spooned on top.",
        "ingredients": [
            ("Chicken thighs", 600.0, "g"),
            ("Garlic", 8.0, "pieces"),
            ("Ginger", 20.0, "g"),
            ("Soy sauce", 3.0, "tbsp"),
            ("Water", 200.0, "ml"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Salt", 1.0, "pinch"),
        ],
    },
    {
        "title": "Dan Dan Noodles",
        "description": "Sichuan street food classic with wheat noodles, spicy pork, and a bold sesame-chili sauce.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 2,
        "tags": ["spicy", "budget", "high-protein", "quick"],
        "instructions": "1. Cook noodles according to package directions, drain, and set aside.\n2. Heat oil in a wok and brown ground pork with a pinch of salt.\n3. Add Sichuan preserved vegetables and stir-fry for 1 minute.\n4. In each serving bowl, combine tahini, soy sauce, chili oil, and rice vinegar.\n5. Ladle a splash of hot noodle cooking water into each bowl and stir to make the sauce.\n6. Add drained noodles to the bowls and toss to coat.\n7. Top with the cooked pork mixture and chopped scallions.",
        "ingredients": [
            ("Dried wheat noodles", 200.0, "g"),
            ("Ground pork", 150.0, "g"),
            ("Tahini (or sesame paste)", 2.0, "tbsp"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Chili oil", 2.0, "tbsp"),
            ("Rice vinegar", 1.0, "tbsp"),
            ("Sichuan preserved vegetables", 30.0, "g"),
            ("Scallions", 2.0, "pieces"),
            ("Vegetable oil", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Chinese Steamed Eggs",
        "description": "Silky smooth steamed egg custard seasoned with soy sauce and sesame oil. A gentle, comforting side dish.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 12,
        "servings": 2,
        "tags": ["vegetarian", "quick", "budget", "gluten-free"],
        "instructions": "1. Beat eggs gently in a bowl and mix with warm water in a 1:1.5 ratio.\n2. Strain the egg mixture through a fine sieve into a heatproof bowl to remove bubbles.\n3. Cover the bowl tightly with plastic wrap or a plate.\n4. Place in a steamer over simmering water and steam on medium-low heat for 10-12 minutes.\n5. The custard is done when the surface is set but still jiggles slightly.\n6. Drizzle soy sauce and sesame oil over the top and serve warm.",
        "ingredients": [
            ("Eggs", 3.0, "pieces"),
            ("Warm water", 270.0, "ml"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Sesame oil", 0.5, "tsp"),
            ("Salt", 1.0, "pinch"),
        ],
    },
    {
        "title": "Stir-Fried Bok Choy with Garlic",
        "description": "Crisp-tender baby bok choy quickly stir-fried with garlic. One of the simplest and most satisfying Chinese vegetable dishes.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 5,
        "servings": 2,
        "tags": ["vegetarian", "vegan", "quick", "stir-fry", "budget", "gluten-free"],
        "instructions": "1. Wash bok choy thoroughly and halve the larger heads lengthwise.\n2. Mince garlic cloves.\n3. Heat oil in a wok over high heat until smoking.\n4. Add garlic and stir-fry for 10 seconds until fragrant.\n5. Add bok choy stems first, tossing for 1 minute.\n6. Add the leafy tops, soy sauce, and a splash of water, then stir-fry for another 1-2 minutes until wilted but still bright green.\n7. Season with salt and serve immediately.",
        "ingredients": [
            ("Baby bok choy", 400.0, "g"),
            ("Garlic", 4.0, "pieces"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Vegetable oil", 1.5, "tbsp"),
            ("Water", 2.0, "tbsp"),
            ("Salt", 1.0, "pinch"),
        ],
    },
    # =========================================================================
    # THAI (recipes 11-18)
    # =========================================================================
    {
        "title": "Tom Yum Soup",
        "description": "Thailand's iconic hot and sour shrimp soup with lemongrass, galangal, and lime. Bright, aromatic, and intensely flavorful.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "tags": ["soup", "spicy", "gluten-free", "budget"],
        "instructions": "1. Bring water to a boil and add smashed lemongrass stalks, sliced galangal, and torn kaffir lime leaves.\n2. Simmer aromatics for 10 minutes to infuse the broth.\n3. Add sliced mushrooms and cook for 3 minutes.\n4. Add shrimp and cook for 2-3 minutes until pink.\n5. Remove from heat and stir in fish sauce, lime juice, and Thai chilies.\n6. Taste and adjust the balance of sour, salty, and spicy.\n7. Serve immediately, garnished with fresh cilantro leaves.",
        "ingredients": [
            ("Shrimp", 300.0, "g"),
            ("Water", 1.0, "l"),
            ("Lemongrass stalks", 3.0, "pieces"),
            ("Galangal", 30.0, "g"),
            ("Kaffir lime leaves", 5.0, "pieces"),
            ("Mushrooms", 150.0, "g"),
            ("Fish sauce", 3.0, "tbsp"),
            ("Lime juice", 3.0, "tbsp"),
            ("Thai chilies", 5.0, "pieces"),
            ("Cilantro", 0.25, "cups"),
        ],
    },
    {
        "title": "Pad Krapow (Thai Basil Stir-Fry)",
        "description": "Thai street food staple of ground pork stir-fried with holy basil, chilies, and garlic. Best served over rice with a fried egg.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["spicy", "quick", "stir-fry", "budget", "high-protein"],
        "instructions": "1. Pound garlic and Thai chilies together in a mortar into a rough paste.\n2. Heat oil in a wok over high heat.\n3. Add the garlic-chili paste and stir-fry for 15 seconds.\n4. Add ground pork and stir-fry, breaking it up, for 4-5 minutes until cooked.\n5. Add soy sauce and fish sauce, tossing to combine.\n6. Turn off heat and fold in Thai basil leaves until just wilted.\n7. Serve over steamed jasmine rice, topped with a fried egg.",
        "ingredients": [
            ("Ground pork", 300.0, "g"),
            ("Thai basil leaves", 1.0, "cups"),
            ("Garlic", 6.0, "pieces"),
            ("Thai chilies", 4.0, "pieces"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Fish sauce", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Green Curry with Chicken",
        "description": "Aromatic Thai green curry with tender chicken, bamboo shoots, and Thai basil in a rich coconut milk sauce.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "tags": ["spicy", "one-pot", "gluten-free", "budget"],
        "instructions": "1. Slice chicken thighs into bite-sized pieces.\n2. Heat the thick cream from the top of the coconut milk in a pot over medium heat.\n3. Add green curry paste and fry for 2 minutes until fragrant and the oil splits.\n4. Add chicken pieces and stir to coat in the paste for 3 minutes.\n5. Pour in the remaining coconut milk and bamboo shoots, bring to a simmer.\n6. Cook for 15 minutes until chicken is tender.\n7. Add fish sauce, Thai basil leaves, and sliced kaffir lime leaves.\n8. Serve over steamed jasmine rice.",
        "ingredients": [
            ("Chicken thighs", 400.0, "g"),
            ("Coconut milk", 400.0, "ml"),
            ("Green curry paste", 3.0, "tbsp"),
            ("Bamboo shoots", 100.0, "g"),
            ("Fish sauce", 2.0, "tbsp"),
            ("Thai basil leaves", 0.5, "cups"),
            ("Kaffir lime leaves", 3.0, "pieces"),
        ],
    },
    {
        "title": "Pad See Ew",
        "description": "Thai stir-fried wide rice noodles with Chinese broccoli, egg, and dark soy sauce. Smoky, savory, and satisfying.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 2,
        "tags": ["stir-fry", "quick", "budget", "high-protein"],
        "instructions": "1. Soak wide rice noodles in warm water for 20 minutes if dried, then drain.\n2. Cut Chinese broccoli into 2-inch pieces, separating stems and leaves.\n3. Heat oil in a wok over the highest heat until smoking.\n4. Add sliced chicken and stir-fry for 2 minutes until seared.\n5. Push chicken aside, crack in the egg, and scramble briefly.\n6. Add noodles, dark soy sauce, and soy sauce, tossing vigorously for 2 minutes.\n7. Add Chinese broccoli stems, then leaves, tossing for 1 more minute.\n8. Serve immediately with a squeeze of lime.",
        "ingredients": [
            ("Wide rice noodles", 200.0, "g"),
            ("Chicken thigh", 150.0, "g"),
            ("Chinese broccoli", 200.0, "g"),
            ("Egg", 1.0, "pieces"),
            ("Dark soy sauce", 2.0, "tbsp"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Garlic", 3.0, "pieces"),
        ],
    },
    {
        "title": "Thai Egg Omelette (Khai Jiao)",
        "description": "A puffy, crispy Thai-style omelette deep-fried in a wok. Crunchy outside, fluffy inside, served over rice with sriracha.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 5,
        "servings": 2,
        "tags": ["vegetarian", "quick", "budget", "high-protein"],
        "instructions": "1. Beat eggs vigorously in a bowl until very frothy.\n2. Add fish sauce and white pepper to the eggs and beat again.\n3. Heat generous oil in a wok over high heat until shimmering.\n4. Pour egg mixture into the hot oil in one go.\n5. Let it puff up and fry for 1-2 minutes until golden and crispy on the bottom.\n6. Flip once and fry for another minute.\n7. Drain on paper towels and serve over jasmine rice.",
        "ingredients": [
            ("Eggs", 3.0, "pieces"),
            ("Fish sauce", 1.0, "tbsp"),
            ("White pepper", 0.25, "tsp"),
            ("Vegetable oil", 60.0, "ml"),
        ],
    },
    {
        "title": "Tom Kha Gai",
        "description": "Creamy Thai coconut soup with chicken, galangal, and lemongrass. Milder than tom yum, with a rich coconut base.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["soup", "gluten-free", "one-pot", "budget"],
        "instructions": "1. Slice chicken into thin strips.\n2. Bring coconut milk and water to a gentle simmer in a pot.\n3. Add smashed lemongrass, sliced galangal, and torn kaffir lime leaves.\n4. Simmer for 10 minutes to infuse the broth.\n5. Add chicken strips and mushrooms, cook for 5-7 minutes until chicken is done.\n6. Remove from heat and stir in fish sauce and lime juice.\n7. Garnish with cilantro and sliced Thai chilies.\n8. Serve in bowls as a soup or over rice.",
        "ingredients": [
            ("Chicken thighs", 300.0, "g"),
            ("Coconut milk", 400.0, "ml"),
            ("Water", 250.0, "ml"),
            ("Lemongrass stalks", 2.0, "pieces"),
            ("Galangal", 20.0, "g"),
            ("Kaffir lime leaves", 4.0, "pieces"),
            ("Mushrooms", 150.0, "g"),
            ("Fish sauce", 2.0, "tbsp"),
            ("Lime juice", 3.0, "tbsp"),
            ("Cilantro", 0.25, "cups"),
        ],
    },
    {
        "title": "Thai Larb (Meat Salad)",
        "description": "A zesty Thai salad of minced pork with toasted rice powder, lime, fish sauce, and fresh herbs. Served with lettuce cups.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 3,
        "tags": ["spicy", "gluten-free", "quick", "budget", "high-protein"],
        "instructions": "1. Toast uncooked sticky rice in a dry pan until golden, then grind into a coarse powder.\n2. Cook ground pork in a pan without oil, breaking it up until no longer pink.\n3. Remove from heat and add fish sauce, lime juice, and chili flakes.\n4. Add sliced shallots, chopped cilantro, and mint leaves.\n5. Sprinkle toasted rice powder over the mixture and toss everything together.\n6. Serve in lettuce cups or with steamed sticky rice.",
        "ingredients": [
            ("Ground pork", 300.0, "g"),
            ("Shallots", 3.0, "pieces"),
            ("Lime juice", 3.0, "tbsp"),
            ("Fish sauce", 2.0, "tbsp"),
            ("Dried chili flakes", 1.0, "tsp"),
            ("Mint leaves", 0.5, "cups"),
            ("Cilantro", 0.25, "cups"),
            ("Uncooked sticky rice", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Thai Stir-Fried Morning Glory",
        "description": "Pad pak boong: water spinach flash-fried with garlic, chilies, and fermented soybean paste. A beloved Thai side dish.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 3,
        "servings": 2,
        "tags": ["vegetarian", "vegan", "quick", "stir-fry", "budget", "gluten-free"],
        "instructions": "1. Wash morning glory and cut into 3-inch pieces.\n2. Pound garlic and Thai chilies in a mortar to a rough paste.\n3. Heat oil in a wok over the highest heat until smoking.\n4. Add garlic-chili paste and stir-fry for 5 seconds.\n5. Add morning glory and toss rapidly for 30 seconds.\n6. Add soy sauce and fermented soybean paste, tossing for another 30 seconds until just wilted.\n7. Serve immediately while still vibrant green.",
        "ingredients": [
            ("Morning glory (water spinach)", 300.0, "g"),
            ("Garlic", 5.0, "pieces"),
            ("Thai chilies", 3.0, "pieces"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Fermented soybean paste", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
        ],
    },
    # =========================================================================
    # JAPANESE (recipes 19-26)
    # =========================================================================
    {
        "title": "Miso Soup",
        "description": "Essential Japanese soup made from dashi broth and miso paste with tofu and wakame seaweed. Served with every Japanese meal.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 4,
        "tags": ["vegetarian", "soup", "quick", "budget", "gluten-free"],
        "instructions": "1. Soak dried wakame seaweed in water for 5 minutes, then drain.\n2. Bring dashi stock to a gentle simmer in a pot.\n3. Cut tofu into small cubes and add to the broth.\n4. Add the rehydrated wakame.\n5. Remove pot from heat and dissolve miso paste into the broth using a ladle and chopsticks.\n6. Serve immediately in small bowls, garnished with sliced scallions.",
        "ingredients": [
            ("Dashi stock", 800.0, "ml"),
            ("Miso paste", 3.0, "tbsp"),
            ("Silken tofu", 150.0, "g"),
            ("Dried wakame seaweed", 5.0, "g"),
            ("Scallions", 2.0, "pieces"),
        ],
    },
    {
        "title": "Oyakodon (Chicken and Egg Rice Bowl)",
        "description": "A classic Japanese donburi of chicken and onion simmered in dashi broth, finished with soft-set eggs over rice.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 2,
        "tags": ["one-pot", "quick", "budget", "high-protein"],
        "instructions": "1. Slice chicken thighs into bite-sized pieces and thinly slice the onion.\n2. Combine dashi stock and soy sauce in a small pan and bring to a simmer.\n3. Add onion slices and cook for 3 minutes until softened.\n4. Add chicken pieces and simmer for 5-6 minutes until cooked through.\n5. Beat eggs gently (do not overmix) and pour over the chicken and onion.\n6. Cover and cook for 1-2 minutes until eggs are just barely set.\n7. Slide the mixture over a bowl of hot steamed rice and serve.",
        "ingredients": [
            ("Chicken thighs", 250.0, "g"),
            ("Eggs", 3.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Dashi stock", 150.0, "ml"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Steamed rice", 2.0, "cups"),
        ],
    },
    {
        "title": "Japanese Curry Rice",
        "description": "Thick, hearty Japanese-style curry with potatoes, carrots, and chicken served over rice. Comfort food at its best.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["one-pot", "budget", "high-protein"],
        "instructions": "1. Cut chicken thighs, potatoes, carrots, and onion into bite-sized chunks.\n2. Heat oil in a large pot and brown chicken pieces on all sides.\n3. Add onion and cook until translucent, about 5 minutes.\n4. Add potatoes and carrots, stir for 2 minutes.\n5. Pour in water, bring to a boil, then reduce to a simmer for 20 minutes until vegetables are tender.\n6. Break curry roux blocks into the pot and stir until completely dissolved and sauce thickens.\n7. Simmer for an additional 5 minutes.\n8. Serve over steamed rice.",
        "ingredients": [
            ("Chicken thighs", 400.0, "g"),
            ("Potatoes", 2.0, "pieces"),
            ("Carrots", 2.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Japanese curry roux", 100.0, "g"),
            ("Water", 700.0, "ml"),
            ("Vegetable oil", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Yakisoba",
        "description": "Japanese stir-fried noodles with cabbage, carrots, and pork in a tangy Worcestershire-based sauce.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 2,
        "tags": ["stir-fry", "quick", "budget"],
        "instructions": "1. Slice pork into thin strips and shred cabbage and carrots.\n2. Cook yakisoba noodles briefly according to package directions, then drain.\n3. Heat oil in a wok or large pan over high heat.\n4. Stir-fry pork for 2 minutes until browned.\n5. Add cabbage and carrots, stir-frying for 3 minutes until tender-crisp.\n6. Add noodles and Worcestershire sauce, tossing everything together for 2 minutes.\n7. Serve topped with pickled ginger and nori flakes.",
        "ingredients": [
            ("Yakisoba noodles", 300.0, "g"),
            ("Pork belly (sliced thin)", 150.0, "g"),
            ("Cabbage", 2.0, "cups"),
            ("Carrots", 1.0, "pieces"),
            ("Worcestershire sauce", 3.0, "tbsp"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Pickled ginger", 1.0, "tbsp"),
            ("Nori flakes", 1.0, "tsp"),
        ],
    },
    {
        "title": "Japanese Clear Soup (Sumashi Jiru)",
        "description": "A delicate clear dashi broth with tofu, mushrooms, and scallions. Light, elegant, and deeply umami.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 4,
        "tags": ["vegetarian", "soup", "quick", "budget", "gluten-free"],
        "instructions": "1. Bring dashi stock to a gentle simmer.\n2. Add soy sauce and salt to season the broth.\n3. Slice shiitake mushrooms and cut tofu into small cubes.\n4. Add mushrooms and simmer for 3 minutes.\n5. Add tofu and heat through for 2 minutes.\n6. Ladle into bowls and garnish with sliced scallions.",
        "ingredients": [
            ("Dashi stock", 800.0, "ml"),
            ("Silken tofu", 150.0, "g"),
            ("Shiitake mushrooms", 4.0, "pieces"),
            ("Soy sauce", 1.0, "tsp"),
            ("Scallions", 2.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Onigiri (Rice Balls)",
        "description": "Shaped Japanese rice balls with savory fillings, wrapped in nori. The ultimate portable Japanese meal.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 0,
        "servings": 4,
        "tags": ["budget", "gluten-free"],
        "instructions": "1. Cook short-grain sushi rice and let it cool until warm enough to handle.\n2. Mix salt into a small bowl of water and wet your hands.\n3. Take a generous handful of warm rice and flatten it in your palm.\n4. Place a small amount of canned tuna mixed with soy sauce in the center.\n5. Mold the rice around the filling, shaping into a triangle with firm but gentle pressure.\n6. Wrap the base of each onigiri with a strip of nori seaweed.\n7. Repeat to make 8 rice balls.",
        "ingredients": [
            ("Short-grain rice", 2.0, "cups"),
            ("Canned tuna", 100.0, "g"),
            ("Nori seaweed sheets", 4.0, "pieces"),
            ("Soy sauce", 1.0, "tsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Nikujaga (Japanese Meat and Potatoes)",
        "description": "Home-cooked Japanese comfort stew of thinly sliced beef simmered with potatoes, onions, and carrots in a soy-dashi broth.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "tags": ["one-pot", "budget", "high-protein"],
        "instructions": "1. Slice beef thinly, cut potatoes into chunks, slice onion into wedges, and cut carrots into rolling pieces.\n2. Heat oil in a pot and brown beef slices for 2 minutes.\n3. Add onion and cook for 3 minutes until softened.\n4. Add potatoes and carrots, stirring to coat.\n5. Pour in dashi stock and soy sauce, bring to a boil.\n6. Reduce heat, cover, and simmer for 20 minutes until potatoes are tender.\n7. Serve in bowls with the cooking broth.",
        "ingredients": [
            ("Thinly sliced beef", 250.0, "g"),
            ("Potatoes", 3.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Carrots", 1.0, "pieces"),
            ("Dashi stock", 300.0, "ml"),
            ("Soy sauce", 3.0, "tbsp"),
            ("Vegetable oil", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Tamago Kake Gohan (Egg on Rice)",
        "description": "The simplest Japanese comfort food: a raw egg beaten into hot steamed rice with soy sauce. Silky, umami-rich, and ready in seconds.",
        "difficulty": "easy",
        "prep_time": 2,
        "cook_time": 0,
        "servings": 1,
        "tags": ["vegetarian", "quick", "budget", "gluten-free"],
        "instructions": "1. Place freshly cooked hot steamed rice in a bowl.\n2. Crack a fresh egg directly onto the rice.\n3. Add soy sauce.\n4. Beat the egg vigorously into the rice with chopsticks until the rice is coated in a glossy, creamy layer.\n5. Sprinkle with nori flakes or sesame seeds if desired.\n6. Eat immediately while hot.",
        "ingredients": [
            ("Steamed short-grain rice", 1.5, "cups"),
            ("Fresh egg", 1.0, "pieces"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Nori flakes", 0.5, "tsp"),
            ("Sesame seeds", 0.5, "tsp"),
        ],
    },
    # =========================================================================
    # KOREAN (recipes 27-34)
    # =========================================================================
    {
        "title": "Kimchi Jjigae (Kimchi Stew)",
        "description": "Korea's favorite stew of fermented kimchi simmered with pork, tofu, and scallions. Tangy, spicy, and deeply comforting.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 3,
        "tags": ["spicy", "soup", "one-pot", "budget", "high-protein"],
        "instructions": "1. Slice pork belly into thin pieces and chop aged kimchi into large pieces.\n2. Heat oil in a pot and sauté pork until lightly browned.\n3. Add kimchi and its juice, stir-frying for 3 minutes.\n4. Pour in water and gochugaru, bring to a boil.\n5. Reduce heat and simmer for 15 minutes.\n6. Add cubed tofu and sliced scallions, simmer for another 5 minutes.\n7. Taste and add soy sauce or salt as needed.\n8. Serve bubbling hot with steamed rice.",
        "ingredients": [
            ("Aged kimchi", 2.0, "cups"),
            ("Pork belly", 200.0, "g"),
            ("Firm tofu", 200.0, "g"),
            ("Gochugaru (Korean chili flakes)", 1.0, "tbsp"),
            ("Water", 500.0, "ml"),
            ("Scallions", 2.0, "pieces"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Vegetable oil", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Bibimbap",
        "description": "Iconic Korean mixed rice bowl with assorted seasoned vegetables, a fried egg, and gochujang. Colorful and nutritious.",
        "difficulty": "medium",
        "prep_time": 25,
        "cook_time": 15,
        "servings": 2,
        "tags": ["vegetarian", "high-protein", "budget"],
        "instructions": "1. Prepare each vegetable separately: blanch spinach and season with sesame oil and salt; sauté julienned carrots; sauté sliced zucchini; season bean sprouts with garlic and sesame oil.\n2. Arrange steamed rice in bowls.\n3. Place each seasoned vegetable in a separate section on top of the rice.\n4. Fry eggs sunny-side up.\n5. Place a fried egg on top of each bowl.\n6. Add a generous dollop of gochujang in the center.\n7. Serve with sesame oil and sesame seeds on the side.\n8. Mix everything together before eating.",
        "ingredients": [
            ("Steamed rice", 2.0, "cups"),
            ("Spinach", 100.0, "g"),
            ("Carrots", 1.0, "pieces"),
            ("Zucchini", 1.0, "pieces"),
            ("Bean sprouts", 100.0, "g"),
            ("Eggs", 2.0, "pieces"),
            ("Gochujang (Korean chili paste)", 2.0, "tbsp"),
            ("Sesame oil", 2.0, "tbsp"),
            ("Garlic", 2.0, "pieces"),
            ("Sesame seeds", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Doenjang Jjigae (Soybean Paste Stew)",
        "description": "Robust Korean stew made with fermented soybean paste, tofu, and vegetables. Earthy, savory, and deeply satisfying.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 3,
        "tags": ["vegetarian", "soup", "one-pot", "budget"],
        "instructions": "1. Dice zucchini, potatoes, onion, and tofu into cubes.\n2. Dissolve doenjang paste in anchovy or vegetable stock.\n3. Add potatoes and onion to the pot and bring to a boil.\n4. Reduce heat and simmer for 10 minutes until potatoes soften.\n5. Add zucchini, tofu, and minced garlic.\n6. Simmer for another 7-8 minutes.\n7. Add sliced scallions and Korean chili flakes, cook 1 minute more.\n8. Serve bubbling hot with rice.",
        "ingredients": [
            ("Doenjang (fermented soybean paste)", 2.0, "tbsp"),
            ("Firm tofu", 200.0, "g"),
            ("Zucchini", 1.0, "pieces"),
            ("Potato", 1.0, "pieces"),
            ("Onion", 0.5, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Scallions", 2.0, "pieces"),
            ("Vegetable stock", 500.0, "ml"),
            ("Gochugaru (Korean chili flakes)", 0.5, "tsp"),
        ],
    },
    {
        "title": "Korean Egg Roll (Gyeran Mari)",
        "description": "Rolled Korean omelette with vegetables baked right in. A lunchbox classic that is savory, colorful, and protein-packed.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "quick", "budget", "high-protein"],
        "instructions": "1. Finely dice carrots, scallions, and onion.\n2. Beat eggs and mix in the diced vegetables, salt, and a splash of water.\n3. Heat a rectangular or round pan over medium-low heat and lightly oil it.\n4. Pour a thin layer of the egg mixture into the pan.\n5. When the bottom sets but the top is still slightly wet, roll the egg toward one end of the pan.\n6. Push the roll back, add more egg mixture, and repeat the rolling process 3-4 times.\n7. Remove from pan, let rest 2 minutes, then slice into rounds.\n8. Serve as a side dish or in a packed lunch.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Carrots", 0.5, "pieces"),
            ("Scallions", 2.0, "pieces"),
            ("Onion", 0.25, "pieces"),
            ("Salt", 0.25, "tsp"),
            ("Water", 1.0, "tbsp"),
            ("Vegetable oil", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Kongnamul Guk (Soybean Sprout Soup)",
        "description": "A light, clean Korean soup made with soybean sprouts. Known as a traditional hangover cure and everyday comfort food.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 3,
        "tags": ["vegetarian", "vegan", "soup", "quick", "budget", "gluten-free"],
        "instructions": "1. Wash soybean sprouts thoroughly and remove any brown tails.\n2. Place sprouts in a pot with water and bring to a boil with the lid on.\n3. Do not open the lid for the first 8 minutes to prevent a raw bean smell.\n4. Add minced garlic and soy sauce.\n5. Simmer for another 5 minutes.\n6. Season with salt and white pepper to taste.\n7. Serve in bowls topped with sliced scallions and a drizzle of sesame oil.",
        "ingredients": [
            ("Soybean sprouts", 300.0, "g"),
            ("Water", 700.0, "ml"),
            ("Garlic", 3.0, "pieces"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Scallions", 2.0, "pieces"),
            ("Sesame oil", 1.0, "tsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Japchae (Korean Glass Noodles)",
        "description": "Sweet potato starch noodles stir-fried with colorful vegetables, mushrooms, and sesame oil. A festive Korean side dish.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "stir-fry", "budget"],
        "instructions": "1. Soak sweet potato noodles in hot water for 10 minutes, then drain.\n2. Blanch spinach briefly, squeeze dry, and season with sesame oil and salt.\n3. Julienne carrots, slice onion, and slice mushrooms.\n4. Stir-fry each vegetable separately in a hot pan with a little oil, seasoning each with salt.\n5. Boil the soaked noodles for 5 minutes, drain, and toss with soy sauce and sesame oil.\n6. Combine all vegetables and noodles in a large bowl.\n7. Toss everything together with sesame seeds.\n8. Serve warm or at room temperature.",
        "ingredients": [
            ("Sweet potato glass noodles", 200.0, "g"),
            ("Spinach", 100.0, "g"),
            ("Carrots", 1.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Shiitake mushrooms", 4.0, "pieces"),
            ("Soy sauce", 3.0, "tbsp"),
            ("Sesame oil", 2.0, "tbsp"),
            ("Sesame seeds", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Dubu Jorim (Braised Tofu)",
        "description": "Pan-fried tofu slices braised in a spicy gochugaru soy sauce. A beloved Korean banchan packed with flavor.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 3,
        "tags": ["vegetarian", "vegan", "spicy", "budget", "high-protein"],
        "instructions": "1. Slice firm tofu into half-inch thick rectangular pieces and pat dry.\n2. Pan-fry tofu in oil until golden on both sides, about 3 minutes per side.\n3. Mix together soy sauce, gochugaru, minced garlic, sesame oil, and water to make the braising sauce.\n4. Pour the sauce over the tofu in the pan.\n5. Simmer on medium-low for 5 minutes, spooning sauce over the tofu.\n6. Garnish with sliced scallions and sesame seeds.\n7. Serve as a side dish with rice.",
        "ingredients": [
            ("Firm tofu", 400.0, "g"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Gochugaru (Korean chili flakes)", 1.0, "tbsp"),
            ("Garlic", 3.0, "pieces"),
            ("Sesame oil", 1.0, "tsp"),
            ("Scallions", 2.0, "pieces"),
            ("Sesame seeds", 1.0, "tsp"),
            ("Water", 60.0, "ml"),
            ("Vegetable oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Kimchi Fried Rice",
        "description": "Quick Korean fried rice made with aged kimchi, sesame oil, and topped with a fried egg. The best way to use leftover rice and kimchi.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["spicy", "quick", "stir-fry", "budget"],
        "instructions": "1. Chop aged kimchi into small pieces, reserving the juice.\n2. Heat sesame oil in a pan over medium-high heat.\n3. Add chopped kimchi and stir-fry for 2 minutes until slightly caramelized.\n4. Add cold leftover rice and kimchi juice, stir-frying and breaking up clumps for 3-4 minutes.\n5. Add soy sauce and toss to combine.\n6. Fry eggs separately, keeping the yolks runny.\n7. Serve rice in bowls topped with fried eggs and a sprinkle of sesame seeds.",
        "ingredients": [
            ("Cooked rice", 3.0, "cups"),
            ("Aged kimchi", 1.0, "cups"),
            ("Sesame oil", 1.0, "tbsp"),
            ("Soy sauce", 1.0, "tbsp"),
            ("Eggs", 2.0, "pieces"),
            ("Sesame seeds", 1.0, "tsp"),
            ("Vegetable oil", 1.0, "tbsp"),
        ],
    },
    # =========================================================================
    # VIETNAMESE (recipes 35-42)
    # =========================================================================
    {
        "title": "Pho Bo (Vietnamese Beef Noodle Soup)",
        "description": "Vietnam's iconic noodle soup with a deeply aromatic beef broth, rice noodles, and fresh herbs. A bowl of pure comfort.",
        "difficulty": "hard",
        "prep_time": 20,
        "cook_time": 120,
        "servings": 4,
        "tags": ["soup", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Char onion and ginger over an open flame or under a broiler until blackened.\n2. Toast star anise, cinnamon stick, cloves, and coriander seeds in a dry pan until fragrant.\n3. Place beef bones in a large pot, cover with water, bring to a boil, and skim all scum.\n4. Add charred onion, ginger, toasted spices, and fish sauce.\n5. Simmer for 2 hours on low heat, skimming occasionally.\n6. Cook rice noodles according to package directions and divide among bowls.\n7. Strain the broth and ladle over the noodles, adding thinly sliced raw beef which cooks in the hot broth.\n8. Serve with bean sprouts, Thai basil, lime wedges, and sliced chilies.",
        "ingredients": [
            ("Beef bones", 500.0, "g"),
            ("Beef sirloin (thinly sliced)", 200.0, "g"),
            ("Rice noodles", 300.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Ginger", 50.0, "g"),
            ("Star anise", 3.0, "pieces"),
            ("Cinnamon stick", 1.0, "pieces"),
            ("Fish sauce", 3.0, "tbsp"),
            ("Bean sprouts", 1.0, "cups"),
            ("Thai basil", 0.5, "cups"),
        ],
    },
    {
        "title": "Bun Cha (Vietnamese Grilled Pork with Noodles)",
        "description": "Hanoi's beloved dish of grilled seasoned pork patties served with rice vermicelli, fresh herbs, and a tangy dipping broth.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "tags": ["high-protein", "budget", "gluten-free"],
        "instructions": "1. Mix ground pork with minced garlic, fish sauce, and black pepper. Form into small flat patties.\n2. Grill or pan-fry patties over medium-high heat for 3-4 minutes per side until charred and cooked.\n3. Prepare dipping broth by combining warm water, fish sauce, lime juice, and sliced garlic.\n4. Add sliced chilies and shredded carrots to the broth.\n5. Cook rice vermicelli according to package directions, drain, and rinse in cold water.\n6. Serve noodles on a plate with a platter of lettuce, mint, and cilantro.\n7. Place grilled patties into the dipping broth bowl.\n8. Diners dip noodles and herbs into the broth.",
        "ingredients": [
            ("Ground pork", 400.0, "g"),
            ("Rice vermicelli", 200.0, "g"),
            ("Fish sauce", 4.0, "tbsp"),
            ("Lime juice", 3.0, "tbsp"),
            ("Garlic", 4.0, "pieces"),
            ("Carrots", 1.0, "pieces"),
            ("Lettuce", 4.0, "pieces"),
            ("Mint", 0.5, "cups"),
            ("Cilantro", 0.25, "cups"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Vietnamese Egg Drop Soup (Canh Trung)",
        "description": "A light, nourishing Vietnamese soup of tomatoes, egg ribbons, and scallions. Simple enough for any weeknight.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 3,
        "tags": ["soup", "quick", "budget", "gluten-free"],
        "instructions": "1. Cut tomatoes into thin wedges.\n2. Bring water or chicken stock to a boil in a pot.\n3. Add tomatoes and cook for 3 minutes until softened.\n4. Season with fish sauce and salt.\n5. Beat eggs lightly and slowly drizzle into the simmering soup while stirring gently.\n6. Cook for 1 more minute until egg ribbons are set.\n7. Garnish with chopped scallions and serve immediately.",
        "ingredients": [
            ("Tomatoes", 3.0, "pieces"),
            ("Eggs", 2.0, "pieces"),
            ("Water", 700.0, "ml"),
            ("Fish sauce", 1.5, "tbsp"),
            ("Scallions", 2.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Vietnamese Lemongrass Chicken",
        "description": "Chicken thighs braised with lemongrass, garlic, and fish sauce. Fragrant and caramelized, perfect over steamed rice.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["gluten-free", "budget", "high-protein"],
        "instructions": "1. Cut chicken thighs into bite-sized pieces.\n2. Finely mince lemongrass, garlic, and shallots.\n3. Heat oil in a pan and sauté shallots and garlic until fragrant.\n4. Add lemongrass and stir for 1 minute.\n5. Add chicken pieces and sear on all sides for 5 minutes.\n6. Add fish sauce and black pepper, stir to coat.\n7. Add a splash of water, cover, and braise for 15 minutes until chicken is tender and sauce is reduced.\n8. Serve over steamed rice with fresh herbs.",
        "ingredients": [
            ("Chicken thighs", 500.0, "g"),
            ("Lemongrass stalks", 3.0, "pieces"),
            ("Garlic", 5.0, "pieces"),
            ("Shallots", 2.0, "pieces"),
            ("Fish sauce", 2.0, "tbsp"),
            ("Black pepper", 0.5, "tsp"),
            ("Vegetable oil", 1.0, "tbsp"),
            ("Water", 60.0, "ml"),
        ],
    },
    {
        "title": "Canh Chua (Vietnamese Sour Soup)",
        "description": "A light and tangy Vietnamese soup with tomatoes, pineapple, tamarind, and fish. Refreshing and brimming with fresh herbs.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "tags": ["soup", "gluten-free", "budget"],
        "instructions": "1. Cut fish fillets into pieces and slice tomatoes, pineapple, and okra.\n2. Dissolve tamarind paste in warm water and strain to make tamarind liquid.\n3. Bring water to a boil, add tamarind liquid and tomatoes.\n4. Simmer for 5 minutes, then add pineapple and okra.\n5. Add fish pieces and cook gently for 5-7 minutes until fish is flaky.\n6. Season with fish sauce and salt.\n7. Stir in bean sprouts at the last moment.\n8. Serve garnished with fresh herbs including rice paddy herb and cilantro.",
        "ingredients": [
            ("White fish fillets", 300.0, "g"),
            ("Tomatoes", 2.0, "pieces"),
            ("Pineapple", 150.0, "g"),
            ("Tamarind paste", 2.0, "tbsp"),
            ("Okra", 6.0, "pieces"),
            ("Bean sprouts", 1.0, "cups"),
            ("Fish sauce", 2.0, "tbsp"),
            ("Water", 1.0, "l"),
            ("Cilantro", 0.25, "cups"),
        ],
    },
    {
        "title": "Vietnamese Stir-Fried Water Spinach (Rau Muong Xao Toi)",
        "description": "Crisp water spinach wok-fried with heaps of garlic and a splash of fish sauce. A classic Vietnamese home-cooked side.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 5,
        "servings": 2,
        "tags": ["quick", "stir-fry", "budget", "gluten-free"],
        "instructions": "1. Wash water spinach and cut into 3-inch segments, separating thick stems from leaves.\n2. Mince garlic cloves.\n3. Heat oil in a wok over the highest heat.\n4. Add garlic and stir-fry for 5 seconds.\n5. Add water spinach stems first, tossing for 30 seconds.\n6. Add leaves and fish sauce, stir-frying for another 30-60 seconds until just wilted.\n7. Serve immediately.",
        "ingredients": [
            ("Water spinach", 300.0, "g"),
            ("Garlic", 5.0, "pieces"),
            ("Fish sauce", 1.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
        ],
    },
    {
        "title": "Com Tam (Vietnamese Broken Rice with Pork Chop)",
        "description": "Saigon's signature dish of grilled lemongrass pork chops served over broken rice with a side of fish sauce dressing.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 2,
        "tags": ["high-protein", "budget", "gluten-free"],
        "instructions": "1. Butterfly pork chops to an even thickness.\n2. Mince lemongrass, garlic, and shallots, then combine with fish sauce and black pepper.\n3. Marinate pork chops in the mixture for at least 10 minutes.\n4. Cook broken rice according to package directions.\n5. Grill or pan-fry pork chops over high heat for 4-5 minutes per side until charred and cooked.\n6. Mix fish sauce dressing: fish sauce, lime juice, garlic, and water.\n7. Serve pork chop over broken rice with sliced cucumber, tomato, and fish sauce dressing on the side.",
        "ingredients": [
            ("Pork chops", 2.0, "pieces"),
            ("Broken rice", 1.5, "cups"),
            ("Lemongrass stalks", 2.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Shallots", 2.0, "pieces"),
            ("Fish sauce", 3.0, "tbsp"),
            ("Lime juice", 2.0, "tbsp"),
            ("Cucumber", 1.0, "pieces"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Vietnamese Steamed Egg with Scallions",
        "description": "A delicate Vietnamese steamed egg dish, silky and smooth with scallions and fish sauce.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 2,
        "tags": ["vegetarian", "quick", "budget", "gluten-free"],
        "instructions": "1. Beat eggs gently and combine with warm water in a 1:1.5 ratio.\n2. Add fish sauce and a pinch of salt.\n3. Strain through a fine sieve into a heatproof bowl.\n4. Scatter thinly sliced scallions on top.\n5. Cover with a plate or foil and steam over simmering water for 12-15 minutes.\n6. Drizzle with a splash of fish sauce and fried shallots before serving.",
        "ingredients": [
            ("Eggs", 3.0, "pieces"),
            ("Warm water", 270.0, "ml"),
            ("Fish sauce", 1.0, "tbsp"),
            ("Scallions", 2.0, "pieces"),
            ("Fried shallots", 1.0, "tbsp"),
            ("Salt", 1.0, "pinch"),
        ],
    },
    # =========================================================================
    # INDONESIAN (recipes 43-50)
    # =========================================================================
    {
        "title": "Nasi Goreng (Indonesian Fried Rice)",
        "description": "Indonesia's national dish of wok-fried rice with kecap manis-free savory seasoning, shrimp paste, and a fried egg on top.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 2,
        "tags": ["quick", "stir-fry", "budget", "high-protein"],
        "instructions": "1. Mince garlic, shallots, and chilies into a paste.\n2. Heat oil in a wok over high heat and fry the paste for 30 seconds.\n3. Add shrimp paste and stir for 15 seconds.\n4. Add cold leftover rice and stir-fry for 3-4 minutes, breaking up clumps.\n5. Add soy sauce and toss until evenly colored.\n6. Fry eggs separately and place on top of each serving.\n7. Garnish with sliced cucumber and fried shallots.",
        "ingredients": [
            ("Cooked rice", 3.0, "cups"),
            ("Garlic", 3.0, "pieces"),
            ("Shallots", 3.0, "pieces"),
            ("Red chilies", 2.0, "pieces"),
            ("Shrimp paste (terasi)", 1.0, "tsp"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Eggs", 2.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Cucumber", 0.5, "pieces"),
        ],
    },
    {
        "title": "Soto Ayam (Indonesian Chicken Soup)",
        "description": "Aromatic yellow chicken soup with turmeric, lemongrass, and glass noodles. Indonesia's beloved comfort soup.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 4,
        "tags": ["soup", "gluten-free", "budget", "high-protein"],
        "instructions": "1. Blend shallots, garlic, turmeric, ginger, and candlenuts into a paste.\n2. Heat oil in a large pot and fry the paste for 3 minutes until fragrant.\n3. Add chicken thighs, lemongrass, and kaffir lime leaves.\n4. Pour in water, bring to a boil, then simmer for 30 minutes.\n5. Remove chicken, shred the meat, and return it to the broth.\n6. Soak glass noodles in hot water for 5 minutes, then drain.\n7. Season broth with salt to taste.\n8. Serve broth over glass noodles, topped with shredded chicken, bean sprouts, fried shallots, and lime wedges.",
        "ingredients": [
            ("Chicken thighs", 400.0, "g"),
            ("Shallots", 4.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Fresh turmeric", 15.0, "g"),
            ("Ginger", 15.0, "g"),
            ("Lemongrass stalks", 2.0, "pieces"),
            ("Glass noodles", 100.0, "g"),
            ("Water", 1.0, "l"),
            ("Bean sprouts", 1.0, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Gado Gado (Indonesian Vegetable Salad with Peanut Sauce)",
        "description": "Blanched vegetables, tofu, and boiled eggs drenched in a rich, savory peanut sauce. A hearty Indonesian classic.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "high-protein"],
        "instructions": "1. Blanch cabbage, green beans, and bean sprouts separately until tender-crisp, then drain.\n2. Boil eggs for 7 minutes, cool, and halve.\n3. Pan-fry tofu until golden on both sides and cut into cubes.\n4. Make peanut sauce: blend roasted peanuts, garlic, chili, tamarind paste, salt, and water until smooth.\n5. Arrange blanched vegetables, tofu, and eggs on a platter.\n6. Pour peanut sauce generously over everything.\n7. Garnish with fried shallots and serve.",
        "ingredients": [
            ("Cabbage", 2.0, "cups"),
            ("Green beans", 150.0, "g"),
            ("Bean sprouts", 1.0, "cups"),
            ("Firm tofu", 200.0, "g"),
            ("Eggs", 4.0, "pieces"),
            ("Roasted peanuts", 100.0, "g"),
            ("Garlic", 2.0, "pieces"),
            ("Tamarind paste", 1.0, "tbsp"),
            ("Red chili", 1.0, "pieces"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Sayur Asem (Indonesian Tamarind Vegetable Soup)",
        "description": "A sour and savory Indonesian vegetable soup with tamarind broth, corn, green beans, and chayote. Refreshing and nourishing.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "soup", "budget", "gluten-free"],
        "instructions": "1. Peel and dice chayote, cut corn into rounds, and trim green beans.\n2. Blend shallots, garlic, and galangal into a rough paste.\n3. Bring water to a boil and add the spice paste.\n4. Add corn and chayote, simmer for 10 minutes.\n5. Add green beans and peanuts, cook another 8 minutes.\n6. Dissolve tamarind paste in a little water and strain into the soup.\n7. Season with salt and serve hot.",
        "ingredients": [
            ("Chayote squash", 1.0, "pieces"),
            ("Corn on the cob", 2.0, "pieces"),
            ("Green beans", 100.0, "g"),
            ("Peanuts", 50.0, "g"),
            ("Tamarind paste", 2.0, "tbsp"),
            ("Shallots", 3.0, "pieces"),
            ("Garlic", 2.0, "pieces"),
            ("Galangal", 15.0, "g"),
            ("Water", 1.0, "l"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Tempe Goreng (Fried Tempeh)",
        "description": "Sliced tempeh marinated in garlic and coriander, then shallow-fried until golden and crispy. A cheap, protein-rich Indonesian staple.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 3,
        "tags": ["vegetarian", "vegan", "quick", "budget", "high-protein", "gluten-free"],
        "instructions": "1. Slice tempeh into thin rectangular pieces.\n2. Crush garlic and mix with ground coriander, salt, and water to make a thin marinade.\n3. Dip tempeh slices in the marinade and let sit for 5 minutes.\n4. Heat oil in a pan over medium heat.\n5. Fry tempeh slices in batches until golden and crispy on both sides, about 3 minutes per side.\n6. Drain on paper towels and serve hot with sambal or steamed rice.",
        "ingredients": [
            ("Tempeh", 300.0, "g"),
            ("Garlic", 4.0, "pieces"),
            ("Ground coriander", 1.0, "tsp"),
            ("Salt", 0.5, "tsp"),
            ("Water", 3.0, "tbsp"),
            ("Vegetable oil", 60.0, "ml"),
        ],
    },
    {
        "title": "Mie Goreng (Indonesian Stir-Fried Noodles)",
        "description": "Savory Indonesian stir-fried egg noodles with cabbage, garlic, and soy sauce. Quick, cheap, and endlessly satisfying.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 2,
        "tags": ["stir-fry", "quick", "budget"],
        "instructions": "1. Cook egg noodles according to package directions, drain and set aside.\n2. Mince garlic and shallots, shred cabbage.\n3. Heat oil in a wok over high heat.\n4. Add garlic and shallots, stir-fry for 30 seconds.\n5. Add cabbage and stir-fry for 2 minutes.\n6. Add noodles, soy sauce, and chili sauce, tossing vigorously for 2-3 minutes.\n7. Crack an egg into the wok and stir through.\n8. Serve topped with fried shallots and sliced scallions.",
        "ingredients": [
            ("Egg noodles", 200.0, "g"),
            ("Cabbage", 1.5, "cups"),
            ("Garlic", 3.0, "pieces"),
            ("Shallots", 2.0, "pieces"),
            ("Soy sauce", 2.0, "tbsp"),
            ("Chili sauce", 1.0, "tbsp"),
            ("Egg", 1.0, "pieces"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Scallions", 2.0, "pieces"),
        ],
    },
    {
        "title": "Sambal Telur (Eggs in Chili Sauce)",
        "description": "Hard-boiled eggs fried until blistered then smothered in a fiery sambal sauce. A beloved Indonesian home-cooked dish.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 3,
        "tags": ["spicy", "budget", "high-protein", "gluten-free"],
        "instructions": "1. Hard-boil eggs for 10 minutes, peel, and pat dry.\n2. Deep-fry or pan-fry whole eggs in oil until the surface is blistered and golden.\n3. Blend shallots, garlic, and red chilies into a rough paste.\n4. Fry the paste in oil for 3 minutes until darkened and fragrant.\n5. Add tomato, salt, and a splash of water, simmering for 3 minutes.\n6. Add fried eggs and coat them in the sambal sauce.\n7. Serve with steamed rice.",
        "ingredients": [
            ("Eggs", 6.0, "pieces"),
            ("Red chilies", 5.0, "pieces"),
            ("Shallots", 4.0, "pieces"),
            ("Garlic", 2.0, "pieces"),
            ("Tomato", 1.0, "pieces"),
            ("Salt", 0.5, "tsp"),
            ("Vegetable oil", 60.0, "ml"),
        ],
    },
    {
        "title": "Sop Buntut (Indonesian Oxtail Soup)",
        "description": "A rich, clear Indonesian soup of slow-simmered oxtail with potatoes, carrots, and warming spices. Hearty and deeply savory.",
        "difficulty": "hard",
        "prep_time": 15,
        "cook_time": 150,
        "servings": 6,
        "tags": ["soup", "one-pot", "budget", "high-protein", "gluten-free"],
        "instructions": "1. Blanch oxtail pieces in boiling water for 5 minutes, drain, and rinse.\n2. Place oxtail in a large pot with fresh water and bring to a boil, skimming scum.\n3. Add sliced shallots, garlic, whole cloves, nutmeg, and black peppercorns.\n4. Simmer on low heat for 2 hours until meat is falling off the bone.\n5. Add diced potatoes and carrots, cook another 20 minutes until vegetables are tender.\n6. Season with salt to taste.\n7. Serve in bowls with the broth, topped with fried shallots and chopped celery leaves.\n8. Accompany with steamed rice and sambal on the side.",
        "ingredients": [
            ("Oxtail", 800.0, "g"),
            ("Potatoes", 2.0, "pieces"),
            ("Carrots", 2.0, "pieces"),
            ("Shallots", 4.0, "pieces"),
            ("Garlic", 3.0, "pieces"),
            ("Whole cloves", 3.0, "pieces"),
            ("Nutmeg", 0.25, "tsp"),
            ("Black peppercorns", 1.0, "tsp"),
            ("Water", 2.0, "l"),
            ("Salt", 1.5, "tsp"),
        ],
    },
]
