MIDDLE_EASTERN_RECIPES = [
    {
        "title": "Classic Hummus",
        "description": "Creamy chickpea dip blended with tahini, lemon, and garlic. A staple across the entire Middle East.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 0,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "gluten-free", "quick", "budget", "high-protein"],
        "instructions": "1. Drain and rinse the chickpeas.\n2. Add chickpeas, tahini, lemon juice, garlic, and cumin to a food processor.\n3. Blend until smooth, adding cold water a tablespoon at a time for desired consistency.\n4. Season with salt to taste.\n5. Transfer to a serving plate, drizzle with olive oil, and sprinkle with paprika.",
        "ingredients": [
            ("Chickpeas (canned)", 2.0, "cups"),
            ("Tahini", 3.0, "tbsp"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Cumin", 0.5, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
            ("Cold water", 3.0, "tbsp"),
            ("Paprika", 0.5, "tsp"),
        ],
    },
    {
        "title": "Falafel",
        "description": "Crispy fried chickpea patties seasoned with fresh herbs and spices. Originally from Egypt, beloved everywhere.",
        "difficulty": "medium",
        "prep_time": 30,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "high-protein", "budget"],
        "instructions": "1. Soak dried chickpeas overnight, then drain thoroughly.\n2. Add chickpeas, onion, garlic, parsley, cilantro, cumin, and coriander to a food processor.\n3. Pulse until a coarse paste forms; do not over-blend.\n4. Season with salt and pepper, then refrigerate the mixture for 1 hour.\n5. Shape into small patties or balls.\n6. Heat vegetable oil in a deep pan to 180C.\n7. Fry falafel in batches for 3-4 minutes until deep golden brown.\n8. Drain on paper towels and serve with tahini sauce.",
        "ingredients": [
            ("Dried chickpeas", 2.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Fresh parsley", 0.5, "cups"),
            ("Fresh cilantro", 0.5, "cups"),
            ("Ground cumin", 1.0, "tsp"),
            ("Ground coriander", 1.0, "tsp"),
            ("Salt", 1.0, "tsp"),
            ("Vegetable oil", 2.0, "cups"),
        ],
    },
    {
        "title": "Mujaddara",
        "description": "Hearty Lebanese lentil and rice dish topped with crispy caramelized onions. The ultimate budget comfort food.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 40,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget", "one-pot", "high-protein"],
        "instructions": "1. Rinse lentils and cook in salted water for 15 minutes until just tender.\n2. Slice onions thinly and fry in olive oil over medium-low heat for 20-25 minutes until deeply caramelized.\n3. Add rice to the lentils along with cumin and salt.\n4. Cook for another 15-18 minutes until rice is tender and water is absorbed.\n5. Fluff with a fork and top generously with the caramelized onions.\n6. Serve with plain yogurt on the side.",
        "ingredients": [
            ("Green or brown lentils", 1.0, "cups"),
            ("Long-grain rice", 0.75, "cups"),
            ("Onions", 3.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Ground cumin", 1.0, "tsp"),
            ("Salt", 1.0, "tsp"),
            ("Water", 3.0, "cups"),
        ],
    },
    {
        "title": "Shakshuka",
        "description": "Eggs poached in a spiced tomato and pepper sauce. A North African and Levantine breakfast classic.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "quick", "one-pot", "budget"],
        "instructions": "1. Heat olive oil in a large skillet over medium heat.\n2. Saute diced onion and bell pepper until softened, about 5 minutes.\n3. Add garlic, cumin, and paprika, and cook for 1 minute.\n4. Pour in crushed tomatoes and simmer for 10 minutes until thickened.\n5. Make small wells in the sauce and crack an egg into each well.\n6. Cover and cook for 6-8 minutes until egg whites are set but yolks are still runny.\n7. Garnish with fresh parsley and serve with crusty bread.",
        "ingredients": [
            ("Eggs", 6.0, "pieces"),
            ("Crushed tomatoes", 2.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Bell pepper", 1.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Ground cumin", 1.0, "tsp"),
            ("Paprika", 1.0, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Fresh parsley", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Fattoush",
        "description": "Crunchy Lebanese bread salad with toasted pita, fresh vegetables, and tangy sumac dressing.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 5,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "quick", "budget"],
        "instructions": "1. Tear pita bread into bite-sized pieces and toast in the oven or fry until crisp.\n2. Chop tomatoes, cucumber, radishes, and lettuce into bite-sized pieces.\n3. Thinly slice the green onions.\n4. Whisk together olive oil, lemon juice, sumac, and salt for the dressing.\n5. Toss all vegetables in a large bowl with the dressing.\n6. Add the crispy pita just before serving and toss gently.",
        "ingredients": [
            ("Pita bread", 2.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("Cucumber", 1.0, "pieces"),
            ("Radishes", 4.0, "pieces"),
            ("Romaine lettuce", 2.0, "cups"),
            ("Green onions", 3.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Sumac", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Tabbouleh",
        "description": "Vibrant Lebanese parsley salad with bulgur wheat, tomatoes, and a bright lemon dressing.",
        "difficulty": "easy",
        "prep_time": 20,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "quick", "budget"],
        "instructions": "1. Soak bulgur in hot water for 15 minutes, then drain and squeeze out excess water.\n2. Finely chop the parsley, mint, tomatoes, and green onions.\n3. Combine bulgur with the chopped herbs and vegetables in a large bowl.\n4. Dress with olive oil and lemon juice.\n5. Season with salt and pepper to taste.\n6. Chill for at least 15 minutes before serving to let flavors meld.",
        "ingredients": [
            ("Fine bulgur wheat", 0.5, "cups"),
            ("Fresh parsley", 3.0, "cups"),
            ("Fresh mint", 0.5, "cups"),
            ("Tomatoes", 2.0, "pieces"),
            ("Green onions", 4.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Lemon juice", 3.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Baba Ghanoush",
        "description": "Smoky roasted eggplant dip blended with tahini and lemon. A Levantine classic served as a meze.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Prick eggplants all over with a fork.\n2. Roast directly over a gas flame or under a broiler, turning often, until skin is charred and flesh is soft.\n3. Let cool, then peel off the charred skin and drain the flesh in a colander.\n4. Mash the eggplant flesh with a fork.\n5. Mix in tahini, lemon juice, garlic, and salt.\n6. Transfer to a plate, drizzle with olive oil, and serve with flatbread.",
        "ingredients": [
            ("Large eggplants", 2.0, "pieces"),
            ("Tahini", 2.0, "tbsp"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Ful Medames",
        "description": "Egyptian stewed fava beans mashed with garlic, lemon, and olive oil. The national breakfast dish of Egypt.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-protein", "budget"],
        "instructions": "1. Drain and rinse the fava beans.\n2. Heat beans in a saucepan with a splash of water over medium heat.\n3. Mash some of the beans with the back of a spoon, leaving some whole.\n4. Stir in minced garlic, cumin, and lemon juice.\n5. Season with salt and pepper.\n6. Serve in bowls drizzled with olive oil, topped with chopped parsley and a sprinkle of chili flakes.",
        "ingredients": [
            ("Fava beans (canned)", 2.0, "cups"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Ground cumin", 1.0, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Fresh parsley", 2.0, "tbsp"),
            ("Chili flakes", 0.25, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Koshari",
        "description": "Egyptian street food combining rice, lentils, and pasta topped with spiced tomato sauce and crispy onions.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 45,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "budget", "high-protein"],
        "instructions": "1. Cook lentils in water until tender, about 20 minutes, then drain.\n2. Cook rice separately until fluffy.\n3. Cook small pasta (macaroni or ditalini) until al dente and drain.\n4. Slice onions thinly and fry in oil until deeply crispy and golden brown.\n5. Make the sauce: saute garlic in olive oil, add tomato passata, vinegar, cumin, and chili flakes; simmer 10 minutes.\n6. Layer rice, lentils, and pasta in a serving bowl.\n7. Spoon the spiced tomato sauce over the top.\n8. Garnish generously with the crispy fried onions.",
        "ingredients": [
            ("Brown lentils", 1.0, "cups"),
            ("Long-grain rice", 1.0, "cups"),
            ("Small pasta", 1.0, "cups"),
            ("Onions", 3.0, "pieces"),
            ("Tomato passata", 1.5, "cups"),
            ("Garlic cloves", 3.0, "pieces"),
            ("White vinegar", 1.0, "tbsp"),
            ("Ground cumin", 1.0, "tsp"),
            ("Chili flakes", 0.5, "tsp"),
            ("Vegetable oil", 0.5, "cups"),
        ],
    },
    {
        "title": "Kibbeh",
        "description": "Lebanese bulgur and ground lamb croquettes stuffed with spiced meat, pine nuts, and onions.",
        "difficulty": "hard",
        "prep_time": 45,
        "cook_time": 20,
        "servings": 6,
        "tags": ["high-protein", "budget"],
        "instructions": "1. Soak fine bulgur in water for 30 minutes, then drain and squeeze dry.\n2. Combine bulgur with half the ground lamb, grated onion, allspice, cumin, and salt in a food processor and blend to a smooth paste.\n3. For the filling, saute diced onion in oil until soft, add remaining lamb, pine nuts, allspice, and cinnamon; cook until browned.\n4. Take a small ball of the outer shell mixture, form an oval, and make a hollow in the center.\n5. Fill with a spoonful of the cooked filling and seal shut into a torpedo shape.\n6. Deep fry in hot oil for 4-5 minutes until golden brown and crispy.\n7. Drain on paper towels and serve with yogurt.",
        "ingredients": [
            ("Fine bulgur wheat", 1.5, "cups"),
            ("Ground lamb", 400.0, "g"),
            ("Onions", 2.0, "pieces"),
            ("Pine nuts", 2.0, "tbsp"),
            ("Ground allspice", 1.0, "tsp"),
            ("Ground cumin", 0.5, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Vegetable oil", 2.0, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Labneh",
        "description": "Thick strained yogurt dip drizzled with olive oil and za'atar. A Levantine breakfast and meze essential.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "quick", "budget"],
        "instructions": "1. Line a fine-mesh strainer with cheesecloth and set it over a bowl.\n2. Stir salt into the yogurt and pour into the cheesecloth.\n3. Gather the edges and tie them up.\n4. Refrigerate and let drain for 12-24 hours until thick and creamy.\n5. Spread labneh on a plate, drizzle with olive oil, and sprinkle with za'atar.\n6. Serve with warm pita bread.",
        "ingredients": [
            ("Plain whole-milk yogurt", 3.0, "cups"),
            ("Salt", 0.5, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Za'atar", 1.0, "tsp"),
        ],
    },
    {
        "title": "Manakeesh with Za'atar",
        "description": "Lebanese flatbread topped with a fragrant za'atar and olive oil mixture. A popular street breakfast.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 10,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget"],
        "instructions": "1. Mix flour, yeast, salt, olive oil, and warm water to form a soft dough.\n2. Knead for 8 minutes until smooth and elastic.\n3. Let the dough rise in a warm place for 1 hour.\n4. Divide into 4 balls and roll each out into a flat round.\n5. Mix za'atar with olive oil to form a paste and spread over each round.\n6. Bake at 230C for 8-10 minutes until edges are golden.\n7. Serve warm, folded or flat.",
        "ingredients": [
            ("All-purpose flour", 2.5, "cups"),
            ("Instant yeast", 1.0, "tsp"),
            ("Salt", 0.5, "tsp"),
            ("Olive oil", 3.0, "tbsp"),
            ("Warm water", 0.75, "cups"),
            ("Za'atar", 3.0, "tbsp"),
            ("Olive oil for topping", 3.0, "tbsp"),
        ],
    },
    {
        "title": "Kabsa",
        "description": "Saudi Arabian spiced rice with chicken, tomatoes, and warm spices. A festive one-pot rice dish.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 50,
        "servings": 6,
        "tags": ["one-pot", "high-protein", "budget"],
        "instructions": "1. Season chicken pieces with salt, black pepper, and kabsa spice mix.\n2. Brown chicken in oil in a large pot, then remove and set aside.\n3. Saute diced onion, garlic, and grated carrot in the same pot.\n4. Add tomato paste, diced tomatoes, and spices; cook for 2 minutes.\n5. Add rinsed rice and stir to coat.\n6. Place chicken on top of the rice and add water.\n7. Cover and cook on low heat for 25-30 minutes until rice is tender and chicken is cooked through.\n8. Serve on a large platter, placing chicken over the rice.",
        "ingredients": [
            ("Chicken pieces", 800.0, "g"),
            ("Basmati rice", 2.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Diced tomatoes", 1.0, "cups"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Kabsa spice mix", 2.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Water", 3.0, "cups"),
        ],
    },
    {
        "title": "Muhammarah",
        "description": "Syrian roasted red pepper and walnut dip with earthy cumin and tangy pomegranate molasses.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "quick", "budget"],
        "instructions": "1. Toast walnuts in a dry pan over medium heat until fragrant.\n2. Drain roasted red peppers and pat dry.\n3. Add peppers, walnuts, breadcrumbs, garlic, cumin, and chili flakes to a food processor.\n4. Pulse until coarsely blended, keeping some texture.\n5. Drizzle in olive oil and lemon juice while pulsing.\n6. Season with salt, transfer to a bowl, and drizzle with more olive oil.",
        "ingredients": [
            ("Roasted red peppers", 1.5, "cups"),
            ("Walnuts", 0.75, "cups"),
            ("Breadcrumbs", 0.25, "cups"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Ground cumin", 1.0, "tsp"),
            ("Chili flakes", 0.5, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Lemon juice", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Lentil Soup (Shorbat Adas)",
        "description": "Thick and warming red lentil soup spiced with cumin. A daily staple across the Middle East.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "one-pot", "budget", "high-protein"],
        "instructions": "1. Heat olive oil in a large pot and saute diced onion and garlic until softened.\n2. Add carrots and cook for 2 minutes.\n3. Stir in cumin and turmeric.\n4. Add rinsed red lentils and water; bring to a boil.\n5. Reduce heat and simmer for 20-25 minutes until lentils are completely soft.\n6. Blend with an immersion blender until smooth.\n7. Season with salt and lemon juice, and serve with a drizzle of olive oil.",
        "ingredients": [
            ("Red lentils", 1.5, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Carrots", 2.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Ground cumin", 1.0, "tsp"),
            ("Turmeric", 0.5, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Water", 5.0, "cups"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Fatayer Sabanekh (Spinach Pies)",
        "description": "Lebanese spinach-filled triangular pastries with lemon and sumac. A perfect savory snack or meze.",
        "difficulty": "medium",
        "prep_time": 40,
        "cook_time": 20,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "budget"],
        "instructions": "1. Make dough by mixing flour, yeast, salt, olive oil, and warm water; knead until smooth and let rise 1 hour.\n2. Wash and chop spinach finely, then squeeze out all excess moisture.\n3. Mix spinach with diced onion, lemon juice, sumac, and salt.\n4. Divide dough into small balls and roll each into a thin circle.\n5. Place a spoonful of filling in the center and fold into a triangle, pinching edges firmly.\n6. Place on a baking sheet and bake at 200C for 18-20 minutes until golden.",
        "ingredients": [
            ("All-purpose flour", 3.0, "cups"),
            ("Instant yeast", 1.0, "tsp"),
            ("Spinach", 400.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Sumac", 1.0, "tbsp"),
            ("Olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
            ("Warm water", 1.0, "cups"),
        ],
    },
    {
        "title": "Maqluba",
        "description": "Palestinian upside-down rice dish layered with chicken, fried eggplant, and aromatic spices.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 50,
        "servings": 6,
        "tags": ["one-pot", "high-protein", "budget"],
        "instructions": "1. Slice eggplant into rounds, salt and let sit 15 minutes, then pat dry and fry until golden.\n2. Season chicken pieces with turmeric, allspice, cinnamon, salt, and pepper; brown in a pot.\n3. Rinse rice and soak for 15 minutes.\n4. Layer fried eggplant at the bottom of a heavy pot.\n5. Add chicken on top of the eggplant, then the drained rice over the chicken.\n6. Pour in hot broth, cover tightly, and cook on low heat for 30 minutes.\n7. Let rest 10 minutes, then flip the pot onto a large serving platter.\n8. Garnish with toasted pine nuts and fresh parsley.",
        "ingredients": [
            ("Chicken pieces", 600.0, "g"),
            ("Basmati rice", 2.0, "cups"),
            ("Eggplant", 2.0, "pieces"),
            ("Turmeric", 1.0, "tsp"),
            ("Ground allspice", 0.5, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Chicken broth", 3.0, "cups"),
            ("Vegetable oil", 0.5, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Mejadra Hamra (Red Lentil Mujaddara)",
        "description": "Syrian red lentil and bulgur dish with caramelized onions. A lighter variation of classic mujaddara.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "budget", "one-pot", "high-protein"],
        "instructions": "1. Cook red lentils in water for 10 minutes until almost soft.\n2. Add fine bulgur and stir; reduce heat and cook for another 12-15 minutes.\n3. Meanwhile, thinly slice onions and fry in olive oil until deeply caramelized.\n4. Stir cumin and salt into the lentil-bulgur mixture.\n5. Serve topped with caramelized onions and a squeeze of lemon.",
        "ingredients": [
            ("Red lentils", 1.0, "cups"),
            ("Fine bulgur wheat", 1.0, "cups"),
            ("Onions", 3.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Ground cumin", 1.0, "tsp"),
            ("Water", 3.5, "cups"),
            ("Salt", 1.0, "tsp"),
            ("Lemon juice", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Shish Tawook",
        "description": "Lebanese garlic and yogurt marinated chicken skewers, grilled until charred and juicy.",
        "difficulty": "easy",
        "prep_time": 20,
        "cook_time": 12,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget"],
        "instructions": "1. Cut chicken breasts into 1-inch cubes.\n2. Whisk together yogurt, lemon juice, garlic, olive oil, paprika, and salt.\n3. Marinate chicken in the mixture for at least 1 hour, or overnight for best results.\n4. Thread chicken onto skewers.\n5. Grill over high heat for 10-12 minutes, turning every 3 minutes, until charred and cooked through.\n6. Serve with garlic sauce and pickled turnips.",
        "ingredients": [
            ("Chicken breast", 600.0, "g"),
            ("Plain yogurt", 0.5, "cups"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Paprika", 1.0, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Toum (Lebanese Garlic Sauce)",
        "description": "Intensely garlicky Lebanese whipped garlic sauce, fluffy and emulsified with lemon and oil.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 0,
        "servings": 6,
        "tags": ["vegetarian", "gluten-free", "quick", "budget"],
        "instructions": "1. Peel garlic cloves and add to a food processor with salt.\n2. Blend until finely minced.\n3. With the processor running, very slowly drizzle in vegetable oil a few drops at a time.\n4. Once the mixture begins to emulsify and thicken, alternate adding small amounts of lemon juice and oil.\n5. Continue until all oil and lemon juice are incorporated and the sauce is thick, white, and fluffy.\n6. Store in an airtight container in the refrigerator.",
        "ingredients": [
            ("Garlic cloves", 1.0, "cups"),
            ("Vegetable oil", 1.5, "cups"),
            ("Lemon juice", 3.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Bamia (Okra Stew)",
        "description": "Egyptian okra stew braised with tomatoes, garlic, and coriander. Often served over rice.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "one-pot", "budget"],
        "instructions": "1. Trim okra stems carefully without cutting into the pods.\n2. Heat olive oil and saute onion until translucent.\n3. Add garlic and ground coriander, cooking for 1 minute.\n4. Add diced tomatoes and tomato paste; simmer for 5 minutes.\n5. Add okra to the sauce and stir gently.\n6. Cover and cook on low heat for 25-30 minutes until okra is tender.\n7. Season with salt and lemon juice, and serve over white rice.",
        "ingredients": [
            ("Fresh okra", 500.0, "g"),
            ("Diced tomatoes", 1.5, "cups"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Ground coriander", 1.0, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Lemon juice", 1.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Makdous (Stuffed Baby Eggplant)",
        "description": "Syrian preserved baby eggplants stuffed with walnuts, garlic, and red pepper. A prized meze.",
        "difficulty": "hard",
        "prep_time": 40,
        "cook_time": 10,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Boil baby eggplants in salted water for 5-8 minutes until just tender but still firm.\n2. Drain and make a lengthwise slit in each eggplant.\n3. Press eggplants under a weight overnight to remove excess moisture.\n4. Chop walnuts finely and mix with minced garlic, chili flakes, and salt.\n5. Stuff each eggplant generously with the walnut mixture.\n6. Pack stuffed eggplants tightly into a jar and cover completely with olive oil.\n7. Seal and let cure at room temperature for 5-7 days before eating.",
        "ingredients": [
            ("Baby eggplants", 20.0, "pieces"),
            ("Walnuts", 1.0, "cups"),
            ("Garlic cloves", 8.0, "pieces"),
            ("Chili flakes", 1.0, "tbsp"),
            ("Olive oil", 2.0, "cups"),
            ("Salt", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Turkish Mercimek Kofte (Lentil Kofte)",
        "description": "Turkish red lentil and bulgur patties shaped by hand and served with lettuce wraps and lemon.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "budget", "high-protein"],
        "instructions": "1. Cook red lentils in water until very soft and water is absorbed, about 15 minutes.\n2. While still hot, stir in fine bulgur and cover; let sit 15 minutes to absorb.\n3. Saute diced onion in olive oil until soft, add tomato paste and cumin; cook 2 minutes.\n4. Mix the onion mixture into the lentil-bulgur base.\n5. Add finely chopped green onions and parsley.\n6. Season with salt and knead the mixture well.\n7. Shape into small oval patties.\n8. Serve at room temperature on lettuce leaves with a squeeze of lemon.",
        "ingredients": [
            ("Red lentils", 1.0, "cups"),
            ("Fine bulgur wheat", 0.75, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Green onions", 4.0, "pieces"),
            ("Fresh parsley", 0.5, "cups"),
            ("Ground cumin", 1.0, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Kofta Kebab",
        "description": "Spiced ground lamb or beef skewers grilled over charcoal. A street food staple from Turkey to Egypt.",
        "difficulty": "easy",
        "prep_time": 20,
        "cook_time": 10,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "quick", "budget"],
        "instructions": "1. Combine ground lamb with grated onion, minced garlic, parsley, cumin, allspice, and salt.\n2. Knead the mixture well with your hands for several minutes until sticky.\n3. Divide into portions and shape each around a flat metal skewer in an elongated oval.\n4. Grill over high heat for 3-4 minutes per side until charred outside and cooked through.\n5. Serve with flatbread, sliced onions, and a side of tahini sauce.",
        "ingredients": [
            ("Ground lamb", 500.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Fresh parsley", 0.25, "cups"),
            ("Ground cumin", 1.0, "tsp"),
            ("Ground allspice", 0.5, "tsp"),
            ("Salt", 1.0, "tsp"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Moussaka (Middle Eastern Style)",
        "description": "Layered eggplant and chickpea casserole baked in a spiced tomato sauce. A Levantine comfort dish.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 40,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Slice eggplant into rounds, brush with olive oil, and roast at 200C until golden, about 20 minutes.\n2. Saute onion and garlic in olive oil until soft.\n3. Add chickpeas, diced tomatoes, tomato paste, cumin, and allspice; simmer 10 minutes.\n4. Layer roasted eggplant slices in a baking dish.\n5. Spoon the chickpea-tomato sauce over the eggplant.\n6. Repeat layers and bake at 190C for 20 minutes.\n7. Let rest 10 minutes before serving.",
        "ingredients": [
            ("Eggplant", 2.0, "pieces"),
            ("Chickpeas (canned)", 1.5, "cups"),
            ("Diced tomatoes", 1.5, "cups"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Ground cumin", 1.0, "tsp"),
            ("Ground allspice", 0.5, "tsp"),
            ("Olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Fasulye Pilaki (Turkish White Bean Stew)",
        "description": "Turkish braised white beans in a tomato and olive oil sauce, served at room temperature.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "one-pot", "budget", "high-protein"],
        "instructions": "1. Heat olive oil and saute diced onion, carrot, and celery until softened.\n2. Add garlic and cook for 1 minute.\n3. Stir in tomato paste and diced tomatoes.\n4. Add drained white beans and enough water to just cover.\n5. Season with salt and pepper.\n6. Simmer uncovered for 25-30 minutes until sauce thickens.\n7. Let cool to room temperature, garnish with parsley, and serve.",
        "ingredients": [
            ("White beans (canned)", 2.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Carrot", 1.0, "pieces"),
            ("Celery stalk", 1.0, "pieces"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Diced tomatoes", 1.0, "cups"),
            ("Olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Dolma (Stuffed Grape Leaves)",
        "description": "Tender grape leaves rolled around a seasoned rice and herb filling. A beloved dish from Turkey to Iraq.",
        "difficulty": "hard",
        "prep_time": 45,
        "cook_time": 45,
        "servings": 6,
        "tags": ["vegetarian", "vegan", "budget"],
        "instructions": "1. Rinse grape leaves and blanch briefly in boiling water; drain.\n2. Mix rice with diced onion, chopped parsley, chopped mint, tomato paste, allspice, and lemon juice.\n3. Place a grape leaf shiny-side down and add a spoonful of filling near the stem.\n4. Fold in the sides and roll up tightly into a small cigar shape.\n5. Line the bottom of a pot with extra grape leaves to prevent sticking.\n6. Pack rolled dolma tightly in the pot in layers.\n7. Add water and lemon juice, place a plate on top to weigh them down.\n8. Simmer on low heat for 40-45 minutes until rice is cooked through.",
        "ingredients": [
            ("Grape leaves", 50.0, "pieces"),
            ("Short-grain rice", 1.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Fresh parsley", 0.5, "cups"),
            ("Fresh mint", 0.25, "cups"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Ground allspice", 1.0, "tsp"),
            ("Lemon juice", 3.0, "tbsp"),
            ("Olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Chicken Shawarma",
        "description": "Spiced and marinated chicken roasted and sliced thin, inspired by the rotating spit street food.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 25,
        "servings": 4,
        "tags": ["high-protein", "budget"],
        "instructions": "1. Slice chicken thighs and place in a bowl.\n2. Mix yogurt, lemon juice, garlic, cumin, paprika, turmeric, cinnamon, and salt.\n3. Pour marinade over chicken and toss well; marinate for at least 2 hours.\n4. Spread chicken on a baking sheet in a single layer.\n5. Roast at 220C for 20-25 minutes until edges are charred and crispy.\n6. Slice thinly and serve in pita with pickles, tahini, and vegetables.",
        "ingredients": [
            ("Chicken thighs (boneless)", 600.0, "g"),
            ("Plain yogurt", 0.25, "cups"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Ground cumin", 1.5, "tsp"),
            ("Paprika", 1.0, "tsp"),
            ("Turmeric", 0.5, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Balila (Warm Chickpea Salad)",
        "description": "Lebanese warm chickpea dish dressed with lemon, garlic, and olive oil. A humble yet satisfying breakfast.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "tags": ["vegetarian", "vegan", "gluten-free", "quick", "budget", "high-protein"],
        "instructions": "1. Heat chickpeas in a saucepan with a little of their liquid until warmed through.\n2. Drain and place in a serving bowl.\n3. Add minced garlic, lemon juice, and cumin.\n4. Drizzle generously with olive oil.\n5. Season with salt and sprinkle with chopped parsley.\n6. Serve warm with flatbread for scooping.",
        "ingredients": [
            ("Chickpeas (canned)", 2.0, "cups"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Ground cumin", 0.5, "tsp"),
            ("Fresh parsley", 2.0, "tbsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Tahini Sauce",
        "description": "Versatile sesame sauce used across Middle Eastern cuisine for drizzling, dipping, and dressing.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 0,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "quick", "budget"],
        "instructions": "1. In a bowl, whisk tahini with lemon juice.\n2. Add cold water gradually, whisking constantly, until the sauce reaches a smooth pouring consistency.\n3. Stir in minced garlic and salt.\n4. Taste and adjust lemon juice and salt.\n5. Drizzle with olive oil if desired and serve.",
        "ingredients": [
            ("Tahini", 0.5, "cups"),
            ("Lemon juice", 3.0, "tbsp"),
            ("Cold water", 0.25, "cups"),
            ("Garlic clove", 1.0, "pieces"),
            ("Salt", 0.25, "tsp"),
        ],
    },
    {
        "title": "Iraqi Tashreeb (Bread and Broth Soup)",
        "description": "Iraqi comfort dish of flatbread soaked in a spiced chickpea and tomato broth.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["budget", "one-pot", "high-protein"],
        "instructions": "1. Heat oil in a pot and saute onion and garlic until softened.\n2. Add diced tomatoes, tomato paste, turmeric, cumin, and baharat spice.\n3. Pour in broth and bring to a boil.\n4. Add drained chickpeas and simmer for 15 minutes.\n5. Tear flatbread into pieces and place in serving bowls.\n6. Ladle the hot broth and chickpeas over the bread.\n7. Garnish with fresh parsley and a squeeze of lemon.",
        "ingredients": [
            ("Flatbread", 2.0, "pieces"),
            ("Chickpeas (canned)", 1.5, "cups"),
            ("Chicken broth", 3.0, "cups"),
            ("Diced tomatoes", 1.0, "cups"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Turmeric", 0.5, "tsp"),
            ("Baharat spice", 1.0, "tsp"),
        ],
    },
    {
        "title": "Loubieh Bi Zeit (Green Beans in Olive Oil)",
        "description": "Lebanese green beans braised in tomato sauce with olive oil and garlic. Served at room temperature.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Trim green beans and cut into 2-inch pieces.\n2. Heat olive oil in a pot and saute diced onion until translucent.\n3. Add garlic and cook 1 minute.\n4. Add diced tomatoes, tomato paste, and water.\n5. Add green beans and season with salt.\n6. Cover and simmer for 25-30 minutes until beans are very tender.\n7. Let cool to room temperature before serving.",
        "ingredients": [
            ("Green beans", 500.0, "g"),
            ("Diced tomatoes", 1.0, "cups"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Water", 0.5, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Musakhan",
        "description": "Palestinian roasted chicken on taboon bread with caramelized onions and sumac. A festive national dish.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 50,
        "servings": 4,
        "tags": ["high-protein", "budget"],
        "instructions": "1. Slice onions thinly and cook in olive oil over medium heat for 20 minutes until deeply caramelized.\n2. Stir sumac into the onions and cook 2 more minutes.\n3. Season chicken pieces with salt, allspice, and black pepper.\n4. Spread half the onion mixture over flatbread on a baking sheet.\n5. Place chicken on top and cover with remaining onions.\n6. Roast at 200C for 30-35 minutes until chicken is golden and cooked through.\n7. Garnish with toasted pine nuts and serve.",
        "ingredients": [
            ("Chicken pieces", 800.0, "g"),
            ("Onions", 4.0, "pieces"),
            ("Sumac", 3.0, "tbsp"),
            ("Olive oil", 4.0, "tbsp"),
            ("Ground allspice", 1.0, "tsp"),
            ("Flatbread", 2.0, "pieces"),
            ("Pine nuts", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Turkish Karniyarik (Stuffed Eggplant)",
        "description": "Turkish eggplant split open and stuffed with spiced ground beef, tomatoes, and peppers.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 40,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget"],
        "instructions": "1. Peel eggplants in alternating strips and fry in oil until softened; drain on paper towels.\n2. Saute diced onion and garlic in olive oil until soft.\n3. Add ground beef and cook until browned.\n4. Stir in diced tomatoes, bell pepper, parsley, cumin, and salt.\n5. Slit each eggplant lengthwise without cutting through.\n6. Stuff generously with the meat mixture.\n7. Place in a baking dish, add a splash of water, and bake at 190C for 25 minutes.",
        "ingredients": [
            ("Eggplants", 4.0, "pieces"),
            ("Ground beef", 300.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Tomatoes", 2.0, "pieces"),
            ("Green bell pepper", 1.0, "pieces"),
            ("Fresh parsley", 0.25, "cups"),
            ("Ground cumin", 0.5, "tsp"),
            ("Olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Sambousek (Meat Pies)",
        "description": "Crispy fried Lebanese pastry pockets filled with spiced ground meat, onions, and pine nuts.",
        "difficulty": "medium",
        "prep_time": 40,
        "cook_time": 15,
        "servings": 6,
        "tags": ["budget", "high-protein"],
        "instructions": "1. Mix flour, salt, and olive oil, then add water gradually to form a smooth dough; rest 30 minutes.\n2. Saute onion until soft, add ground beef, allspice, cinnamon, and salt; cook until browned.\n3. Stir in pine nuts and remove from heat.\n4. Roll dough thin and cut into circles.\n5. Place a spoonful of filling on each circle, fold into a half-moon, and seal edges with a fork.\n6. Deep fry in hot oil for 3-4 minutes until golden and crispy.\n7. Drain on paper towels and serve warm.",
        "ingredients": [
            ("All-purpose flour", 2.0, "cups"),
            ("Ground beef", 300.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Pine nuts", 2.0, "tbsp"),
            ("Ground allspice", 0.5, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Olive oil", 3.0, "tbsp"),
            ("Vegetable oil", 2.0, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Hindbeh (Dandelion Greens with Onions)",
        "description": "Lebanese sauteed dandelion greens with caramelized onions and lemon. A bitter green delicacy.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "quick", "budget"],
        "instructions": "1. Wash dandelion greens thoroughly and chop roughly.\n2. Blanch greens in boiling salted water for 3-4 minutes, then drain.\n3. Slice onion thinly and fry in olive oil until caramelized.\n4. Toss the blanched greens into the pan with the onions.\n5. Squeeze lemon juice over the top and season with salt.\n6. Serve warm or at room temperature.",
        "ingredients": [
            ("Dandelion greens", 500.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Olive oil", 3.0, "tbsp"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Persian Kuku Sabzi (Herb Frittata)",
        "description": "Iranian baked herb frittata packed with fresh herbs, walnuts, and barberries. A Nowruz tradition.",
        "difficulty": "medium",
        "prep_time": 20,
        "cook_time": 35,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget"],
        "instructions": "1. Finely chop parsley, cilantro, dill, and chives.\n2. Beat eggs in a large bowl and mix in all the chopped herbs.\n3. Add chopped walnuts, turmeric, salt, and pepper.\n4. Heat olive oil in an oven-safe skillet over medium heat.\n5. Pour in the egg mixture and cook on the stove for 5 minutes.\n6. Transfer to the oven at 180C and bake for 25-30 minutes until set and golden.\n7. Let cool slightly, slice into wedges, and serve.",
        "ingredients": [
            ("Eggs", 6.0, "pieces"),
            ("Fresh parsley", 1.0, "cups"),
            ("Fresh cilantro", 1.0, "cups"),
            ("Fresh dill", 0.5, "cups"),
            ("Fresh chives", 0.5, "cups"),
            ("Walnuts", 0.25, "cups"),
            ("Turmeric", 0.5, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Fatteh (Chickpea and Bread Casserole)",
        "description": "Layered Syrian-Lebanese dish of toasted bread, chickpeas, yogurt, and pine nuts.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "tags": ["vegetarian", "budget", "high-protein"],
        "instructions": "1. Tear pita bread into pieces and toast or fry until crispy and golden.\n2. Heat chickpeas in their liquid with a pinch of cumin.\n3. Mix yogurt with minced garlic, lemon juice, and tahini.\n4. Toast pine nuts in a little butter until golden.\n5. Layer crispy bread in a serving dish.\n6. Spoon warm chickpeas with some liquid over the bread.\n7. Pour the yogurt-tahini sauce over everything.\n8. Top with toasted pine nuts and a sprinkle of paprika.",
        "ingredients": [
            ("Pita bread", 2.0, "pieces"),
            ("Chickpeas (canned)", 2.0, "cups"),
            ("Plain yogurt", 1.0, "cups"),
            ("Tahini", 2.0, "tbsp"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Lemon juice", 1.0, "tbsp"),
            ("Pine nuts", 2.0, "tbsp"),
            ("Ground cumin", 0.5, "tsp"),
            ("Paprika", 0.25, "tsp"),
        ],
    },
    {
        "title": "Bazella w Riz (Peas and Rice)",
        "description": "Lebanese one-pot dish of green peas with spiced ground meat served over fluffy rice.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["one-pot", "budget", "high-protein"],
        "instructions": "1. Brown ground beef with diced onion in a pot.\n2. Add garlic, cinnamon, and allspice; cook 1 minute.\n3. Stir in tomato paste and diced tomatoes.\n4. Add frozen peas and enough water to create a stew.\n5. Simmer for 15-20 minutes until peas are tender.\n6. Meanwhile, cook rice separately until fluffy.\n7. Serve the pea stew over rice.",
        "ingredients": [
            ("Ground beef", 300.0, "g"),
            ("Frozen peas", 2.0, "cups"),
            ("Long-grain rice", 1.5, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Diced tomatoes", 0.5, "cups"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Ground allspice", 0.5, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Hashweh (Spiced Rice with Meat)",
        "description": "Lebanese festive rice with ground lamb, toasted nuts, and warm spices. Served at celebrations.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 6,
        "tags": ["high-protein", "budget"],
        "instructions": "1. Brown ground lamb in a pot, breaking it up into fine crumbles.\n2. Add diced onion and cook until softened.\n3. Season with cinnamon, allspice, cumin, salt, and pepper.\n4. Add rinsed rice and stir to coat in the fat.\n5. Pour in water, bring to a boil, then cover and reduce to low heat.\n6. Cook for 18-20 minutes until rice is tender and water is absorbed.\n7. Toast almonds and pine nuts in butter.\n8. Fluff rice and serve topped with the toasted nuts.",
        "ingredients": [
            ("Ground lamb", 300.0, "g"),
            ("Long-grain rice", 2.0, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Ground cinnamon", 0.5, "tsp"),
            ("Ground allspice", 0.5, "tsp"),
            ("Almonds", 2.0, "tbsp"),
            ("Pine nuts", 2.0, "tbsp"),
            ("Water", 3.0, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Turkish Ezogelin Soup",
        "description": "Turkish bride's soup with red lentils, bulgur, and tomato. Named after a famous folk story bride.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "one-pot", "budget", "high-protein"],
        "instructions": "1. Heat olive oil in a pot and saute diced onion until translucent.\n2. Add tomato paste and red pepper paste; cook for 2 minutes.\n3. Add red lentils, bulgur, and water; stir well.\n4. Bring to a boil, then simmer for 20 minutes until lentils and bulgur are soft.\n5. Season with salt, cumin, and chili flakes.\n6. Stir in lemon juice and serve with an extra drizzle of olive oil.",
        "ingredients": [
            ("Red lentils", 1.0, "cups"),
            ("Fine bulgur wheat", 0.25, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato paste", 2.0, "tbsp"),
            ("Red pepper paste", 1.0, "tbsp"),
            ("Ground cumin", 1.0, "tsp"),
            ("Chili flakes", 0.5, "tsp"),
            ("Water", 5.0, "cups"),
            ("Olive oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Persian Ash Reshteh (Noodle Soup)",
        "description": "Thick Iranian herb and legume noodle soup topped with kashk, fried onions, and fried mint.",
        "difficulty": "hard",
        "prep_time": 30,
        "cook_time": 60,
        "servings": 6,
        "tags": ["vegetarian", "budget", "high-protein", "one-pot"],
        "instructions": "1. Soak chickpeas and kidney beans overnight, then drain.\n2. Cook chickpeas and kidney beans in water until tender, about 40 minutes.\n3. Add chopped spinach, parsley, cilantro, and dill to the pot.\n4. Add lentils and cook another 15 minutes.\n5. Add flat noodles and cook until they are tender.\n6. Season with turmeric, salt, and pepper.\n7. Fry sliced onions until crispy, and fry dried mint in oil separately.\n8. Serve soup topped with fried onions, fried mint oil, and a dollop of yogurt.",
        "ingredients": [
            ("Dried chickpeas", 0.5, "cups"),
            ("Kidney beans", 0.5, "cups"),
            ("Green lentils", 0.5, "cups"),
            ("Flat noodles", 200.0, "g"),
            ("Spinach", 2.0, "cups"),
            ("Fresh parsley", 1.0, "cups"),
            ("Fresh cilantro", 0.5, "cups"),
            ("Onions", 2.0, "pieces"),
            ("Turmeric", 1.0, "tsp"),
            ("Dried mint", 1.0, "tbsp"),
        ],
    },
    {
        "title": "Msabbaha (Warm Hummus with Whole Chickpeas)",
        "description": "Palestinian warm chickpea dish similar to hummus but chunkier, served with pools of tahini and olive oil.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "quick", "budget", "high-protein"],
        "instructions": "1. Warm chickpeas in a saucepan with some of their liquid.\n2. In a serving bowl, spread a generous amount of tahini.\n3. Spoon the warm chickpeas with their liquid over the tahini.\n4. Add minced garlic, lemon juice, and cumin.\n5. Drizzle with olive oil and sprinkle with paprika.\n6. Serve immediately with warm pita for scooping.",
        "ingredients": [
            ("Chickpeas (canned)", 2.0, "cups"),
            ("Tahini", 3.0, "tbsp"),
            ("Lemon juice", 2.0, "tbsp"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Ground cumin", 0.5, "tsp"),
            ("Paprika", 0.5, "tsp"),
            ("Salt", 1.0, "to taste"),
        ],
    },
    {
        "title": "Menemen (Turkish Scrambled Eggs with Tomatoes)",
        "description": "Turkish breakfast scramble of eggs cooked with tomatoes, peppers, and spices in one pan.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 2,
        "tags": ["vegetarian", "gluten-free", "quick", "one-pot", "budget"],
        "instructions": "1. Heat olive oil in a skillet over medium heat.\n2. Saute diced green pepper and onion until softened.\n3. Add diced tomatoes and cook until they break down, about 5 minutes.\n4. Season with chili flakes and salt.\n5. Crack eggs directly into the pan and stir gently.\n6. Cook, stirring occasionally, until eggs are just set but still creamy.\n7. Serve immediately in the pan with crusty bread.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Tomatoes", 3.0, "pieces"),
            ("Green pepper", 1.0, "pieces"),
            ("Onion", 0.5, "pieces"),
            ("Olive oil", 1.0, "tbsp"),
            ("Chili flakes", 0.25, "tsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Bulgur Pilaf",
        "description": "Simple Turkish bulgur wheat cooked with tomato paste and peppers. A lighter alternative to rice.",
        "difficulty": "easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "quick", "budget", "one-pot"],
        "instructions": "1. Heat olive oil in a saucepan and saute diced onion until softened.\n2. Add tomato paste and diced green pepper; cook for 2 minutes.\n3. Add coarse bulgur and stir to coat.\n4. Pour in boiling water and add salt.\n5. Cover, reduce heat to low, and cook for 12-15 minutes until liquid is absorbed.\n6. Remove from heat and let steam with the lid on for 5 minutes before fluffing.",
        "ingredients": [
            ("Coarse bulgur wheat", 1.5, "cups"),
            ("Onion", 1.0, "pieces"),
            ("Tomato paste", 1.0, "tbsp"),
            ("Green pepper", 1.0, "pieces"),
            ("Olive oil", 2.0, "tbsp"),
            ("Boiling water", 2.5, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Za'atar Eggs",
        "description": "Fried eggs topped with za'atar and olive oil. The simplest Levantine breakfast done right.",
        "difficulty": "easy",
        "prep_time": 2,
        "cook_time": 5,
        "servings": 2,
        "tags": ["vegetarian", "gluten-free", "quick", "budget"],
        "instructions": "1. Heat olive oil in a non-stick skillet over medium heat.\n2. Crack eggs into the pan and fry until whites are set.\n3. Sprinkle za'atar generously over the eggs.\n4. Season with salt and a pinch of chili flakes if desired.\n5. Serve immediately with warm pita bread.",
        "ingredients": [
            ("Eggs", 4.0, "pieces"),
            ("Olive oil", 1.0, "tbsp"),
            ("Za'atar", 1.0, "tbsp"),
            ("Salt", 1.0, "pinch"),
            ("Chili flakes", 1.0, "pinch"),
        ],
    },
    {
        "title": "Kabab Koobideh (Persian Ground Meat Kebab)",
        "description": "Iranian ground beef kebab with onion, saffron, and sumac, grilled on flat skewers over charcoal.",
        "difficulty": "medium",
        "prep_time": 25,
        "cook_time": 10,
        "servings": 4,
        "tags": ["gluten-free", "high-protein", "budget"],
        "instructions": "1. Grate onion and squeeze out all the juice through a cheesecloth.\n2. Mix ground beef with the grated onion, salt, black pepper, and turmeric.\n3. Knead the meat vigorously for 5-10 minutes until very sticky and smooth.\n4. Refrigerate for 1 hour.\n5. Shape meat onto wide flat skewers in a long thin form.\n6. Grill over high heat for 3-4 minutes per side.\n7. Serve with basmati rice, grilled tomatoes, and sumac.",
        "ingredients": [
            ("Ground beef (80/20)", 500.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Turmeric", 0.5, "tsp"),
            ("Sumac", 1.0, "tsp"),
            ("Salt", 1.0, "tsp"),
            ("Black pepper", 0.5, "tsp"),
        ],
    },
    {
        "title": "Persian Zereshk Polo (Barberry Rice)",
        "description": "Aromatic Iranian saffron rice studded with tart barberries and toasted with a crispy tahdig crust.",
        "difficulty": "hard",
        "prep_time": 20,
        "cook_time": 50,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget"],
        "instructions": "1. Soak basmati rice in salted water for 1-2 hours, then drain.\n2. Parboil rice in a large pot of boiling salted water for 5-6 minutes; drain.\n3. Bloom saffron threads in 2 tablespoons of hot water.\n4. Mix a cup of rice with saffron water and a tablespoon of oil for the tahdig layer.\n5. Spread saffron rice on the bottom of an oiled pot.\n6. Layer remaining rice on top and poke holes with a spoon handle.\n7. Saute barberries in butter just until plumped.\n8. Cook rice covered on low heat for 40 minutes, then serve inverted with barberries on top.",
        "ingredients": [
            ("Basmati rice", 2.0, "cups"),
            ("Dried barberries", 0.5, "cups"),
            ("Saffron threads", 0.5, "tsp"),
            ("Butter", 2.0, "tbsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Warak Enab (Stuffed Grape Leaves with Meat)",
        "description": "Lebanese grape leaves stuffed with rice, ground lamb, and spices. Slow-cooked until tender.",
        "difficulty": "hard",
        "prep_time": 45,
        "cook_time": 60,
        "servings": 6,
        "tags": ["budget", "high-protein"],
        "instructions": "1. Blanch grape leaves in boiling water for 2 minutes, then drain.\n2. Mix ground lamb with rice, diced tomato, allspice, cinnamon, salt, and pepper.\n3. Place a leaf flat on the counter, add a spoonful of filling near the stem end.\n4. Fold in sides and roll tightly.\n5. Line a pot with spare leaves, then pack rolls seam-side down.\n6. Add water, lemon juice, and a plate to weigh them down.\n7. Simmer on low heat for 60 minutes until rice and meat are cooked.\n8. Serve warm with yogurt on the side.",
        "ingredients": [
            ("Grape leaves", 50.0, "pieces"),
            ("Ground lamb", 250.0, "g"),
            ("Short-grain rice", 1.0, "cups"),
            ("Tomato", 1.0, "pieces"),
            ("Ground allspice", 1.0, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Lemon juice", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Mutabbal",
        "description": "Smoky eggplant and yogurt dip, creamier than baba ghanoush. A Syrian and Iraqi favorite.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget"],
        "instructions": "1. Char eggplants over a flame or under a broiler until completely soft.\n2. Peel off the charred skin and drain the flesh.\n3. Mash the eggplant with a fork.\n4. Mix in yogurt, tahini, garlic, lemon juice, and salt.\n5. Spread on a plate, drizzle with olive oil, and sprinkle with paprika.\n6. Serve with warm flatbread.",
        "ingredients": [
            ("Large eggplants", 2.0, "pieces"),
            ("Plain yogurt", 0.25, "cups"),
            ("Tahini", 2.0, "tbsp"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Lemon juice", 1.0, "tbsp"),
            ("Olive oil", 1.0, "tbsp"),
            ("Salt", 0.5, "tsp"),
        ],
    },
    {
        "title": "Arayes (Grilled Meat-Stuffed Pita)",
        "description": "Lebanese pita bread stuffed with spiced ground meat and grilled until crispy. A popular street snack.",
        "difficulty": "easy",
        "prep_time": 15,
        "cook_time": 10,
        "servings": 4,
        "tags": ["high-protein", "quick", "budget"],
        "instructions": "1. Mix ground beef with diced onion, minced garlic, parsley, allspice, cumin, and salt.\n2. Cut pita breads in half to form pockets.\n3. Stuff each pita half generously with the meat mixture, spreading it evenly.\n4. Brush the outside with olive oil.\n5. Grill on a hot grill or grill pan for 3-4 minutes per side until pita is crispy and meat is cooked.\n6. Serve hot with tahini sauce and pickles.",
        "ingredients": [
            ("Ground beef", 400.0, "g"),
            ("Pita bread", 4.0, "pieces"),
            ("Onion", 1.0, "pieces"),
            ("Garlic cloves", 2.0, "pieces"),
            ("Fresh parsley", 0.25, "cups"),
            ("Ground allspice", 0.5, "tsp"),
            ("Ground cumin", 0.5, "tsp"),
            ("Olive oil", 1.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Shorbet Freekeh (Freekeh Soup)",
        "description": "Syrian smoky green wheat soup with chicken. Freekeh gives a distinctive nutty, smoky flavor.",
        "difficulty": "medium",
        "prep_time": 10,
        "cook_time": 45,
        "servings": 4,
        "tags": ["high-protein", "one-pot", "budget"],
        "instructions": "1. Rinse freekeh and soak for 10 minutes, then drain.\n2. Brown chicken pieces in olive oil in a large pot; remove and set aside.\n3. Saute diced onion in the same pot until softened.\n4. Add freekeh, cumin, cinnamon, and salt; stir for 1 minute.\n5. Return chicken to the pot and add water.\n6. Bring to a boil, then simmer for 35-40 minutes until freekeh is tender.\n7. Serve hot, garnished with fresh parsley.",
        "ingredients": [
            ("Freekeh", 1.0, "cups"),
            ("Chicken pieces", 500.0, "g"),
            ("Onion", 1.0, "pieces"),
            ("Ground cumin", 1.0, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Olive oil", 2.0, "tbsp"),
            ("Water", 5.0, "cups"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Batata Harra (Spicy Potatoes)",
        "description": "Lebanese crispy fried potatoes tossed with garlic, chili, cilantro, and lemon. A beloved meze.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget"],
        "instructions": "1. Cut potatoes into 1-inch cubes.\n2. Fry potatoes in vegetable oil until golden and crispy; drain on paper towels.\n3. In the same pan, saute minced garlic and chili flakes in olive oil for 30 seconds.\n4. Add the fried potatoes back and toss with chopped cilantro.\n5. Squeeze lemon juice over the top and season with salt.\n6. Serve hot as a meze or side dish.",
        "ingredients": [
            ("Potatoes", 4.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Chili flakes", 0.5, "tsp"),
            ("Lemon juice", 1.0, "tbsp"),
            ("Vegetable oil", 0.5, "cups"),
            ("Olive oil", 1.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Kousa Mahshi (Stuffed Zucchini)",
        "description": "Syrian hollowed zucchini stuffed with rice and spiced meat, simmered in a tomato broth.",
        "difficulty": "hard",
        "prep_time": 35,
        "cook_time": 45,
        "servings": 4,
        "tags": ["budget", "high-protein"],
        "instructions": "1. Hollow out zucchini using a corer, leaving a thin wall. Save the pulp.\n2. Mix ground beef with rice, diced tomato, allspice, cinnamon, and salt.\n3. Stuff each zucchini about three-quarters full to allow rice to expand.\n4. Make the sauce: saute garlic in oil, add crushed tomatoes and water.\n5. Place stuffed zucchini upright in the pot and pour sauce over them.\n6. Cover and simmer on low heat for 40-45 minutes until zucchini is tender and rice is cooked.\n7. Serve with the tomato broth spooned over.",
        "ingredients": [
            ("Zucchini", 6.0, "pieces"),
            ("Ground beef", 250.0, "g"),
            ("Short-grain rice", 0.5, "cups"),
            ("Tomato", 1.0, "pieces"),
            ("Crushed tomatoes", 1.5, "cups"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Ground allspice", 0.5, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Persian Mirza Ghasemi (Smoky Eggplant and Tomato)",
        "description": "Northern Iranian dish of smoky charred eggplant cooked down with tomatoes, garlic, and eggs.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget"],
        "instructions": "1. Char eggplants over a flame until skin is blackened and flesh is completely soft.\n2. Peel and roughly mash the eggplant flesh.\n3. Saute minced garlic in oil for 30 seconds.\n4. Add diced tomatoes and cook until broken down, about 10 minutes.\n5. Stir in the mashed eggplant and turmeric; cook for 5 minutes.\n6. Crack eggs into the mixture and stir until just set.\n7. Season with salt and pepper, and serve with bread.",
        "ingredients": [
            ("Large eggplants", 3.0, "pieces"),
            ("Tomatoes", 4.0, "pieces"),
            ("Garlic cloves", 4.0, "pieces"),
            ("Eggs", 3.0, "pieces"),
            ("Turmeric", 0.5, "tsp"),
            ("Vegetable oil", 2.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Adas Polo (Persian Lentil Rice)",
        "description": "Iranian rice layered with lentils, raisins, and caramelized onions, featuring a golden tahdig crust.",
        "difficulty": "medium",
        "prep_time": 15,
        "cook_time": 50,
        "servings": 4,
        "tags": ["vegetarian", "gluten-free", "budget", "high-protein"],
        "instructions": "1. Soak basmati rice in salted water for 1 hour, then drain.\n2. Cook green lentils until just tender, about 20 minutes; drain.\n3. Parboil rice for 5 minutes in boiling salted water; drain.\n4. Caramelize sliced onions in oil until deeply golden.\n5. Mix a cup of rice with oil and a splash of water for the tahdig.\n6. Layer tahdig rice on the bottom of an oiled pot, then alternate layers of rice and lentils.\n7. Cover and cook on low heat for 35 minutes.\n8. Invert onto a platter and top with caramelized onions.",
        "ingredients": [
            ("Basmati rice", 2.0, "cups"),
            ("Green lentils", 0.75, "cups"),
            ("Onions", 2.0, "pieces"),
            ("Vegetable oil", 3.0, "tbsp"),
            ("Turmeric", 0.5, "tsp"),
            ("Ground cinnamon", 0.25, "tsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
    {
        "title": "Egyptian Besarah (Fava Bean Dip)",
        "description": "Creamy Egyptian dip made from dried fava beans blended with herbs, garlic, and cumin.",
        "difficulty": "easy",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "tags": ["vegetarian", "vegan", "gluten-free", "budget", "high-protein"],
        "instructions": "1. Cook split dried fava beans in water until very soft, about 20 minutes.\n2. Drain, reserving some cooking liquid.\n3. Blend beans with garlic, dill, cilantro, cumin, and salt.\n4. Add cooking liquid as needed for a smooth, thick consistency.\n5. Spread on a plate and drizzle generously with olive oil.\n6. Serve at room temperature with bread.",
        "ingredients": [
            ("Split dried fava beans", 1.5, "cups"),
            ("Garlic cloves", 3.0, "pieces"),
            ("Fresh dill", 0.5, "cups"),
            ("Fresh cilantro", 0.25, "cups"),
            ("Ground cumin", 1.0, "tsp"),
            ("Olive oil", 3.0, "tbsp"),
            ("Salt", 1.0, "tsp"),
        ],
    },
]
